import HodgeReduction.HCGapL4.ShiftedCorrespondenceSHSM2
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.ShiftedCorrespondenceSHSM2
open HodgeReduction

#print axioms ShiftedMTCorrespondencePackageAt_SHSM2_toRaw
#print axioms identity_ShiftedMTCorrespondencePackageAt_SHSM2
#print axioms ShiftedMTCorrespondencePackageAt_SHSM2_compose
#print axioms ShiftedMTCorrespondencePackageAt_SHSM2_point_to_ellipticCurve_codim0_to_codim1
#print axioms ShiftedMTCorrespondencePackageAt_SHSM2_point_to_E_via_composition
#print axioms VarietyHCAt_ellipticCurve_codim1_via_SHSM2_composed_correspondence
#print axioms R218_does_not_close_mtCorrespondencePackage
#print axioms R218_does_not_delete_v1
#print axioms R218_does_not_implement_real_chow_composition
#print axioms R218_does_not_prove_categorical_associativity_v2
#print axioms R218_does_not_develop_v1_v2_bridge
#print axioms hodgeConjectureReal_canonical
