import HodgeReduction.HCGapL4.ShiftedCorrespondenceSHSM2Bridge
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.ShiftedCorrespondenceSHSM2Bridge
open HodgeReduction

#print axioms ShiftedMTCorrespondencePackageAt_SHSM_to_SHSM2
#print axioms bridged_SHSM2_point_to_ellipticCurve_codim0_to_codim1
#print axioms bridged_SHSM2_point_to_E_via_composition_v2
#print axioms VarietyHCAt_ellipticCurve_codim1_via_bridged_SHSM2_route
#print axioms R219_does_not_prove_backward_bridge
#print axioms R219_does_not_close_mtCorrespondencePackage
#print axioms R219_does_not_make_v1_obsolete
#print axioms hodgeConjectureReal_canonical
