import HodgeReduction.HCGapL4.SHSM2MultiStep
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.SHSM2MultiStep
open HodgeReduction

#print axioms ShiftedMTCorrespondencePackageAt_SHSM2_compose3
#print axioms VarietyHCAt_of_SHSM2_composed3
#print axioms SHSM2_point_to_E_via_three_step_composition
#print axioms VarietyHCAt_ellipticCurve_codim1_via_SHSM2_three_step_composition
#print axioms R220_does_not_close_mtCorrespondencePackage
#print axioms R220_does_not_prove_categorical_associativity
#print axioms R220_does_not_implement_real_chow_multistep
#print axioms R220_only_operational_multistep_not_bracketing_equality
#print axioms hodgeConjectureReal_canonical
