import HodgeReduction.HCGapL4.InternalCycleActionWithProductCycle
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.InternalCycleActionWithProductCycle
open HodgeReduction

#print axioms InternalCycleActionData_SHSM_WithProductCycle.to_SHSM
#print axioms InternalCycleActionData_SHSM_WithProductCycle.to_SHSM2
#print axioms internalCycleActionData_SHSM_WithProductCycle_point_to_ellipticCurve
#print axioms SHSM2_point_to_E_from_productCycleFactory
#print axioms VarietyHCAt_ellipticCurve_codim1_via_productCycleFactory
#print axioms VarietyHCAt_ellipticCurve_codim1_via_productCycleFactory_compose3
#print axioms R223_does_not_close_mtCorrespondencePackage
#print axioms R223_does_not_implement_true_chow_functoriality
#print axioms R223_does_not_prove_cycle_induces_action
#print axioms R223_does_not_implement_pushforward_pullback_cup
#print axioms R223_only_records_product_cycle_provenance
#print axioms hodgeConjectureReal_canonical
