import HodgeReduction.HCGapL4.ProductCohomologyPointProjectiveLine
import HodgeReduction.HCGapL4.PtToProjectiveLineProductCycleFactory
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.ProductCohomologyPointProjectiveLine
open HodgeReduction.HCGapL4.PtToProjectiveLineProductCycleFactory
open HodgeReduction

#print axioms VarietyCohomologyData_pointTimesProjectiveLine
#print axioms pointTimesProjectiveLineCycleClassFamily
#print axioms AlgebraicClassesData_pointTimesProjectiveLine
#print axioms cycleAction_H0_to_H2_pointToProjectiveLine
#print axioms cycleAction_H0_to_H2_preserves_algClasses_point_to_projectiveLine
#print axioms internalCycleActionData_SHSM_point_to_projectiveLine
#print axioms internalCycleActionData_SHSM_WithProductCycle_point_to_projectiveLine
#print axioms SHSM2_point_to_projectiveLine_from_productCycleFactory
#print axioms VarietyHCAt_projectiveLine_codim1_via_productCycleFactory
#print axioms VarietyHCAt_projectiveLine_codim1_via_productCycleFactory_compose3
#print axioms R224_does_not_close_mtCorrespondencePackage
#print axioms R224_does_not_implement_general_product
#print axioms R224_does_not_implement_true_chow_functoriality
#print axioms R224_only_second_product_cycle_factory_instance
#print axioms hodgeConjectureReal_canonical
