import HodgeReduction.HCGapL4.ProductCohomologyProjectiveLineEllipticCurve
import HodgeReduction.HCGapL4.ProductCycleFactoryProjectiveLineToEllipticCurve
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.ProductCohomologyProjectiveLineEllipticCurve
open HodgeReduction.HCGapL4.ProductCycleFactoryProjectiveLineToEllipticCurve
open HodgeReduction

#print axioms VarietyCohomologyData_projectiveLineTimesEllipticCurve
#print axioms projectiveLineTimesEllipticCurveCycleClassFamily
#print axioms AlgebraicClassesData_projectiveLineTimesEllipticCurve
#print axioms cycleAction_H0_projectiveLine_to_H2_ellipticCurve
#print axioms internalCycleActionData_SHSM_WithProductCycle_projectiveLine_to_ellipticCurve
#print axioms SHSM2_point_to_ellipticCurve_via_two_nontrivial_cross_variety_factories
#print axioms VarietyHCAt_ellipticCurve_codim1_via_two_nontrivial_cross_variety_factories
#print axioms R228_does_not_close_mtCorrespondencePackage
#print axioms R228_does_not_implement_true_chow_composition
#print axioms R228_does_not_prove_cycles_induce_actions
#print axioms R228_does_not_implement_true_projectiveLine_times_ellipticCurve
#print axioms R228_only_cross_variety_factory_SHSM2_chain
#print axioms hodgeConjectureReal_canonical
