import HodgeReduction.HCGapL4.E7ShimuraDatumToySkeleton
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.E7ShimuraDatumToySkeleton
open HodgeReduction

#print axioms E7ShimuraDatumToySkeleton_V56Weight3
#print axioms E7ShimuraDatumToySkeleton_V56Weight3_weight_compatibility
#print axioms E7ShimuraToy_WithShimuraDatumSkeleton
#print axioms VarietyHCAt_E7ShimuraToyWithShimuraDatumSkeleton_codim1_via_productCycleFactory
#print axioms R234_does_not_close_canonicalE7ShimuraTor
#print axioms R234_does_not_implement_real_shimura_datum
#print axioms R234_does_not_implement_real_mumford_tate
#print axioms R234_does_not_implement_real_deligne_torus
#print axioms R234_does_not_implement_hermitian_symmetric_domain
#print axioms R234_does_not_implement_reflex_field
#print axioms R234_does_not_identify_toy_with_real_E7Shimura
#print axioms hodgeConjectureReal_canonical
