import HodgeReduction.HCGapL4.CMAbelianToyChainToE7ShimuraToy
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.CMAbelianToyChainToE7ShimuraToy
open HodgeReduction

#print axioms SHSM2_point_to_E7ShimuraToy_via_CMAbelianToy_productCycle_chain
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_CMAbelianToy_productCycle_chain
#print axioms E7ShimuraToy_MTCorrespondencePackageViaCMAbelianToyChainSkeleton
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_CMAbelianToy_chainSkeleton
#print axioms R238_does_not_close_canonicalE7ShimuraTor
#print axioms R238_does_not_implement_real_motivic_factorization
#print axioms R238_does_not_implement_true_chow_composition
#print axioms R238_does_not_prove_cycles_induce_actions
#print axioms R238_does_not_prove_deligne_1982
#print axioms R238_does_not_identify_toy_with_real_E7Shimura
#print axioms hodgeConjectureReal_canonical
