import HodgeReduction.HCGapL4.E7ShimuraToyReflexFieldSkeleton
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.E7ShimuraToyReflexFieldSkeleton
open HodgeReduction

#print axioms ReflexFieldToySkeleton_Q
#print axioms E7ShimuraToy_WithReflexFieldSkeleton
#print axioms VarietyHCAt_E7ShimuraToyWithReflexFieldSkeleton_codim1_via_v3_CMChain
#print axioms R241_does_not_close_canonicalE7ShimuraTor
#print axioms R241_does_not_implement_real_reflex_field
#print axioms R241_does_not_implement_canonical_model
#print axioms R241_does_not_implement_shimura_reciprocity
#print axioms R241_does_not_implement_galois_action
#print axioms R241_does_not_identify_toy_with_real_E7Shimura
#print axioms hodgeConjectureReal_canonical
