import HodgeReduction.HCGapL4.E7ShimuraTorFieldReplacementPlan
import HodgeReduction.HCGapL4.E7ShimuraTorCohomologyReplacement
import HodgeReduction.HCGapL4.E7ShimuraTorAlgClassesReplacement
import HodgeReduction.HCGapL4.E7ShimuraTorMTCorrespondenceReplacement
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.E7ShimuraTorFieldReplacementPlan
open HodgeReduction.HCGapL4.E7ShimuraTorCohomologyReplacement
open HodgeReduction.HCGapL4.E7ShimuraTorAlgClassesReplacement
open HodgeReduction.HCGapL4.E7ShimuraTorMTCorrespondenceReplacement
open HodgeReduction

-- R244
#print axioms E7ShimuraTorActiveFieldReplacementPlanToySkeleton_current
#print axioms L1_G_Replace_cohomologyOfUnderlying
#print axioms L2_G_Replace_algClassesOfUnderlying
#print axioms L4_G_Replace_mtCorrespondencePackage
#print axioms E7ShimuraTor_active_replacement_targets_are_three

-- R245
#print axioms CohomologyOfUnderlyingReplacementToyPlan_E7ShimuraToy
#print axioms Target_RealE7Shimura_cohomologyOfUnderlying_replaces_toyVCD
#print axioms L1_G_CohomologyReplacement_To_E7ShimuraTorToyContainer

-- R246
#print axioms AlgClassesOfUnderlyingReplacementToyPlan_E7ShimuraToy
#print axioms Target_RealE7Shimura_ChowGroup
#print axioms Target_RealE7Shimura_CycleClassMap
#print axioms Target_RealE7Shimura_algClasses_eq_cycleClassImage
#print axioms L4_G_AlgClassesReplacement_From_CycleClassFamily_To_RealChow
#print axioms L4_G_AlgClassesReplacement_To_E7ShimuraTorToyContainer

-- R247
#print axioms MTCorrespondencePackageReplacementToyPlan_CMChain
#print axioms Target_Real_CMAbelianVariety_Source
#print axioms Target_Deligne1982_HC_For_CMAbelianVariety
#print axioms Target_Real_E7Shimura_MTCorrespondencePackage
#print axioms Target_Real_MotivicFactorization_To_E7Shimura
#print axioms MTCorrespondencePackageReplacementToyPlan_has_kernel_pure_toy_transfer

-- Headline guard
#print axioms hodgeConjectureReal_canonical
