import HodgeReduction.HCGapL4.CycleClassMapReplacement
import HodgeReduction.HCGapL4.E7ShimuraToyCycleClassMapReplacement
import HodgeReduction.HCGapL4.E7ShimuraTorAlgClassesReplacementViaCycleClassMap
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.CycleClassMapReplacement
open HodgeReduction.HCGapL4.E7ShimuraToyCycleClassMapReplacement
open HodgeReduction.HCGapL4.E7ShimuraTorAlgClassesReplacementViaCycleClassMap
open HodgeReduction

-- R248
#print axioms AlgebraicClassesData.ofCycleClassMapReplacement
#print axioms ofCycleClassMapReplacement_algClasses_eq_range
#print axioms VarietyHCAt_of_cycleClassMapReplacement_surjective_on_hodgeClasses

-- R249
#print axioms CycleClassMapReplacementData_E7ShimuraToy
#print axioms AlgebraicClassesData_E7ShimuraToy_fromCycleClassMap
#print axioms E7ShimuraToy_algClasses_agree_fromCycleClassMap_codim0
#print axioms E7ShimuraToy_algClasses_agree_fromCycleClassMap_codim1
#print axioms E7ShimuraToy_algClasses_agree_fromCycleClassMap_all_codims
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_cycleClassMapReplacement
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_cycleClassMapReplacement_existingACD

-- R250
#print axioms AlgClassesOfUnderlyingCycleClassMapReplacementPlan_E7ShimuraToy
#print axioms AlgClassesOfUnderlyingCycleClassMapReplacementPlan_E7ShimuraToy_HC_codim1
#print axioms Target_RealE7Shimura_algClassesOfUnderlying_fromCycleClassMap

-- Headline guard
#print axioms hodgeConjectureReal_canonical
