import HodgeReduction.HCGapL4.AbstractHodgeSource
import HodgeReduction.HCGapL4.AbstractHCDataPackage
import HodgeReduction.HCGapL4.AbstractHCDataWithMTTransfer
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R257
#print axioms AbstractHodgeSource.ofVCD
#print axioms AbstractHodgeSource_E7ShimuraToy
#print axioms L1_G_AbstractHodgeSource_To_CohomologyReplacementNextTarget

-- R258
#print axioms AbstractHCDataPackage.ofCycleClassMap
#print axioms AbstractHCDataPackage.VarietyHCAt_of_hodgeClasses_le_cycleClassRange
#print axioms AbstractHCDataPackage_E7ShimuraToy
#print axioms AbstractHCDataPackage_E7ShimuraToy_HC_codim1
#print axioms L4_G_AbstractHCDataPackage_To_algClassesOfUnderlying
#print axioms L4_G_AbstractHCDataPackage_MissingRealChowGroup
#print axioms L4_G_AbstractHCDataPackage_MissingRealCycleClassMap
#print axioms L4_G_AbstractHCDataPackage_To_canonicalE7ShimuraTor

-- R259
#print axioms AbstractHCDataWithMTTransfer.targetHCAt
#print axioms SHSM2_ellipticCurve_to_E7ShimuraToy_fromCycleClassMap_codim1_to_codim1
#print axioms AbstractHCDataWithMTTransfer_E7ShimuraToy
#print axioms AbstractHCDataWithMTTransfer_E7ShimuraToy_HC_codim1
#print axioms L4_G_AbstractHCDataWithMTTransfer_To_cohomologyOfUnderlying
#print axioms L4_G_AbstractHCDataWithMTTransfer_To_algClassesOfUnderlying
#print axioms L4_G_AbstractHCDataWithMTTransfer_To_mtCorrespondencePackage
#print axioms L4_G_AbstractHCDataWithMTTransfer_To_canonicalE7ShimuraTor

-- Headline guard
#print axioms hodgeConjectureReal_canonical
