import HodgeReduction.HCGapL4.GaussianRationalNumberFieldConstruction
import HodgeReduction.HCGapL4.GaussianRationalConjugation
import HodgeReduction.HCGapL4.ImaginaryQuadraticFieldRealizationInterface
import HodgeReduction.HCGapL4.CMFieldRealizationInterface
import HodgeReduction.HCGapL4.EllipticCurveEnd0ActionTarget
import HodgeReduction.HCGapL4.CMFieldChainIntegration
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R273
#print axioms GaussianRationalNumberFieldConstructionSkeleton_current
#print axioms CMFieldInterfaceWithNumberFieldConstructionSkeleton_Gaussian
#print axioms BlockingLemma_GaussianRationalFieldCandidate_finiteDimensional
#print axioms Target_R273_FiniteDimensional
#print axioms Target_R273_NumberField
#print axioms Target_R273_finrank_eq_two
#print axioms L4_G_GaussianNumberFieldConstruction_To_CMFieldInterface
#print axioms L4_G_GaussianNumberFieldConstruction_MissingBasisOneI
#print axioms L4_G_GaussianNumberFieldConstruction_MissingFiniteDimensionalProof
#print axioms L4_G_GaussianNumberFieldConstruction_MissingFinrankTwo

-- R274
#print axioms GaussianRationalConjugationSkeleton_current
#print axioms CMFieldInterfaceWithConjugationTargetSkeleton_Gaussian
#print axioms Target_R274_GaussianRationalFieldCandidate_conj
#print axioms Target_R274_GaussianRationalFieldCandidate_conj_involutive
#print axioms Target_R274_GaussianRationalFieldCandidate_conj_i_eq_neg_i
#print axioms L4_G_GaussianConjugation_To_ImaginaryQuadraticInterface
#print axioms L4_G_GaussianConjugation_MissingFractionRingLift
#print axioms L4_G_GaussianConjugation_MissingConjIEqualsNegI

-- R275
#print axioms ImaginaryQuadraticFieldInterfaceRealizationSkeleton_Gaussian
#print axioms ImaginaryQuadraticFieldRealizationEvidenceSkeleton_Gaussian
#print axioms CMFieldInterfaceWithImaginaryQuadraticRealizationSkeleton_Gaussian
#print axioms L4_G_ImaginaryQuadraticInterface_To_CMField
#print axioms L4_G_ImaginaryQuadraticInterface_MissingNumberField
#print axioms L4_G_ImaginaryQuadraticInterface_MissingComplexEmbedding
#print axioms L4_G_ImaginaryQuadraticInterface_MissingTotallyImaginaryProof

-- R276
#print axioms CMFieldRealizationInterfaceSkeleton_Gaussian
#print axioms EllipticCurveCMInterfaceWithCMFieldRealizationSkeleton_instance
#print axioms AbstractCMAbelianHCSource_from_EllipticCurveCMFieldRealization
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_EllipticCurveCMFieldRealization
#print axioms L4_G_CMFieldRealization_To_R261_hasCMFieldToy
#print axioms L4_G_CMFieldRealization_To_Deligne1982
#print axioms L4_G_CMFieldRealization_MissingEnd0Action
#print axioms L4_G_CMFieldRealization_MissingActualCMEC

-- R277
#print axioms EllipticCurveEnd0ActionTargetSkeleton_Gaussian
#print axioms Target_R261_hasCMFieldToy_from_CMFieldRealization
#print axioms Target_R261_rankConditionToy_from_End0Action
#print axioms Target_R261_actsOnCohomologyToy_from_End0Action
#print axioms L4_G_End0ActionTarget_To_RealEnd
#print axioms L4_G_End0ActionTarget_To_RealEnd0
#print axioms L4_G_End0ActionTarget_To_GaussianCMEmbedding

-- R278
#print axioms EllipticCurveCMFieldChainIntegrationSkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_CMFieldChainIntegration
#print axioms Target_Prove_NumberField_GaussianRationalFieldCandidate
#print axioms Target_Construct_GaussianRationalConjugation
#print axioms Target_Prove_ImaginaryQuadratic_Gaussian
#print axioms Target_Construct_End0_EllipticCurve
#print axioms Target_Construct_CMEmbedding_Gaussian_To_End0
#print axioms Target_Construct_End0_Action_On_H1_H2
#print axioms R278_NextPriority_NumberFieldFirst
#print axioms R278_NextPriority_ConjugationSecond
#print axioms R278_NextPriority_End0Third
#print axioms L4_G_CMFieldChainIntegration_To_R261_hasCMFieldToy
#print axioms L4_G_CMFieldChainIntegration_To_R261_rankConditionToy
#print axioms L4_G_CMFieldChainIntegration_To_R261_actsOnCohomologyToy
#print axioms L4_G_CMFieldChainIntegration_To_Deligne1982

-- Headline guard
#print axioms hodgeConjectureReal_canonical
