import HodgeReduction.HCGapL4.GaussianPolynomialIrreducible
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R284
#print axioms GaussianPolynomialOverQ_no_root
#print axioms GaussianPolynomialOverQ_roots_eq_zero
#print axioms GaussianPolynomialOverQ_irreducible
#print axioms BlockingLemma_R281_X_sq_add_one_irreducible_over_Q_closed
#print axioms GaussianPolynomialOverQ_irreducible_Fact
#print axioms GaussianAdjoinRootCandidate_has_Field
#print axioms L4_G_GaussianPolynomialIrreducible_To_AdjoinRootField
#print axioms L4_G_GaussianPolynomialIrreducible_To_GaussianRationalAlgEquiv
#print axioms L4_G_GaussianPolynomialIrreducible_To_NumberField

-- Headline guard
#print axioms hodgeConjectureReal_canonical
