import HodgeReduction.HCGapL4.CanonicalFieldwiseCohomologyComparison
import HodgeReduction.HCGapL4.CanonicalFieldwiseAlgClassesComparison
import HodgeReduction.HCGapL4.CanonicalFieldwiseMTPackageComparison
import HodgeReduction.HCGapL4.HCFrontierAfterFieldwiseComparisonSkeleton
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R367 cohomology comparison
#print axioms HCRelevantCohomologyComparisonAtCodim_reflexive_E7ShimuraToy

-- R368 algClasses comparison
#print axioms HCRelevantAlgClassesComparisonAtCodim_reflexive_E7ShimuraToy
#print axioms ReplacementAlgClassesComparisonUsesChowBridge_current

-- R369 mtPackage comparison
#print axioms HCRelevantMTPackageComparison_internalCurrent

-- R370 frontier audit
#print axioms HCFrontierAfterFieldwiseComparisonSkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_HCFrontierAfterFieldwiseComparisonSkeleton

-- Final-goal markers (axiom-free)
#print axioms R370_HC_FinalGoal_KernelOnly
#print axioms R370_canonicalE7ShimuraTor_StillOnlyProjectAxiom
#print axioms R370_FieldwiseComparisonSkeleton_Available
#print axioms R370_NextTarget_AuthorizedRefactorPreparation
#print axioms R370_NextTarget_RealBridgeInstantiation
#print axioms R370_HonestPosition_Scaffolding_Complete_External_Decisions_Pending

-- Honest markers from R367/R368
#print axioms R367_CohomologyComparison_FieldEquality_NotClaimed
#print axioms R368_AlgClassesComparison_FieldEquality_NotClaimed

-- Headline guard
#print axioms hodgeConjectureReal_canonical
