import HodgeReduction.HCGapL4.ParametricCanonicalReplacementAssumptions
import HodgeReduction.HCGapL4.ParametricCanonicalHCTransfer
import HodgeReduction.HCGapL4.ShadowCanonicalHCTheorem
import HodgeReduction.HCGapL4.AuthorizedRefactorPreparationMap
import HodgeReduction.HCGapL4.MathlibRealGeometryRevisitGate
import HodgeReduction.HCGapL4.HCFrontierAfterParametricRefactorPreparation
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R371 parametric replacement assumptions
#print axioms ParametricCanonicalReplacementAssumptionsWeak_internalReflexive
#print axioms ParametricCanonicalReplacementAssumptions_internal_reflexive_nonempty

-- R372 parametric HC transfer
#print axioms replacement_internal_codim1_HC

-- R373 shadow canonical theorem
#print axioms shadow_hodgeConjectureReal_canonical_codim1
#print axioms shadow_hodgeConjectureReal_canonical_codim1_applies_internal

-- R374 authorized refactor plan
#print axioms AuthorizedCanonicalRefactorPlan_current
#print axioms AuthorizedRefactorRiskLedger_current

-- R375 Mathlib revisit gate
#print axioms MathlibRealGeometryRevisitGate_current

-- R376 frontier audit
#print axioms HCFrontierAfterParametricRefactorPreparation_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_HCFrontierAfterParametricRefactorPreparation

-- Final-goal markers (axiom-free)
#print axioms R376_HC_FinalGoal_KernelOnly
#print axioms R376_ParametricRefactorPreparation_Complete
#print axioms R376_canonicalE7ShimuraTor_StillOnlyProjectAxiom
#print axioms R376_NextAction_AuthorizeRefactor_Or_WaitForRealGeometry
#print axioms R376_HonestConclusion_FurtherScaffoldingWouldBe_InfrastructureDrift

-- Headline guard
#print axioms hodgeConjectureReal_canonical
