import HodgeReduction.HCGapL4.CanonicalConeExtractionAudit
import HodgeReduction.HCGapL4.ParametricCanonicalE7ShimuraTor
import HodgeReduction.HCGapL4.ParametricCanonicalHCAtCodim1
import HodgeReduction.HCGapL4.ParametricHodgeConjectureReal
import HodgeReduction.HCGapL4.ParametricHCExplicitAssumptions
import HodgeReduction.HCGapL4.CanonicalRootCompatibilityWrapper
import HodgeReduction.HCGapL4.AuthorizedRefactorDryRunReport
import HodgeReduction.HCGapL4.HCFrontierAfterAuthorizedRefactorDryRun
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R378 parametric tor
#print axioms ParametricCanonicalE7ShimuraTor_from_canonical

-- R379 parametric HC theorem (KEY: cone should NOT include canonicalE7ShimuraTor)
#print axioms hodgeConjectureReal_from_ParametricCanonicalE7ShimuraTor
#print axioms VarietyHCAt_of_ParametricCanonicalE7ShimuraTor_codim1
#print axioms hodgeConjectureReal_canonical_via_parametric

-- R380 global theorem route
#print axioms hodgeConjectureReal_from_ParametricTor
#print axioms hodgeConjectureReal_canonical_via_parametric_old
#print axioms hodgeConjectureReal_replacement_internal_codim1

-- R381 explicit assumptions
#print axioms ParametricHCExplicitAssumptions_internalCurrent
#print axioms ParametricHCExplicitAssumptions_nonempty

-- R382 compatibility wrapper
#print axioms hodgeConjectureReal_canonical_compat_old_route

-- R383 dry-run
#print axioms AuthorizedRefactorDryRunReport_current

-- R384 frontier
#print axioms HCFrontierAfterAuthorizedRefactorDryRun_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_HCFrontierAfterAuthorizedRefactorDryRun

-- Final-goal markers
#print axioms R384_HC_FinalGoal_KernelOnly
#print axioms R384_canonicalE7ShimuraTor_Status
#print axioms R384_NextTarget_FirstExplicitBridgeObligation
#print axioms R384_HonestPosition_Refactor_Complete_OneObligationLeft

-- Headline guard (must remain unchanged)
#print axioms hodgeConjectureReal_canonical
