/-
Generated by paper-ledger/audit_master.py. Do not edit by hand.
Canonical master SHA-256: 43d238de736e4d9ad517f00da0014ac3c1a76349bdc1ae03f95c85cca2ac8eef
-/
import HodgeReduction.Canonical.FullHodgeGoal

namespace HodgeReduction.Canonical
namespace PaperLedgerGenerated

def canonicalMasterPath : String := "contributions/hodge-conjecture-master-proof.tex"
def canonicalMasterSha256 : String := "43d238de736e4d9ad517f00da0014ac3c1a76349bdc1ae03f95c85cca2ac8eef"
def ledgerSha256 : String := "5592750b7e46d042010c47411b11bd2460e57d9aaa23961559b1fc8da215aa87"

def unclosedClaimIds : List String := []
def unclosedCitationOccurrenceIds : List String := []
def unclosedProseCandidateIds : List String := []

structure ClosureSnapshot where
  environmentCount : Nat
  declaredOpenEnvironmentCount : Nat
  registeredOpenEnvironmentCount : Nat
  unboundNonopenEnvironmentCount : Nat
  kernelClosedEnvironmentCount : Nat
  referenceBackedEnvironmentCount : Nat
  supportedEnvironmentCount : Nat
  citationKeyCount : Nat
  citationOccurrenceCount : Nat
  kernelClosedCitationOccurrenceCount : Nat
  referenceBackedCitationOccurrenceCount : Nat
  supportedCitationOccurrenceCount : Nat
  proseCandidateCount : Nat
  kernelClosedProseCandidateCount : Nat
  referenceBackedProseCandidateCount : Nat
  supportedProseCandidateCount : Nat
  nonMasterTexSourceCount : Nat
  noncanonicalImportCount : Nat
  structuralFailureCount : Nat
  manualCloseFieldsPresent : Bool
  paperEvidenceClosed : Bool
  fullHodgeProved : Bool
  deriving Repr, DecidableEq, Inhabited

def paperEvidenceClosed : Bool :=
  unclosedClaimIds.isEmpty &&
    unclosedCitationOccurrenceIds.isEmpty &&
      unclosedProseCandidateIds.isEmpty &&
        0 == 0 &&
          0 == 0

/-- Backwards-compatible short name: this is evidence closure of the paper,
not a proof of the Hodge Conjecture. -/
abbrev paperClosed : Bool := paperEvidenceClosed

def fullHodgeProved : Bool :=
  currentFullHodgeClosureStatusSnapshot.fullHcClosureClaim

def currentPaperLedgerClosureSnapshot : ClosureSnapshot where
  environmentCount := 13
  declaredOpenEnvironmentCount := 1
  registeredOpenEnvironmentCount := 1
  unboundNonopenEnvironmentCount := 3
  kernelClosedEnvironmentCount := 9
  referenceBackedEnvironmentCount := 3
  supportedEnvironmentCount := 13
  citationKeyCount := 4
  citationOccurrenceCount := 4
  kernelClosedCitationOccurrenceCount := 0
  referenceBackedCitationOccurrenceCount := 4
  supportedCitationOccurrenceCount := 4
  proseCandidateCount := 3
  kernelClosedProseCandidateCount := 2
  referenceBackedProseCandidateCount := 1
  supportedProseCandidateCount := 3
  nonMasterTexSourceCount := 0
  noncanonicalImportCount := 0
  structuralFailureCount := 0
  manualCloseFieldsPresent := false
  paperEvidenceClosed := paperEvidenceClosed
  fullHodgeProved := fullHodgeProved

set_option maxRecDepth 100000 in
theorem currentPaperLedgerClosureSnapshot_eq_generated :
    currentPaperLedgerClosureSnapshot =
      ({ environmentCount := 13
         declaredOpenEnvironmentCount := 1
         registeredOpenEnvironmentCount := 1
         unboundNonopenEnvironmentCount := 3
         kernelClosedEnvironmentCount := 9
         referenceBackedEnvironmentCount := 3
         supportedEnvironmentCount := 13
         citationKeyCount := 4
         citationOccurrenceCount := 4
         kernelClosedCitationOccurrenceCount := 0
         referenceBackedCitationOccurrenceCount := 4
         supportedCitationOccurrenceCount := 4
         proseCandidateCount := 3
         kernelClosedProseCandidateCount := 2
         referenceBackedProseCandidateCount := 1
         supportedProseCandidateCount := 3
         nonMasterTexSourceCount := 0
         noncanonicalImportCount := 0
         structuralFailureCount := 0
         manualCloseFieldsPresent := false
         paperEvidenceClosed := true
         fullHodgeProved := false } : ClosureSnapshot) := by
  decide

set_option maxRecDepth 100000 in
theorem paperEvidenceClosed_eq_true : paperEvidenceClosed = true := by
  decide

theorem fullHodgeProved_eq_false : fullHodgeProved = false := by
  decide

end PaperLedgerGenerated
end HodgeReduction.Canonical
