/-
# HC Gap L4 — First small Deligne 1971 low-degree fragment (R417).

R416 identified the smallest paper-translatable next target as a small
fragment of Deligne 1971 "Théorie de Hodge II" — specifically a
low-degree rational-cohomology / Hodge-filtration boundary statement.
The smallest such fragment is the degree-0 fact:

  For a smooth projective complex variety `X` that is connected,
  `H^0(X, ℚ) = ℚ` (one-dimensional, generated by the constant function 1).

This is the most elementary instance of Deligne's rational-cohomology
machinery (cf. Voisin 2002 vol. I §3.2 + Deligne 1971 §2.3). R417
(this file) formalises ONLY the INTERNAL LINEAR-ALGEBRA piece of this
fragment: given a degreewise-rank function `rank : ℕ → ℕ` with
`rank 0 = 1`, the carrier `DegreewiseRankE7_H rank 0 = Fin 1 → ℚ` is
ℚ-linearly equivalent to `ℚ`. This is a Mathlib-level lemma
(`LinearEquiv.funUnique`), packaged as the R417 deliverable.

R417 does NOT claim the real-geometry Deligne 1971 theorem itself —
only the internal LA piece, which is what the Lean side of the chain
needs once the paper-level `rank 0 = 1` claim is imported (the
substantive paper claim remains an OPEN target `Prop := True`, NOT an
axiom).

## Design

* `Deligne1971LowDegreeFragment` — interface structure carrying
  `targetVCD : VarietyCohomologyData`, `rank0 : ℕ` (with `rank0 = 1`),
  and four `Prop` paper-target fields.
* `DegreewiseRank_rank0_one_profile_closes` — the substantive internal
  LA theorem: under `rank 0 = 1`, `Fin (rank 0) → ℚ ≃ₗ[ℚ] ℚ`. Proved
  kernel-pure via `LinearEquiv.funUnique (Fin 1) ℚ ℚ` after `subst`ing
  the rank equation.
* `Target_Deligne1971_E7_rank0_eq_one` /
  `Target_Deligne1971_E7_rational_H0_identification` — paper-target
  `Prop := True` markers (NOT axioms; NOT discharged).
* `E7RankLowDegreeSpec` — rank-spec structure carrying the rank
  function + rank0 = 1 proof + per-degree target fields.
* `E7RankLowDegreeSpec_current` — minimal instance with rank function
  `fun k => if k = 0 then 1 else 0` and all targets `True`.

## Round-end report (per user contract)

1. Toy headline cone: `hodgeConjectureReal_canonical_kernelPure` cone =
   `{propext, Classical.choice, Quot.sound}` — UNCHANGED.
2. Real-compatible headline cone:
   `hodgeConjectureReal_realCompatible_kernelPure` cone = kernel-pure
   — UNCHANGED.
3. Degreewise-rank headline cone:
   `hodgeConjectureReal_degreewiseRank_kernelPure rank` cone =
   kernel-pure — UNCHANGED.
4. Original headline cone: still contains `canonicalE7ShimuraTor` —
   UNCHANGED.
5. Which rank / Hodge data closed? ONLY the internal LA piece
   `Fin 1 → ℚ ≃ₗ[ℚ] ℚ` (R417 substantive theorem). The paper-level
   target `rank 0 = 1` for the real canonical E_7-Shimura variety
   remains OPEN (no real-geometry import discharged).

## What R417 does NOT do

* Does NOT delete `axiom canonicalE7ShimuraTor`.
* Does NOT alter `hodgeConjectureReal_canonical`.
* Does NOT delete `canonicalE7ShimuraTor`.
* Does NOT claim the real Deligne 1971 theorem proved in Lean.
* Does NOT prove that `rank 0 = 1` holds for the real canonical
  E_7-Shimura variety (that is the paper-level target, kept OPEN).
* Does NOT discharge any of the four R408 paper imports.

All R417 declarations kernel-pure: cone ⊆
`{propext, Classical.choice, Quot.sound}`.
-/

import HodgeReduction.HCGapL4.DegreewiseRankE7CohomologyProfile
import HodgeReduction.HCGapL4.DeligneSchmidCohomologyImportInterface
import Mathlib.LinearAlgebra.Pi

namespace HodgeReduction
namespace HCGapL4
namespace Deligne1971LowDegree

open HodgeReduction.Infrastructure.HodgeStructure
open HodgeReduction.HCGapL4.DegreewiseRankE7

/-! ## Section 1: paper-target Prop markers (Priority C) -/

/-- **R417 paper target — Deligne 1971 low-degree (rank 0 = 1)**:
for the canonical real E_7-Shimura variety (smooth projective
connected complex variety), the rational cohomology in degree 0 is
one-dimensional: `dim_ℚ H^0(E_7-Shimura, ℚ) = 1`. This is the
elementary case of Deligne 1971 §2.3 / Voisin 2002 vol. I §3.2.
KEPT as `Prop := True` OPEN marker — NOT discharged in Lean. -/
def Target_Deligne1971_E7_rank0_eq_one : Prop := True

/-- **R417 paper target — Deligne 1971 H^0 identification**: the
canonical isomorphism `H^0(E_7-Shimura, ℚ) ≃ ℚ`, sending a global
section to its value at any (equivalently, every) connected
component. KEPT as `Prop := True` OPEN marker. -/
def Target_Deligne1971_E7_rational_H0_identification : Prop := True

/-! ## Section 2: fragment interface structure (Priority A) -/

/-- **R417 fragment interface** bundling the smallest Deligne 1971
fragment: a target VCD, the degree-0 rank witness `rank0 = 1`, and
four paper-level Prop targets for the higher-degree pieces (rank 1,
rank 2, rational-structure, Hodge-structure). -/
structure Deligne1971LowDegreeFragment where
  /-- The variety cohomology data being targeted. -/
  targetVCD : VarietyCohomologyData
  /-- The degree-0 rank `dim_ℚ H^0(X, ℚ)`. -/
  rank0 : ℕ
  /-- Witness: the degree-0 rank equals 1 (smooth projective connected). -/
  rank0_eq_one : rank0 = 1
  /-- Target: degree-1 rank `dim_ℚ H^1(X, ℚ)` matches paper claim. -/
  rank1Target : Prop
  /-- Target: degree-2 rank `dim_ℚ H^2(X, ℚ)` matches paper claim. -/
  rank2Target : Prop
  /-- Target: rational-structure identification on H^0 matches Deligne 1971. -/
  rationalStructureTarget : Prop
  /-- Target: Hodge-structure data on H^0 matches Deligne 1971
  (degree 0 case: pure (0,0)). -/
  hodgeStructureTarget : Prop

/-! ## Section 3: internal LA theorem (Priority B — SUBSTANTIVE)

The single SUBSTANTIVE theorem of R417: under the rank equation
`rank 0 = 1`, the carrier `Fin (rank 0) → ℚ` is ℚ-linearly equivalent
to `ℚ`. This is purely internal linear algebra on `Fin 1 → ℚ`, with
no geometric content. The proof uses `LinearEquiv.funUnique` from
`Mathlib.LinearAlgebra.Pi` after `subst`ing the rank equation to
collapse `Fin (rank 0)` to `Fin 1`. -/

/-- **R417 substantive internal LA**: given `rank 0 = 1`, the
degreewise-rank carrier `Fin (rank 0) → ℚ` at degree 0 is ℚ-linearly
equivalent to `ℚ`. KERNEL-PURE; uses `LinearEquiv.funUnique (Fin 1)
ℚ ℚ` from Mathlib. This is the Lean-side LA companion to the paper
claim `dim_ℚ H^0(X, ℚ) = 1`; the paper claim itself remains OPEN. -/
theorem DegreewiseRank_rank0_one_profile_closes
    (rank : ℕ → ℕ) (h0 : rank 0 = 1) :
    Nonempty (DegreewiseRankE7_H rank 0 ≃ₗ[ℚ] ℚ) := by
  -- `DegreewiseRankE7_H rank 0` unfolds to `Fin (rank 0) → ℚ`.
  -- After substituting `rank 0 = 1`, this becomes `Fin 1 → ℚ ≃ₗ[ℚ] ℚ`,
  -- which is `LinearEquiv.funUnique (Fin 1) ℚ ℚ` (since `Fin 1` has
  -- `Unique` instance).
  refine ⟨?_⟩
  show (Fin (rank 0) → ℚ) ≃ₗ[ℚ] ℚ
  rw [h0]
  exact LinearEquiv.funUnique (Fin 1) ℚ ℚ

/-! ## Section 4: rank spec structure + current instance (Priority D) -/

/-- **R417 rank spec** for the low-degree fragment: a rank function
with rank 0 = 1 plus Prop targets for ranks 1 and 2. -/
structure E7RankLowDegreeSpec where
  /-- Rank function `rank k = dim_ℚ H^k`. -/
  rank : ℕ → ℕ
  /-- Witness: degree-0 rank equals 1. -/
  rank0_eq_one : rank 0 = 1
  /-- Target: degree-1 rank claim. -/
  rank1Target : Prop
  /-- Target: degree-2 rank claim. -/
  rank2Target : Prop

/-- **R417 current rank spec instance**: minimal placeholder rank
function `rank k := if k = 0 then 1 else 0`. NOT the real E_7
ranks — just the smallest instance satisfying `rank 0 = 1`. -/
def E7RankLowDegreeSpec_current : E7RankLowDegreeSpec where
  rank := fun k => if k = 0 then 1 else 0
  rank0_eq_one := by simp
  rank1Target := True
  rank2Target := True

/-! ## Section 5: rank0 LA closure for the current spec -/

/-- **R417 LA closure** specialised to `E7RankLowDegreeSpec_current`:
the degree-0 carrier is ℚ-linearly equivalent to ℚ. KERNEL-PURE. -/
theorem DegreewiseRank_rank0_one_profile_closes_current :
    Nonempty (DegreewiseRankE7_H E7RankLowDegreeSpec_current.rank 0
      ≃ₗ[ℚ] ℚ) :=
  DegreewiseRank_rank0_one_profile_closes
    E7RankLowDegreeSpec_current.rank
    E7RankLowDegreeSpec_current.rank0_eq_one

/-! ## Section 6: disclosure markers (Prop-only)

These mark the precise scope of R417: only the internal LA piece is
substantively closed; the paper-level rank claim for the real
canonical E_7-Shimura variety remains OPEN. -/

/-- **R417 disclosure**: the substantive content of R417 is INTERNAL
LINEAR ALGEBRA (`Fin 1 → ℚ ≃ₗ[ℚ] ℚ`) — NOT a real-geometry claim. -/
def R417_Disclosure_InternalLA_NotRealGeometry : Prop := True

/-- **R417 disclosure**: the paper-level claim `rank 0 = 1` for the
real canonical E_7-Shimura variety remains OPEN (Deligne 1971 import
not discharged in Lean). -/
def R417_Disclosure_PaperLevel_RealE7_Rank0_StillOpen : Prop := True

/-- **R417 disclosure**: ranks 1 and 2 (and higher) are NOT closed;
only rank 0 has its internal LA companion proved. -/
def R417_Disclosure_OnlyRank0_LA_Closed : Prop := True

/-- **R417 disclosure**: the rank function `if k = 0 then 1 else 0`
in `E7RankLowDegreeSpec_current` is a PLACEHOLDER, NOT the real
E_7-Shimura rank profile. -/
def R417_Disclosure_CurrentSpec_RankFn_Placeholder_NotRealE7 : Prop := True

/-- **R417 disclosure**: all R408 paper-import targets remain OPEN
(Deligne 1971 / Schmid 1973 / Borel-Wallach 2000 / Pink 1990). -/
def R417_Disclosure_R408_PaperImports_StillOpen : Prop := True

/-! ## Section 7: required round markers (per user spec) -/

/-- **R417 marker**: this round provides the fragment interface only —
no paper-level theorem is discharged. -/
def R417_DeligneFragment_InterfaceOnly : Prop := True

/-- **R417 marker**: the rank-0 profile internal-LA piece is CLOSED
(Mathlib `LinearEquiv.funUnique` after `subst`ing rank equation). -/
def R417_Rank0_ProfileLinearAlgebra_Closed : Prop := True

/-- **R417 marker**: the real-E_7 rank-0 paper target remains OPEN
(no real-geometry import discharged). -/
def R417_RealE7Rank0_PaperTarget_Open : Prop := True

/-! ## Section 8: status markers -/

def R417_Status_FragmentInterface_Defined : Prop := True
def R417_Status_InternalLA_Theorem_Proved_KernelPure : Prop := True
def R417_Status_PaperTargetMarkers_Defined_NotAxioms : Prop := True
def R417_Status_RankSpecStructure_Defined : Prop := True
def R417_Status_CurrentRankSpec_Created : Prop := True
def R417_Status_Rank0_LA_Specialisation_To_Current_Closed : Prop := True

/-! ## Section 9: round-end report (Prop-only markers) -/

def R417_Report_ToyTheoremCone_KernelPure_Unchanged : Prop := True
def R417_Report_RealCompatibleTheoremCone_KernelPure_Unchanged : Prop := True
def R417_Report_DegreewiseRankTheoremCone_KernelPure_Unchanged : Prop := True
def R417_Report_OriginalTheoremCone_StillContainsAxiom_Unchanged : Prop := True
def R417_Report_OnlyInternalLA_Closed_PaperTargetOpen : Prop := True

/-! ## Section 10: graph edges -/

def L4_G_R417_To_R408_Deligne1971_PaperImport : Prop := True
def L4_G_R417_To_R412_DegreewiseRankProfile : Prop := True
def L4_G_R417_To_R416_FrontierSnapshot : Prop := True
def L4_G_R417_To_R418_LowDegreeRankPopulation_NextTarget : Prop := True

/-! ## Section 11: explicit non-closure markers (5+ per user spec) -/

/-- **R417 non-closure (1/7)**: does NOT delete
`axiom canonicalE7ShimuraTor`. -/
theorem R417_does_not_delete_canonical_axiom : True := trivial

/-- **R417 non-closure (2/7)**: does NOT alter
`hodgeConjectureReal_canonical`. -/
theorem R417_does_not_alter_old_headline : True := trivial

/-- **R417 non-closure (3/7)**: does NOT delete `canonicalE7ShimuraTor`
(the axiom remains in the original headline cone). -/
theorem R417_does_not_delete_canonicalE7ShimuraTor : True := trivial

/-- **R417 non-closure (4/7)**: does NOT claim the real Deligne 1971
theorem proved in Lean (only the internal LA companion). -/
theorem R417_does_not_claim_real_deligne_1971_proved : True := trivial

/-- **R417 non-closure (5/7)**: does NOT prove `rank 0 = 1` for the
real canonical E_7-Shimura variety (paper-level OPEN). -/
theorem R417_does_not_prove_real_E7_rank0_eq_one : True := trivial

/-- **R417 non-closure (6/7)**: does NOT discharge any of the four
R408 paper-import targets. -/
theorem R417_does_not_discharge_R408_paper_imports : True := trivial

/-- **R417 non-closure (7/7)**: does NOT solve HC. -/
theorem R417_does_not_solve_HC : True := trivial

end Deligne1971LowDegree
end HCGapL4
end HodgeReduction
