/-
# HC Gap L4 -- Front C92: Cartan generator line criterion (R656).

R655 identifies the live target with the Cartan scalar-preimage theorem:
every class in `trivialModulePart` must be `j_q (r • h^4)`.

This file makes that target more concrete without adding a new assumption.
The Cartan H8 source is already `span {h^4}`, and Borel stable-range
injectivity makes `j_q(h^4)` non-zero.  Therefore its image is exactly the
one-dimensional line `span {j_q(h^4)}`.  The remaining target is the geometric
containment

  `trivialModulePart <= span {j_q(h^4)}`.

That containment is equivalent to the scalar-preimage theorem, and hence to
the R655 bijectivity/right-inverse target after the source carrier is fixed.
-/

import HodgeReduction.HCGapL4.FrontC91_H8ResidualRightInverseScalarPreimageEquivalence

set_option linter.dupNamespace false

namespace HodgeReduction
namespace HCGapL4
namespace FrontC92_H8ResidualCartanGeneratorLineCriterion

open HodgeReduction.Infrastructure.Cohomology
open HodgeReduction.Infrastructure.Shimura
open HodgeReduction.Infrastructure.Automorphic
open FrontC36_TargetBettiObstruction
open FrontC71_H8ResidualSourceInvariantExactImageContract
open FrontC83_H8ResidualCartanImageScalarPreimage
open FrontC87_H8ResidualInvariantMapSurjectivity
open FrontC91_H8ResidualRightInverseScalarPreimageEquivalence

section CartanGeneratorLine

variable {A B : Type*}
  [CommRing A] [Algebra Rat A] [CohomologyRing A]
  [KaehlerClass A] [CompactDualData A] [CartanCompactDualIso A]
  [AddCommGroup B] [Module Rat B]
  [MatsushimaData A B]

omit [CompactDualData A] [CartanCompactDualIso A] in
/-- The Matsushima image of the compact-dual H8 generator is non-zero. -/
theorem matsushima_h_pow_four_image_ne_zero :
    MatsushimaData.j_q (A := A) (B := B)
        ((KaehlerClass.h : A) ^ 4) ≠ 0 := by
  intro hzero
  have hpre :
      ((KaehlerClass.h : A) ^ 4) = 0 := by
    apply MatsushimaData.j_q_injective (A := A) (B := B)
    simpa using hzero
  exact KaehlerClass.h_pow_4_ne_zero (A := A) hpre

/-- The generator `j_q(h^4)` lies in the Cartan H8 image. -/
theorem matsushima_h_pow_four_mem_cartan_image :
    MatsushimaData.j_q (A := A) (B := B)
        ((KaehlerClass.h : A) ^ 4) ∈
      Submodule.map (MatsushimaData.j_q (A := A) (B := B))
        (CartanCompactDualIso.trivialModuleGK_H8 (A := A)) := by
  refine ⟨((KaehlerClass.h : A) ^ 4), ?_, rfl⟩
  rw [CartanCompactDualIso.trivialModuleGK_H8_eq_compactDual_H8 (A := A)]
  rw [CompactDualData.H8_eq_span_h_pow_4 (A := A)]
  exact Submodule.subset_span (by simp)

/-- The Cartan H8 image is precisely the line generated by `j_q(h^4)`. -/
theorem cartan_image_eq_span_matsushima_h_pow_four :
    Submodule.map (MatsushimaData.j_q (A := A) (B := B))
        (CartanCompactDualIso.trivialModuleGK_H8 (A := A)) =
      Submodule.span Rat
        {MatsushimaData.j_q (A := A) (B := B)
          ((KaehlerClass.h : A) ^ 4)} := by
  ext beta
  constructor
  · intro hbeta
    obtain ⟨alpha, halpha, halpha_beta⟩ := hbeta
    have halpha_H8 : alpha ∈ CompactDualData.H8 (A := A) := by
      rw [← CartanCompactDualIso.trivialModuleGK_H8_eq_compactDual_H8
        (A := A)]
      exact halpha
    rw [CompactDualData.H8_eq_span_h_pow_4 (A := A)] at halpha_H8
    rw [Submodule.mem_span_singleton] at halpha_H8
    obtain ⟨r, hr⟩ := halpha_H8
    rw [← halpha_beta, ← hr, map_smul]
    exact
      Submodule.smul_mem _
        r
        (Submodule.subset_span (by simp))
  · intro hbeta
    rw [Submodule.mem_span_singleton] at hbeta
    obtain ⟨r, hr⟩ := hbeta
    refine ⟨r • ((KaehlerClass.h : A) ^ 4), ?_, ?_⟩
    · rw [CartanCompactDualIso.trivialModuleGK_H8_eq_compactDual_H8 (A := A)]
      rw [CompactDualData.H8_eq_span_h_pow_4 (A := A)]
      exact
        Submodule.smul_mem _
          r
          (Submodule.subset_span (by simp))
    · rw [map_smul]
      exact hr

/-- The Cartan image is non-trivial, with explicit generator `j_q(h^4)`. -/
theorem cartan_image_contains_nonzero_generator :
    ∃ beta : B,
      beta ∈
          Submodule.map (MatsushimaData.j_q (A := A) (B := B))
            (CartanCompactDualIso.trivialModuleGK_H8 (A := A)) ∧
        beta ≠ 0 := by
  exact
    ⟨MatsushimaData.j_q (A := A) (B := B)
        ((KaehlerClass.h : A) ^ 4),
      matsushima_h_pow_four_mem_cartan_image (A := A) (B := B),
      matsushima_h_pow_four_image_ne_zero (A := A) (B := B)⟩

end CartanGeneratorLine

section ScalarPreimageLineCriterion

variable {A B : Type*}
  [CommRing A] [Algebra Rat A] [CohomologyRing A]
  [KaehlerClass A] [CompactDualData A] [CartanCompactDualIso A]
  [AddCommGroup B] [Module Rat B]
  [MatsushimaData A B]
  [MatsushimaSurjectivityData A B]
  [MatsushimaCompactDualData A B]
  [CuspidalCohomologyData B]
  [EisensteinVanishingDeg8 A B]
  [CuspidalGInvariantTrivialModuleDeg8 A B]

omit [CompactDualData A] [CartanCompactDualIso A]
  [MatsushimaSurjectivityData A B] [MatsushimaCompactDualData A B]
  [EisensteinVanishingDeg8 A B] [CuspidalGInvariantTrivialModuleDeg8 A B] in
/-- The scalar-preimage theorem is exactly containment of the target
trivial-module part in the explicit line generated by `j_q(h^4)`. -/
theorem cartan_scalar_preimage_iff_trivialModulePart_le_matsushima_h_pow_four_line :
    (forall beta : B,
        beta ∈ CuspidalCohomologyData.trivialModulePart (A := B) ->
          exists r : Rat,
            MatsushimaData.j_q (A := A) (B := B)
              (r • ((KaehlerClass.h : A) ^ 4)) = beta) ↔
      (CuspidalCohomologyData.trivialModulePart (A := B) ≤
        Submodule.span Rat
          {MatsushimaData.j_q (A := A) (B := B)
            ((KaehlerClass.h : A) ^ 4)}) := by
  constructor
  · intro hscalar beta hbeta
    obtain ⟨r, hr⟩ := hscalar beta hbeta
    rw [← hr, map_smul]
    exact
      Submodule.smul_mem _
        r
        (Submodule.subset_span (by simp))
  · intro hline beta hbeta
    have hbeta_line :
        beta ∈
          Submodule.span Rat
            {MatsushimaData.j_q (A := A) (B := B)
              ((KaehlerClass.h : A) ^ 4)} :=
      hline hbeta
    rw [Submodule.mem_span_singleton] at hbeta_line
    obtain ⟨r, hr⟩ := hbeta_line
    refine ⟨r, ?_⟩
    rw [map_smul]
    exact hr

omit [MatsushimaSurjectivityData A B] [MatsushimaCompactDualData A B] in
/-- After source-H8 is fixed, invariant-map bijectivity is equivalent to the
concrete line-containment target for `trivialModulePart`. -/
theorem sourceToTargetInvariantMap_bijective_iff_trivialModulePart_le_matsushima_h_pow_four_line
    (hsource_H8 :
      MatsushimaData.source_invariants (A := A) (B := B) =
        CompactDualData.H8 (A := A)) :
    Function.Bijective (sourceToTargetInvariantMap A B) ↔
      (CuspidalCohomologyData.trivialModulePart (A := B) ≤
        Submodule.span Rat
          {MatsushimaData.j_q (A := A) (B := B)
            ((KaehlerClass.h : A) ^ 4)}) :=
  (sourceToTargetInvariantMap_bijective_iff_cartan_scalar_preimage
    (A := A) (B := B) hsource_H8).trans
    (cartan_scalar_preimage_iff_trivialModulePart_le_matsushima_h_pow_four_line
      (A := A) (B := B))

/-- The R655 right-inverse/scalar contract is equivalently a contract whose
remaining target is the explicit `j_q(h^4)` line containment. -/
structure EVIIH8ResidualCartanLineContainmentContract
    (A B : Type*)
    [CommRing A] [Algebra Rat A] [CohomologyRing A]
    [KaehlerClass A] [CompactDualData A] [CartanCompactDualIso A]
    [AddCommGroup B] [Module Rat B]
    [MatsushimaData A B]
    [MatsushimaSurjectivityData A B]
    [MatsushimaCompactDualData A B]
    [CuspidalCohomologyData B]
    [EisensteinVanishingDeg8 A B]
    [CuspidalGInvariantTrivialModuleDeg8 A B] where
  source_invariants_exact_image : sourceInvariantExactImageTarget A B
  source_invariants_eq_H8 :
    MatsushimaData.source_invariants (A := A) (B := B) =
      CompactDualData.H8 (A := A)
  trivialModulePart_le_h_pow_four_line :
    CuspidalCohomologyData.trivialModulePart (A := B) ≤
      Submodule.span Rat
        {MatsushimaData.j_q (A := A) (B := B)
          ((KaehlerClass.h : A) ^ 4)}

/-- A line-containment contract gives the existing scalar-preimage contract. -/
def cartanScalarUpperBoundContract_of_cartanLineContainmentContract
    (O : EVIIH8ResidualCartanLineContainmentContract A B) :
    EVIIH8ResidualCartanScalarUpperBoundContract A B where
  source_invariants_exact_image := O.source_invariants_exact_image
  source_invariants_eq_H8 := O.source_invariants_eq_H8
  cartan_scalar_preimage :=
    (cartan_scalar_preimage_iff_trivialModulePart_le_matsushima_h_pow_four_line
      (A := A) (B := B)).2 O.trivialModulePart_le_h_pow_four_line

/-- The existing scalar-preimage contract gives the line-containment contract. -/
def cartanLineContainmentContract_of_cartanScalarUpperBoundContract
    (O : EVIIH8ResidualCartanScalarUpperBoundContract A B) :
    EVIIH8ResidualCartanLineContainmentContract A B where
  source_invariants_exact_image := O.source_invariants_exact_image
  source_invariants_eq_H8 := O.source_invariants_eq_H8
  trivialModulePart_le_h_pow_four_line :=
    (cartan_scalar_preimage_iff_trivialModulePart_le_matsushima_h_pow_four_line
      (A := A) (B := B)).1 O.cartan_scalar_preimage

/-- The line-containment package and the R647 scalar-preimage package are the
same residual target. -/
theorem residual_cartanLine_nonempty_iff_cartanScalar_nonempty :
    Nonempty (EVIIH8ResidualCartanLineContainmentContract A B) ↔
      Nonempty (EVIIH8ResidualCartanScalarUpperBoundContract A B) :=
  Iff.intro
    (fun h =>
      h.elim (fun O =>
        Nonempty.intro
          (cartanScalarUpperBoundContract_of_cartanLineContainmentContract
            (A := A) (B := B) O)))
    (fun h =>
      h.elim (fun O =>
        Nonempty.intro
          (cartanLineContainmentContract_of_cartanScalarUpperBoundContract
            (A := A) (B := B) O)))

end ScalarPreimageLineCriterion

section Obstruction

/-- Exact image and source-H8 still do not force the explicit line containment
in the current abstract interface.  The new formulation is a genuine target,
not a closure claim. -/
theorem current_interface_with_exactImage_sourceH8_does_not_force_h_pow_four_line :
    sourceInvariantExactImageTarget TargetBettiSource TargetBettiTarget ∧
      (MatsushimaData.source_invariants
          (A := TargetBettiSource) (B := TargetBettiTarget) =
        CompactDualData.H8 (A := TargetBettiSource)) ∧
      Not
        (CuspidalCohomologyData.trivialModulePart
            (A := TargetBettiTarget) ≤
          Submodule.span Rat
            {MatsushimaData.j_q
                (A := TargetBettiSource) (B := TargetBettiTarget)
              ((KaehlerClass.h : TargetBettiSource) ^ 4)}) := by
  rcases current_interface_with_exactImage_sourceH8_does_not_force_rightInverse_or_scalar
    with ⟨hexact, hsource, _, hnotScalar⟩
  refine ⟨hexact, hsource, ?_⟩
  intro hline
  exact hnotScalar
    ((cartan_scalar_preimage_iff_trivialModulePart_le_matsushima_h_pow_four_line
      (A := TargetBettiSource) (B := TargetBettiTarget)).2 hline)

end Obstruction

/-- R656 target names for route summaries. -/
def currentR656CartanGeneratorLineTargetNames : List String := [
  "prove Submodule.map j_q source_invariants = surjectivity_target",
  "prove source_invariants = H8",
  "prove trivialModulePart <= span {j_q(h^4)}"
]

/-- Machine-readable status for the R656 generator-line ledger. -/
structure R656CartanGeneratorLineSnapshot where
  proofWorkObligationCount : Nat
  cartanImageIdentifiedWithGeneratorLine : Bool
  generatorImageNonzero : Bool
  scalarPreimageEquivalentToLineContainment : Bool
  carrierFactsForceLineContainment : Bool
  fullHcClosureClaim : Bool
  isClosureClaim : Bool
  deriving Repr, DecidableEq, Inhabited

/-- Current R656 status: the scalar-preimage gap is now an explicit
line-containment target around the non-zero generator `j_q(h^4)`. -/
def currentR656CartanGeneratorLineSnapshot :
    R656CartanGeneratorLineSnapshot where
  proofWorkObligationCount := currentR656CartanGeneratorLineTargetNames.length
  cartanImageIdentifiedWithGeneratorLine := true
  generatorImageNonzero := true
  scalarPreimageEquivalentToLineContainment := true
  carrierFactsForceLineContainment := false
  fullHcClosureClaim := false
  isClosureClaim := false

/-- Kernel-checked numeric/Boolean status for the R656 ledger. -/
theorem currentR656CartanGeneratorLineSnapshot_eq_texStatus :
    currentR656CartanGeneratorLineSnapshot =
      ({ proofWorkObligationCount := 3
         cartanImageIdentifiedWithGeneratorLine := true
         generatorImageNonzero := true
         scalarPreimageEquivalentToLineContainment := true
         carrierFactsForceLineContainment := false
         fullHcClosureClaim := false
         isClosureClaim := false } :
        R656CartanGeneratorLineSnapshot) := by
  decide

/-- Kernel-checked target names for the R656 ledger. -/
theorem currentR656CartanGeneratorLineTargetNames_eq_texStatus :
    currentR656CartanGeneratorLineTargetNames = [
      "prove Submodule.map j_q source_invariants = surjectivity_target",
      "prove source_invariants = H8",
      "prove trivialModulePart <= span {j_q(h^4)}"
    ] := by
  rfl

def R656_substantiveTheoremCount : Nat := 10

end FrontC92_H8ResidualCartanGeneratorLineCriterion
end HCGapL4
end HodgeReduction
