/-
# HC Gap L4 -- Front C200: target-line nonzero gives the generator (R765).

R764 moves the source-containment frontier to target-line geometry:

  * prove `j_q(h^4) in target_invariants`;
  * prove `target_invariants <= span {j_q(h^4)}`;
  * keep honest `MatsushimaV56BoundaryData` explicit.

This file proves the linear-algebra compression behind the next attack.  If the
target-invariant subspace is contained in the one-dimensional line generated by
`j_q(h^4)` and has any nonzero class, then the generator of that line is itself
in `target_invariants`.  Therefore the generator-membership half can be
attacked by proving target-line containment plus target nonvanishing.

No target-line theorem, nonvanishing theorem, boundary theorem, or Hodge
conjecture closure is asserted here.
-/

import HodgeReduction.HCGapL4.FrontC199_H8ResidualTargetLineSourceContainmentBridge

set_option linter.dupNamespace false
set_option linter.unusedSectionVars false

namespace HodgeReduction
namespace HCGapL4
namespace FrontC200_H8ResidualTargetLineNonzeroGenerator

open HodgeReduction.Infrastructure.Cohomology
open HodgeReduction.Infrastructure.Shimura
open HodgeReduction.Infrastructure.Automorphic
open FrontC13_MatsushimaV56BoundaryBridge
open FrontC199_H8ResidualTargetLineSourceContainmentBridge

section TargetLineNonzeroGenerator

variable {A B : Type*}
  [CommRing A] [Algebra Rat A] [CohomologyRing A]
  [KaehlerClass A] [CompactDualData A] [CartanCompactDualIso A]
  [AddCommGroup B] [Module Rat B]
  [MatsushimaData A B]
  [MatsushimaSurjectivityData A B]
  [MatsushimaCompactDualData A B]
  [CuspidalCohomologyData B]
  [EisensteinVanishingDeg8 A B]
  [CuspidalGInvariantTrivialModuleDeg8 A B]

/-- **R765 substantive theorem (1/6)**: a nonzero subspace contained in the
line generated by `j_q(h^4)` contains that line generator. -/
theorem targetGenerator_mem_of_target_invariants_le_line_and_exists_nonzero
    (hline :
      LE.le (MatsushimaData.target_invariants (A := A) (B := B))
        (Submodule.span Rat
          {MatsushimaData.j_q (A := A) (B := B)
            ((KaehlerClass.h : A) ^ 4)}))
    (hnonzero :
      Exists fun beta : B =>
        (MatsushimaData.target_invariants (A := A) (B := B)).carrier beta /\
          Not (beta = 0)) :
    (MatsushimaData.target_invariants (A := A) (B := B)).carrier
      (MatsushimaData.j_q (A := A) (B := B)
        ((KaehlerClass.h : A) ^ 4)) := by
  obtain ⟨beta, hbeta_target, hbeta_ne⟩ := hnonzero
  have hbeta_line :
      beta ∈
        Submodule.span Rat
          {MatsushimaData.j_q (A := A) (B := B)
            ((KaehlerClass.h : A) ^ 4)} :=
    hline hbeta_target
  rw [Submodule.mem_span_singleton] at hbeta_line
  obtain ⟨r, hr⟩ := hbeta_line
  let targetGenerator : B :=
    MatsushimaData.j_q (A := A) (B := B)
      ((KaehlerClass.h : A) ^ 4)
  have hr_target : r • targetGenerator = beta := by
    simpa [targetGenerator] using hr
  have hr_ne : r ≠ 0 := by
    intro hr_zero
    apply hbeta_ne
    calc
      beta = r • targetGenerator := hr_target.symm
      _ = 0 := by simp [targetGenerator, hr_zero]
  have hgen_eq_inv_smul_beta :
      targetGenerator = r⁻¹ • beta := by
    calc
      targetGenerator = 1 • targetGenerator := by simp
      _ = (r⁻¹ * r) • targetGenerator := by
        rw [inv_mul_cancel₀ hr_ne]
        simp
      _ = r⁻¹ • (r • targetGenerator) := by
        simp [mul_smul]
      _ = r⁻¹ • beta := by
        rw [hr_target]
  dsimp [targetGenerator] at hgen_eq_inv_smul_beta
  rw [hgen_eq_inv_smul_beta]
  exact Submodule.smul_mem
    (MatsushimaData.target_invariants (A := A) (B := B)) r⁻¹ hbeta_target

/-- **R765 substantive theorem (2/6)**: the same nonzero witness can be given
on `trivialModulePart`, using the existing R554 equality
`target_invariants = trivialModulePart`. -/
theorem targetGenerator_mem_of_target_invariants_le_line_and_exists_nonzero_trivialModulePart
    (hline :
      LE.le (MatsushimaData.target_invariants (A := A) (B := B))
        (Submodule.span Rat
          {MatsushimaData.j_q (A := A) (B := B)
            ((KaehlerClass.h : A) ^ 4)}))
    (hnonzero :
      Exists fun beta : B =>
        (CuspidalCohomologyData.trivialModulePart (A := B)).carrier beta /\
          Not (beta = 0)) :
    (MatsushimaData.target_invariants (A := A) (B := B)).carrier
      (MatsushimaData.j_q (A := A) (B := B)
        ((KaehlerClass.h : A) ^ 4)) := by
  apply targetGenerator_mem_of_target_invariants_le_line_and_exists_nonzero
    (A := A) (B := B) hline
  obtain ⟨beta, hbeta_trivial, hbeta_ne⟩ := hnonzero
  exact ⟨beta, by
    simpa [target_invariants_eq_trivialModulePart (A := A) (B := B)]
      using hbeta_trivial, hbeta_ne⟩

/-- **R765 substantive theorem (3/6)**: boundary data, target-line
containment, and target nonzero prove the R763 generator/source containment. -/
theorem H8_le_source_invariants_of_boundaryData_targetLine_and_targetNonzero
    (D : MatsushimaV56BoundaryData A B)
    (hline :
      LE.le (MatsushimaData.target_invariants (A := A) (B := B))
        (Submodule.span Rat
          {MatsushimaData.j_q (A := A) (B := B)
            ((KaehlerClass.h : A) ^ 4)}))
    (hnonzero :
      Exists fun beta : B =>
        (MatsushimaData.target_invariants (A := A) (B := B)).carrier beta /\
          Not (beta = 0)) :
    LE.le (CompactDualData.H8 (A := A))
      (MatsushimaData.source_invariants (A := A) (B := B)) :=
  H8_le_source_invariants_of_boundaryData_targetGenerator_mem
    (A := A) (B := B) D
    (targetGenerator_mem_of_target_invariants_le_line_and_exists_nonzero
      (A := A) (B := B) hline hnonzero)

/-- **R765 substantive theorem (4/6)**: boundary data, target-line
containment, and target nonzero close the source-H8 equality. -/
theorem source_invariants_eq_H8_of_boundaryData_targetLine_and_targetNonzero
    (D : MatsushimaV56BoundaryData A B)
    (hline :
      LE.le (MatsushimaData.target_invariants (A := A) (B := B))
        (Submodule.span Rat
          {MatsushimaData.j_q (A := A) (B := B)
            ((KaehlerClass.h : A) ^ 4)}))
    (hnonzero :
      Exists fun beta : B =>
        (MatsushimaData.target_invariants (A := A) (B := B)).carrier beta /\
          Not (beta = 0)) :
    MatsushimaData.source_invariants (A := A) (B := B) =
      CompactDualData.H8 (A := A) :=
  source_invariants_eq_H8_of_boundaryData_targetGenerator_mem_and_targetLine
    (A := A) (B := B) D
    (targetGenerator_mem_of_target_invariants_le_line_and_exists_nonzero
      (A := A) (B := B) hline hnonzero)
    hline

/-- **R765 substantive theorem (5/6)**: the same fields feed the visible
compact-dual/H8 target. -/
theorem compactDual_eq_H8_of_boundaryData_targetLine_and_targetNonzero
    (D : MatsushimaV56BoundaryData A B)
    (hline :
      LE.le (MatsushimaData.target_invariants (A := A) (B := B))
        (Submodule.span Rat
          {MatsushimaData.j_q (A := A) (B := B)
            ((KaehlerClass.h : A) ^ 4)}))
    (hnonzero :
      Exists fun beta : B =>
        (MatsushimaData.target_invariants (A := A) (B := B)).carrier beta /\
          Not (beta = 0)) :
    MatsushimaCompactDualData.compactDual (A := A) (B := B) =
      CompactDualData.H8 (A := A) :=
  compactDual_eq_H8_of_boundaryData_targetGenerator_mem_and_targetLine
    (A := A) (B := B) D
    (targetGenerator_mem_of_target_invariants_le_line_and_exists_nonzero
      (A := A) (B := B) hline hnonzero)
    hline

/-- **R765 substantive theorem (6/6)**: the R765 theorem can consume
nonzero trivial-module data directly. -/
theorem compactDual_eq_H8_of_boundaryData_targetLine_and_trivialModulePartNonzero
    (D : MatsushimaV56BoundaryData A B)
    (hline :
      LE.le (MatsushimaData.target_invariants (A := A) (B := B))
        (Submodule.span Rat
          {MatsushimaData.j_q (A := A) (B := B)
            ((KaehlerClass.h : A) ^ 4)}))
    (hnonzero :
      Exists fun beta : B =>
        (CuspidalCohomologyData.trivialModulePart (A := B)).carrier beta /\
          Not (beta = 0)) :
    MatsushimaCompactDualData.compactDual (A := A) (B := B) =
      CompactDualData.H8 (A := A) :=
  compactDual_eq_H8_of_boundaryData_targetGenerator_mem_and_targetLine
    (A := A) (B := B) D
    (targetGenerator_mem_of_target_invariants_le_line_and_exists_nonzero_trivialModulePart
      (A := A) (B := B) hline hnonzero)
    hline

end TargetLineNonzeroGenerator

/-- R765 target names for route summaries. -/
def currentR765TargetLineNonzeroGeneratorTargetNames : List String := [
  "prove MatsushimaV56BoundaryData",
  "prove target_invariants <= span {j_q(h^4)}",
  "prove target_invariants has a nonzero class"
]

/-- Machine-readable status for the R765 target-line/nonzero bridge. -/
structure R765TargetLineNonzeroGeneratorSnapshot where
  proofWorkObligationCount : Nat
  targetLineAndNonzeroForceTargetGenerator : Bool
  targetLineAndNonzeroFeedSourceGeneratorContainment : Bool
  targetLineAndNonzeroFeedSourceH8 : Bool
  targetLineAndNonzeroFeedCompactDualH8 : Bool
  trivialModulePartNonzeroAccepted : Bool
  provesBoundaryData : Bool
  provesTargetLineContainment : Bool
  provesTargetNonzero : Bool
  provesTargetGeneratorMembership : Bool
  provesCompactDualH8 : Bool
  fullHcClosureClaim : Bool
  isClosureClaim : Bool
  deriving Repr, DecidableEq, Inhabited

/-- Current R765 status: the R764 target-generator field is not independent
once target-line containment and target nonzero are available. -/
def currentR765TargetLineNonzeroGeneratorSnapshot :
    R765TargetLineNonzeroGeneratorSnapshot where
  proofWorkObligationCount := currentR765TargetLineNonzeroGeneratorTargetNames.length
  targetLineAndNonzeroForceTargetGenerator := true
  targetLineAndNonzeroFeedSourceGeneratorContainment := true
  targetLineAndNonzeroFeedSourceH8 := true
  targetLineAndNonzeroFeedCompactDualH8 := true
  trivialModulePartNonzeroAccepted := true
  provesBoundaryData := false
  provesTargetLineContainment := false
  provesTargetNonzero := false
  provesTargetGeneratorMembership := false
  provesCompactDualH8 := false
  fullHcClosureClaim := false
  isClosureClaim := false

/-- Kernel-checked status for the R765 target-line/nonzero bridge. -/
theorem currentR765TargetLineNonzeroGeneratorSnapshot_eq_texStatus :
    currentR765TargetLineNonzeroGeneratorSnapshot =
      ({ proofWorkObligationCount := 3
         targetLineAndNonzeroForceTargetGenerator := true
         targetLineAndNonzeroFeedSourceGeneratorContainment := true
         targetLineAndNonzeroFeedSourceH8 := true
         targetLineAndNonzeroFeedCompactDualH8 := true
         trivialModulePartNonzeroAccepted := true
         provesBoundaryData := false
         provesTargetLineContainment := false
         provesTargetNonzero := false
         provesTargetGeneratorMembership := false
         provesCompactDualH8 := false
         fullHcClosureClaim := false
         isClosureClaim := false } :
        R765TargetLineNonzeroGeneratorSnapshot) := by
  decide

/-- Kernel-checked target names for the R765 bridge. -/
theorem currentR765TargetLineNonzeroGeneratorTargetNames_eq_texStatus :
    currentR765TargetLineNonzeroGeneratorTargetNames = [
      "prove MatsushimaV56BoundaryData",
      "prove target_invariants <= span {j_q(h^4)}",
      "prove target_invariants has a nonzero class"
    ] := by
  rfl

def R765_substantiveTheoremCount : Nat := 6

end FrontC200_H8ResidualTargetLineNonzeroGenerator
end HCGapL4
end HodgeReduction
