/-
# HC Gap L4 -- Front C138: Cartan image equals the boundary/source-H8 route (R703).

R702 connected the R646 Cartan-image containment route to the finite
trivial-multiplicity consumer.  R691 already used the explicit generator line
`span {j_q(h^4)}`, and R694 identified the preferred two-target route as

* honest `MatsushimaV56BoundaryData`;
* concrete source surjectivity `surjectivity_source = H8`.

This file closes the notation gap between those route surfaces.  The Cartan
image is exactly the line generated by `j_q(h^4)` (R656), so the R646/R702
Cartan-image contract is equivalent to the R691 generator-line contract.  The
same contract is also equivalent to the R694 boundary-data/source-H8 route.

No geometric target is proved here.  The remaining work is still the R694
two-target route: prove boundary data and prove source-H8 surjectivity.
-/

import HodgeReduction.HCGapL4.FrontC137_H8ResidualCartanImageFiniteMultiplicity
import HodgeReduction.HCGapL4.FrontC127_H8ResidualLineContainmentExplicitFiniteRoute
import HodgeReduction.HCGapL4.FrontC130_H8ResidualBoundaryDataSourceSurjectivityRoute

set_option linter.dupNamespace false
set_option linter.unusedSectionVars false

namespace HodgeReduction
namespace HCGapL4
namespace FrontC138_H8ResidualCartanImageBoundarySourceH8Equivalence

open HodgeReduction.Infrastructure.Cohomology
open HodgeReduction.Infrastructure.Shimura
open HodgeReduction.Infrastructure.Automorphic
open FrontC13_MatsushimaV56BoundaryBridge
open FrontC60_H8ResidualSourceCarrierSplitPackage
open FrontC82_H8ResidualAtlasMultiplicityCriterion
open FrontC92_H8ResidualCartanGeneratorLineCriterion
open FrontC117_H8ResidualSourceCompactDualCartanLineThreeTargetEquivalence
open FrontC123_H8ResidualGeneratorMultiplicityRoute
open FrontC127_H8ResidualLineContainmentExplicitFiniteRoute
open FrontC130_H8ResidualBoundaryDataSourceSurjectivityRoute
open FrontC135_H8ResidualFiniteRankOneTrivialMultiplicity
open FrontC136_H8ResidualFiniteTrivialMultiplicityExplicitRoute
open FrontC137_H8ResidualCartanImageFiniteMultiplicity

section CartanImageGeneratorLineBoundarySourceH8

variable {A B : Type*}
  [CommRing A] [Algebra Rat A] [CohomologyRing A]
  [KaehlerClass A] [CompactDualData A] [CartanCompactDualIso A]
  [AddCommGroup B] [Module Rat B]
  [MatsushimaData A B]
  [MatsushimaSurjectivityData A B]
  [MatsushimaCompactDualData A B]
  [CuspidalCohomologyData B]
  [EisensteinVanishingDeg8 A B]
  [CuspidalGInvariantTrivialModuleDeg8 A B]

/-- **R703 substantive theorem (1/6)**: the R646/R702 Cartan-image contract
feeds the R691 generator-line contract. -/
def sourceBoundaryLineContainmentContract_of_cartanImageUpperBoundContract
    (O : EVIIH8ResidualCartanImageUpperBoundContract A B) :
    EVIIH8ResidualSourceBoundaryLineContainmentContract A B where
  source_eq_compactDual :=
    (source_eq_compactDual_iff_sourceInvariantExactImageTarget
      (A := A) (B := B)).2 O.source_invariants_exact_image
  h_pow_four_mem_source_invariants :=
    h_pow_four_mem_source_invariants_of_source_invariants_eq_H8
      (A := A) (B := B) O.source_invariants_eq_H8
  trivialModulePart_le_h_pow_four_line := by
    simpa [cartan_image_eq_span_matsushima_h_pow_four (A := A) (B := B)]
      using O.trivialModulePart_le_cartanImage

/-- **R703 substantive theorem (2/6)**: conversely, the R691 generator-line
contract feeds the R646/R702 Cartan-image contract. -/
def cartanImageUpperBoundContract_of_sourceBoundaryLineContainmentContract
    (O : EVIIH8ResidualSourceBoundaryLineContainmentContract A B) :
    EVIIH8ResidualCartanImageUpperBoundContract A B where
  source_invariants_exact_image :=
    (source_eq_compactDual_iff_sourceInvariantExactImageTarget
      (A := A) (B := B)).1 O.source_eq_compactDual
  source_invariants_eq_H8 := by
    haveI :
        FiniteDimensional Rat
          (CuspidalCohomologyData.trivialModulePart (A := B)) :=
      trivialModulePart_finiteDimensional_of_h_pow_four_mem_source_lineContainment
        (A := A) (B := B)
        O.h_pow_four_mem_source_invariants
        O.trivialModulePart_le_h_pow_four_line
    exact
      source_invariants_eq_H8_of_h_pow_four_mem_source_trivialModulePartUpperBound
      (A := A) (B := B)
      O.h_pow_four_mem_source_invariants
      (trivialModulePart_upper_bound_of_h_pow_four_mem_source_lineContainment
        (A := A) (B := B)
        O.h_pow_four_mem_source_invariants
        O.trivialModulePart_le_h_pow_four_line)
  trivialModulePart_le_cartanImage := by
    simpa [cartan_image_eq_span_matsushima_h_pow_four (A := A) (B := B)]
      using O.trivialModulePart_le_h_pow_four_line

/-- **R703 substantive theorem (3/6)**: the Cartan-image route and the
generator-line route are the same inhabited residual contract. -/
theorem residual_cartanImageUpperBound_nonempty_iff_sourceBoundaryLineContainment_nonempty :
    Nonempty (EVIIH8ResidualCartanImageUpperBoundContract A B) <->
      Nonempty (EVIIH8ResidualSourceBoundaryLineContainmentContract A B) :=
  Iff.intro
    (fun h =>
      h.elim (fun O =>
        Nonempty.intro
          (sourceBoundaryLineContainmentContract_of_cartanImageUpperBoundContract
            (A := A) (B := B) O)))
    (fun h =>
      h.elim (fun O =>
        Nonempty.intro
          (cartanImageUpperBoundContract_of_sourceBoundaryLineContainmentContract
            (A := A) (B := B) O)))

/-- **R703 substantive theorem (4/6)**: a Cartan-image contract also rebuilds
the preferred R694 boundary-data/source-H8 contract. -/
def boundaryDataSourceSurjectivityContract_of_cartanImageUpperBoundContract
    (O : EVIIH8ResidualCartanImageUpperBoundContract A B) :
    EVIIH8ResidualBoundaryDataSourceSurjectivityContract A B := by
  let F : EVIIH8ResidualFiniteTrivialMultiplicityContract A B :=
    finiteTrivialMultiplicityContract_of_cartanImageUpperBoundContract
      (A := A) (B := B) O
  let D : MatsushimaV56BoundaryData A B :=
    boundaryData_of_finiteTrivialMultiplicityContract (A := A) (B := B) F
  exact
    { boundary := D
      surjectivity_source_eq_H8 :=
        (surjectivity_source_eq_H8_iff_source_invariants_eq_H8_of_boundaryData
          (A := A) (B := B) D).2 O.source_invariants_eq_H8 }

/-- **R703 substantive theorem (5/6)**: conversely, the R694
boundary-data/source-H8 route rebuilds the R646/R702 Cartan-image contract. -/
def cartanImageUpperBoundContract_of_boundaryDataSourceSurjectivityContract
    (O : EVIIH8ResidualBoundaryDataSourceSurjectivityContract A B) :
    EVIIH8ResidualCartanImageUpperBoundContract A B where
  source_invariants_exact_image :=
    (source_eq_compactDual_iff_sourceInvariantExactImageTarget
      (A := A) (B := B)).1 O.boundary.source_eq_compactDual
  source_invariants_eq_H8 :=
    source_invariants_eq_H8_of_boundaryData_surjectivity_source_eq_H8
      (A := A) (B := B) O.boundary O.surjectivity_source_eq_H8
  trivialModulePart_le_cartanImage := by
    have hline :
        CuspidalCohomologyData.trivialModulePart (A := B) <=
          Submodule.span Rat
            {MatsushimaData.j_q (A := A) (B := B)
              ((KaehlerClass.h : A) ^ 4)} :=
      trivialModulePart_le_h_pow_four_line_of_boundaryData_surjectivity_source_eq_H8
        (A := A) (B := B) O.boundary O.surjectivity_source_eq_H8
    simpa [cartan_image_eq_span_matsushima_h_pow_four (A := A) (B := B)]
      using hline

/-- **R703 substantive theorem (6/6)**: the Cartan-image route and the R694
boundary-data/source-H8 route are equivalent inhabited residual contracts. -/
theorem residual_cartanImageUpperBound_nonempty_iff_boundaryDataSourceSurjectivity_nonempty :
    Nonempty (EVIIH8ResidualCartanImageUpperBoundContract A B) <->
      Nonempty (EVIIH8ResidualBoundaryDataSourceSurjectivityContract A B) :=
  Iff.intro
    (fun h =>
      h.elim (fun O =>
        Nonempty.intro
          (boundaryDataSourceSurjectivityContract_of_cartanImageUpperBoundContract
            (A := A) (B := B) O)))
    (fun h =>
      h.elim (fun O =>
        Nonempty.intro
          (cartanImageUpperBoundContract_of_boundaryDataSourceSurjectivityContract
            (A := A) (B := B) O)))

end CartanImageGeneratorLineBoundarySourceH8

/-- R703 target names for route summaries. -/
def currentR703CartanImageBoundarySourceH8TargetNames : List String := [
  "prove MatsushimaV56BoundaryData",
  "prove surjectivity_source = H8"
]

/-- Machine-readable status for the R703 route equivalence. -/
structure R703CartanImageBoundarySourceH8Snapshot where
  proofWorkObligationCount : Nat
  cartanImageRouteEquivalentToGeneratorLineRoute : Bool
  cartanImageRouteEquivalentToBoundarySourceH8Route : Bool
  preferredRouteTargetCount : Nat
  provesBoundaryData : Bool
  provesSourceSurjectivityH8 : Bool
  provesCartanImageContainment : Bool
  introducesStrongerPremise : Bool
  fullHcClosureClaim : Bool
  isClosureClaim : Bool
  deriving Repr, DecidableEq, Inhabited

/-- Current R703 status: R646/R702, R691, and R694 are one route surface.
The remaining preferred target is still boundary data plus source-H8
surjectivity. -/
def currentR703CartanImageBoundarySourceH8Snapshot :
    R703CartanImageBoundarySourceH8Snapshot where
  proofWorkObligationCount :=
    currentR703CartanImageBoundarySourceH8TargetNames.length
  cartanImageRouteEquivalentToGeneratorLineRoute := true
  cartanImageRouteEquivalentToBoundarySourceH8Route := true
  preferredRouteTargetCount := 2
  provesBoundaryData := false
  provesSourceSurjectivityH8 := false
  provesCartanImageContainment := false
  introducesStrongerPremise := false
  fullHcClosureClaim := false
  isClosureClaim := false

/-- Kernel-checked Boolean status for the R703 route ledger. -/
theorem currentR703CartanImageBoundarySourceH8Snapshot_eq_texStatus :
    currentR703CartanImageBoundarySourceH8Snapshot =
      ({ proofWorkObligationCount := 2
         cartanImageRouteEquivalentToGeneratorLineRoute := true
         cartanImageRouteEquivalentToBoundarySourceH8Route := true
         preferredRouteTargetCount := 2
         provesBoundaryData := false
         provesSourceSurjectivityH8 := false
         provesCartanImageContainment := false
         introducesStrongerPremise := false
         fullHcClosureClaim := false
         isClosureClaim := false } :
        R703CartanImageBoundarySourceH8Snapshot) := by
  decide

/-- Kernel-checked target names for the R703 route. -/
theorem currentR703CartanImageBoundarySourceH8TargetNames_eq_texStatus :
    currentR703CartanImageBoundarySourceH8TargetNames = [
      "prove MatsushimaV56BoundaryData",
      "prove surjectivity_source = H8"
    ] := by
  rfl

def R703_substantiveTheoremCount : Nat := 6

end FrontC138_H8ResidualCartanImageBoundarySourceH8Equivalence
end HCGapL4
end HodgeReduction
