/-
# HC Gap L4 — Gaussian field pair carrier as a `CommRing` (R335).

R330 named the precise blocker for extending the GaussianInt action on
`PointEndHomQ` to a full `ℚ(i)`-action via Mathlib's
`IsLocalization.lift`: the universal property requires a `CommRing`
target, but `PointEndHomQ` (the rationalized point-End carrier built
in R321/R322) is non-commutative in general — composition of
`AddMonoidHom`s does not commute.

R335 takes the side-step recommended by R330:

  * Build the **pair carrier** `ℚ × ℚ`, equipped with the **Gaussian
    multiplication** `(a, b) * (c, d) = (a*c - b*d, a*d + b*c)`. As
    `(re + im·i) * (re' + im'·i)` this is exactly the ring structure
    of the Gaussian rationals `ℚ(i)`, modulo carrier identification.
  * Prove that this pair carrier is a (commutative!) `CommRing` —
    real algebra, all ring axioms discharged by `ext + ring`.
  * Define the canonical embedding
    `GaussianFieldPairCarrier → PointEndHomQ` sending
    `(a, b) ↦ a • pointEnd_id_Q + b • gaussianCM_phi_Q`. This is the
    `ℚ`-linear lift of the bivariate embedding into the commutative
    subring of `PointEndHomQ` generated by `pointEnd_id_Q` and
    `gaussianCM_phi_Q`.
  * Prove that the embedding preserves `0`, `1`, `+`, `-`. (All four
    closed in this round.) Multiplication preservation is the R336+
    target — it reduces to the same bilinear expansion identity
    `gaussianCM_phi_Q² = -pointEnd_id_Q` (R322) plus distributivity
    of the (bilinear, non-commutative) `PointEndHomQ_mul`, but the
    bookkeeping is heavy enough that R335 leaves it as a marker.

## Strategic anchor

This pair carrier IS the Gaussian rationals as `(re, im) : ℚ × ℚ`
with Gaussian multiplication. It provides the `CommRing` target
needed for any `ℚ(i)`-localization: Mathlib's `IsLocalization.lift`
can now consume this carrier directly, bypassing the (false)
`CommRing PointEndHomQ` requirement. Concretely: combine
`GaussianRationalFieldCandidate = FractionRing GaussianInt` (R267-B)
with the embedding `GaussianInt → GaussianFieldPairCarrier` (one
round downstream) and `IsLocalization.lift` extends the GaussianInt
action to a `ℚ(i)`-action on `GaussianFieldPairCarrier`. The final
piece is the embedding constructed in this file:
`GaussianFieldPairCarrier → PointEndHomQ`, which carries the
`ℚ(i)`-action over to `PointEndHomQ`. That is the source-side
`End⁰`-action consumed by
`canonicalE7ShimuraTor.mtCorrespondencePackage`.

## What R335 (this file) provides (all kernel-pure)

* `GaussianFieldPairCarrier : Type` — pair carrier `(re, im) : ℚ × ℚ`.
* `Zero / One / Neg / Add / Sub / Mul` instances with Gaussian mul.
* Component-pointwise `simp` lemmas for each operation.
* `instCommRing : CommRing GaussianFieldPairCarrier` — closed.
* `Module ℚ GaussianFieldPairCarrier` — closed via the inferred
  `Algebra ℚ` from the `CommRing` plus the rationals on the components.
* `GaussianFieldPair_to_PointEndHomQ` — the embedding into
  `PointEndHomQ`.
* `_zero / _one / _add / _neg` preservation theorems (closed).
* `Target_GaussianFieldPair_to_PointEndHomQ_mul` — multiplication
  preservation marker (R336+ target).
* `L4-G` disclosure markers / status / non-closure markers.

## What R335 does NOT do

* Does NOT close multiplication preservation of the embedding.
* Does NOT construct true algebraic `End⁰(E_K)`.
* Does NOT close `canonicalE7ShimuraTor.mtCorrespondencePackage`.

All declarations kernel-pure: axiom cone
`⊆ {propext, Classical.choice, Quot.sound}`. No `axiom`, no `sorry`,
no `:= True` for substantive closure (markers/status/explicit-mul
target only).
-/

import HodgeReduction.HCGapL4.PointEndHomQMultiplication

set_option maxSynthPendingDepth 4

namespace HodgeReduction
namespace HCGapL4

open scoped TensorProduct

/-! ## Section 1: pair carrier as a NEW structure

We use a fresh `structure` rather than `Prod ℚ ℚ` directly so we can
register `Mul` as the Gaussian multiplication without colliding with
Mathlib's componentwise `Mul (ℚ × ℚ)` instance. -/

/-- **R335** Gaussian pair carrier: `(re, im) : ℚ × ℚ` representing
`re + im·i ∈ ℚ(i)`. A bespoke `structure` (rather than `ℚ × ℚ`) so the
Gaussian `Mul` instance below does not collide with Mathlib's
componentwise `Mul` on `Prod`. -/
@[ext]
structure GaussianFieldPairCarrier where
  /-- Real component. -/
  re : ℚ
  /-- Imaginary component. -/
  im : ℚ
  deriving DecidableEq

namespace GaussianFieldPairCarrier

/-! ## Section 2: ring operations + component-pointwise `simp` lemmas

Each operation is defined elementwise; the Gaussian mul has the
distinctive `(a*c - b*d, a*d + b*c)` shape. -/

/-- Zero element: `0 + 0·i`. -/
instance : Zero GaussianFieldPairCarrier := ⟨⟨0, 0⟩⟩

/-- One element: `1 + 0·i`. -/
instance : One GaussianFieldPairCarrier := ⟨⟨1, 0⟩⟩

/-- Negation: componentwise. -/
instance : Neg GaussianFieldPairCarrier := ⟨fun x => ⟨-x.re, -x.im⟩⟩

/-- Addition: componentwise. -/
instance : Add GaussianFieldPairCarrier :=
  ⟨fun x y => ⟨x.re + y.re, x.im + y.im⟩⟩

/-- Subtraction: componentwise. -/
instance : Sub GaussianFieldPairCarrier :=
  ⟨fun x y => ⟨x.re - y.re, x.im - y.im⟩⟩

/-- Gaussian multiplication: `(a, b) * (c, d) = (a*c - b*d, a*d + b*c)`. -/
instance : Mul GaussianFieldPairCarrier :=
  ⟨fun x y => ⟨x.re * y.re - x.im * y.im,
                x.re * y.im + x.im * y.re⟩⟩

@[simp] theorem zero_re : (0 : GaussianFieldPairCarrier).re = 0 := rfl
@[simp] theorem zero_im : (0 : GaussianFieldPairCarrier).im = 0 := rfl
@[simp] theorem one_re : (1 : GaussianFieldPairCarrier).re = 1 := rfl
@[simp] theorem one_im : (1 : GaussianFieldPairCarrier).im = 0 := rfl
@[simp] theorem add_re (x y : GaussianFieldPairCarrier) :
    (x + y).re = x.re + y.re := rfl
@[simp] theorem add_im (x y : GaussianFieldPairCarrier) :
    (x + y).im = x.im + y.im := rfl
@[simp] theorem neg_re (x : GaussianFieldPairCarrier) :
    (-x).re = -x.re := rfl
@[simp] theorem neg_im (x : GaussianFieldPairCarrier) :
    (-x).im = -x.im := rfl
@[simp] theorem sub_re (x y : GaussianFieldPairCarrier) :
    (x - y).re = x.re - y.re := rfl
@[simp] theorem sub_im (x y : GaussianFieldPairCarrier) :
    (x - y).im = x.im - y.im := rfl
@[simp] theorem mul_re (x y : GaussianFieldPairCarrier) :
    (x * y).re = x.re * y.re - x.im * y.im := rfl
@[simp] theorem mul_im (x y : GaussianFieldPairCarrier) :
    (x * y).im = x.re * y.im + x.im * y.re := rfl

/-! ## Section 3: `CommRing` instance

All field axioms are discharged by `ext` followed by `simp` / `ring`
on the components — both `re` and `im` live in `ℚ`, so any polynomial
identity in `ℚ` works. We supply `nsmul := nsmulRec` and
`zsmul := zsmulRec` so Lean picks the recursive defaults rather than
requiring a custom witness. -/

/-- **R335** the Gaussian pair carrier is a `CommRing`. Proof: every
ring axiom reduces under `ext` to a polynomial identity on the two
`ℚ`-components, discharged by `ring`. -/
instance instCommRing : CommRing GaussianFieldPairCarrier where
  zero_add x := by ext <;> simp
  add_zero x := by ext <;> simp
  add_comm x y := by ext <;> simp [add_comm]
  add_assoc x y z := by ext <;> simp [add_assoc]
  neg_add_cancel x := by ext <;> simp
  mul_one x := by ext <;> simp
  one_mul x := by ext <;> simp
  mul_comm x y := by ext <;> (simp; ring)
  mul_assoc x y z := by ext <;> (simp; ring)
  left_distrib x y z := by ext <;> (simp; ring)
  right_distrib x y z := by ext <;> (simp; ring)
  zero_mul x := by ext <;> simp
  mul_zero x := by ext <;> simp
  sub_eq_add_neg x y := by ext <;> simp [sub_eq_add_neg]
  nsmul := nsmulRec
  zsmul := zsmulRec

/-! ## Section 4: `Module ℚ` instance

Equip the pair carrier with a `SMul ℚ` defined componentwise, then
discharge the `Module ℚ` axioms by `ext + ring` on the components. We
choose this explicit form rather than relying on the typeclass search
to derive an `Algebra ℚ` from `CommRing + CharZero`: the explicit
construction is local, transparent, and provably aligned with the
componentwise smul we want to use on the embedding. -/

/-- **R335** componentwise `ℚ`-scalar multiplication. -/
instance : SMul ℚ GaussianFieldPairCarrier :=
  ⟨fun q x => ⟨q * x.re, q * x.im⟩⟩

@[simp] theorem smul_re (q : ℚ) (x : GaussianFieldPairCarrier) :
    (q • x).re = q * x.re := rfl

@[simp] theorem smul_im (q : ℚ) (x : GaussianFieldPairCarrier) :
    (q • x).im = q * x.im := rfl

/-- **R335** the pair carrier is a `Module ℚ` via the componentwise
smul. All axioms reduce to polynomial identities on `ℚ`. -/
instance instModuleQ : Module ℚ GaussianFieldPairCarrier where
  smul_add q x y := by ext <;> (simp; ring)
  add_smul p q x := by ext <;> (simp; ring)
  mul_smul p q x := by ext <;> (simp; ring)
  one_smul x := by ext <;> simp
  smul_zero q := by ext <;> simp
  zero_smul x := by ext <;> simp

end GaussianFieldPairCarrier

/-! ## Section 5: the embedding into `PointEndHomQ`

The map `(a, b) ↦ a • pointEnd_id_Q + b • gaussianCM_phi_Q` is the
`ℚ`-linear lift of the obvious "Gaussian rationals → commutative
subring of PointEndHomQ" embedding. -/

/-- **R335** the embedding
`(a, b) ↦ a • pointEnd_id_Q + b • gaussianCM_phi_Q` from the Gaussian
pair carrier into the rationalized point-End carrier. -/
noncomputable def GaussianFieldPair_to_PointEndHomQ
    (p : GaussianFieldPairCarrier) : PointEndHomQ :=
  p.re • pointEnd_id_Q + p.im • gaussianCM_phi_Q

/-- **R335** pointwise unfold for the embedding at an explicit pair. -/
@[simp] theorem GaussianFieldPair_to_PointEndHomQ_apply
    (a b : ℚ) :
    GaussianFieldPair_to_PointEndHomQ ⟨a, b⟩
      = a • pointEnd_id_Q + b • gaussianCM_phi_Q := rfl

/-! ## Section 6: preservation of `0`, `1`, `+`, `-`

These four are the "additive-monoid-with-one" part of the embedding;
multiplication preservation is the R336+ target (Section 7). -/

/-- **R335** the embedding sends `0` to `0`. -/
theorem GaussianFieldPair_to_PointEndHomQ_zero :
    GaussianFieldPair_to_PointEndHomQ 0 = 0 := by
  show (0 : ℚ) • pointEnd_id_Q + (0 : ℚ) • gaussianCM_phi_Q = 0
  rw [zero_smul, zero_smul, add_zero]

/-- **R335** the embedding sends `1` to `pointEnd_id_Q`. -/
theorem GaussianFieldPair_to_PointEndHomQ_one :
    GaussianFieldPair_to_PointEndHomQ 1 = pointEnd_id_Q := by
  show (1 : ℚ) • pointEnd_id_Q + (0 : ℚ) • gaussianCM_phi_Q = pointEnd_id_Q
  rw [one_smul, zero_smul, add_zero]

/-- **R335** the embedding preserves addition. -/
theorem GaussianFieldPair_to_PointEndHomQ_add
    (x y : GaussianFieldPairCarrier) :
    GaussianFieldPair_to_PointEndHomQ (x + y)
      = GaussianFieldPair_to_PointEndHomQ x
        + GaussianFieldPair_to_PointEndHomQ y := by
  show (x.re + y.re) • pointEnd_id_Q
        + (x.im + y.im) • gaussianCM_phi_Q
      = (x.re • pointEnd_id_Q + x.im • gaussianCM_phi_Q)
        + (y.re • pointEnd_id_Q + y.im • gaussianCM_phi_Q)
  rw [add_smul, add_smul]
  abel

/-- **R335** the embedding preserves negation. -/
theorem GaussianFieldPair_to_PointEndHomQ_neg
    (x : GaussianFieldPairCarrier) :
    GaussianFieldPair_to_PointEndHomQ (-x)
      = -(GaussianFieldPair_to_PointEndHomQ x) := by
  show (-x.re) • pointEnd_id_Q + (-x.im) • gaussianCM_phi_Q
      = -(x.re • pointEnd_id_Q + x.im • gaussianCM_phi_Q)
  rw [neg_smul, neg_smul]
  abel

/-! ## Section 7: multiplication preservation target

The mul-preservation identity expands to a bilinear computation
involving `gaussianCM_phi_Q² = -pointEnd_id_Q` (R322) plus the
distributive expansion of `PointEndHomQ_mul`. Because
`PointEndHomQ_mul` is a `LinearMap.mk₂` value (not yet a `Mul`
typeclass) and is built through Mathlib's `TensorProduct.map₂`, the
expansion bookkeeping is substantial. R335 records the target; R336+
discharges it once the bilinearity helpers + distributivity normal
forms are in hand. -/

/-- **R335 target**: the embedding preserves multiplication.

  `GaussianFieldPair_to_PointEndHomQ (x * y)
    = PointEndHomQ_mul (GaussianFieldPair_to_PointEndHomQ x)
                       (GaussianFieldPair_to_PointEndHomQ y)`

This requires the `PointEndHomQ_mul` distributivity normal form
(bilinear expansion over `+` and `•` in both arguments) plus R322's
`gaussianCM_phi_Q_sq_eq_neg_one`. Pinned for R336+. -/
def Target_GaussianFieldPair_to_PointEndHomQ_mul : Prop :=
  ∀ x y : GaussianFieldPairCarrier,
    GaussianFieldPair_to_PointEndHomQ (x * y)
      = PointEndHomQ_mul
          (GaussianFieldPair_to_PointEndHomQ x)
          (GaussianFieldPair_to_PointEndHomQ y)

/-! ## Section 8: `L4-G` disclosure markers -/

/-- **L4-G** bridge from the R335 pair carrier to the
`IsLocalization.lift` of the GaussianInt action to `ℚ(i)`. R335
supplies the `CommRing` target; the lift itself is downstream. -/
def L4_G_GaussianFieldSubringCommRing_To_Localization : Prop := True

/-- **L4-G** bridge from the R335 pair carrier to a `ℚ(i)`-action
on `PointEndHomQ`. R335 supplies the embedding into PointEndHomQ;
the action follows once mul-preservation closes. -/
def L4_G_GaussianFieldSubringCommRing_To_PointEndQAction : Prop := True

/-- **L4-G** bridge to the active HC cone field
`canonicalE7ShimuraTor.mtCorrespondencePackage`. The R335 pair carrier
is the precise `CommRing` target named in the R330 blocker; together
with the embedding it gives the source-side `End⁰`-action structural
input that `mtCorrespondencePackage` consumes. -/
def L4_G_GaussianFieldSubringCommRing_To_mtCorrespondencePackage :
    Prop := True

/-! ## Section 9: status -/

/-- **R335 status**: the `CommRing GaussianFieldPairCarrier` instance
is closed. -/
def R335_Status_CommRing_Closed : Prop := True

/-- **R335 status**: the embedding `GaussianFieldPair_to_PointEndHomQ`
is defined. -/
def R335_Status_Embedding_Defined : Prop := True

/-- **R335 status**: the embedding preserves `0`, `1`, `+`, `-`
(all four closed). -/
def R335_Status_Embedding_Add_Closed : Prop := True

/-- **R335 status**: multiplication preservation of the embedding is
pinned as a target (R336+). -/
def R335_Status_Embedding_Mul_Target_Or_Closed : Prop := True

/-! ## Section 10: explicit non-closure -/

/-- **R335 non-closure (1/3)**: does NOT construct full algebraic
`End⁰(E_K)`. R335 builds a commutative `CommRing` carrier (the
Gaussian pair) and embeds it into `PointEndHomQ`; the true algebraic
`End⁰(E_K)` (point-group rationalization vs. true algebraic-End
rationalization) remains the same downstream gap as in R321-R322. -/
theorem R335_does_not_construct_full_End0 : True := trivial

/-- **R335 non-closure (2/3)**: does NOT close
`canonicalE7ShimuraTor.mtCorrespondencePackage`. R335 supplies the
`CommRing` target named in the R330 blocker; the cohomology-action
layer that consumes the source-side `End⁰`-action is downstream. -/
theorem R335_does_not_close_mtCorrespondencePackage : True := trivial

/-- **R335 non-closure (3/3)**: does NOT close `canonicalE7ShimuraTor`
(the active HC cone field). R335 supplies one structural ingredient
along the R327-R338 chain. -/
theorem R335_does_not_close_canonicalE7ShimuraTor : True := trivial

end HCGapL4
end HodgeReduction
