/-
# HC Gap L4 — Gaussian CM action: coordinate-ring preservation (R310).

Building on:
* R267-B — `gaussianRationalI : GaussianRationalFieldCandidate`.
* R285 — `gaussianRationalI_sq_eq_neg_one : gaussianRationalI^2 = -1`.
* R289 — `gaussianRationalI_ne_zero`.
* R300 — `GaussianCMEllipticCurveTargetBaseChange : WeierstrassCurve K`
  with `a₁ = a₂ = a₃ = a₆ = 0`, `a₄ = 1` (i.e. `y² = x³ + x`).
* R301 — `gaussianCMAction_preserves_equation` (function-level).

This file expresses the polynomial identity at the COORDINATE level
(not the `Equation` predicate, not the `Point` type):

For any `x y : K`, substituting `(x, y) ↦ (-x, i·y)` into the
defining polynomial `Y² - X³ - X` of the curve `y² = x³ + x` gives
`-(Y² - X³ - X)`:

    (i·y)² - (-x)³ - (-x)
      = -y² + x³ + x
      = -(y² - x³ - x).

This is the COORDINATE-RING-level statement of the CM action's
compatibility with the curve equation. It is strictly stronger than
`gaussianCMAction_preserves_equation` (R301), which only states the
conditional implication on `Equation x y = 0`; here we record the
unconditional polynomial identity from which R301 follows.

The corresponding ideal-theoretic statement — that the principal ideal
`(Y² - X³ - X) ⊆ K[X, Y]` is preserved by the substitution — would
require MvPolynomial / Ideal API. We record it as a target marker.

## What this file provides (all kernel-pure)

* `gaussianCMAction_coordinate_polynomial_preserves` — the polynomial
  identity `(i·y)² - (-x)³ - (-x) = -(y² - x³ - x)`.
* `gaussianCMAction_coordinate_polynomial_preserves_zero` — corollary
  for the zero locus: `y² - x³ - x = 0 → (i·y)² - (-x)³ - (-x) = 0`.
* Target marker for the ideal-level preservation.
* Status / non-closure markers.

All declarations kernel-pure: axiom cone ⊆ `{propext, Classical.choice,
Quot.sound}`.
-/

import HodgeReduction.HCGapL4.GaussianCMActionEquationPreservation
import HodgeReduction.HCGapL4.GaussianRationalAdjoinRootEquiv

namespace HodgeReduction
namespace HCGapL4

open HodgeReduction.HCGapL4.ComplexMultiplicationQuadraticFieldCandidate

/-! ## Section 1: coordinate-polynomial preservation -/

/-- **R310** the polynomial identity expressing that the substitution
`(x, y) ↦ (-x, i·y)` sends `Y² - X³ - X` to `-(Y² - X³ - X)` over
`K = GaussianRationalFieldCandidate`.

Proof: expand `(i·y)² = i²·y² = -y²` using R285, then linear
combination:
  `(i·y)² - (-x)³ - (-x) = -y² + x³ + x = -(y² - x³ - x)`. -/
theorem gaussianCMAction_coordinate_polynomial_preserves
    (x y : GaussianRationalFieldCandidate) :
    (gaussianRationalI * y)^2 - (-x)^3 - (-x)
      = -(y^2 - x^3 - x) := by
  have hi : (gaussianRationalI : GaussianRationalFieldCandidate)^2 = -1 :=
    gaussianRationalI_sq_eq_neg_one
  linear_combination y^2 * hi

/-- **R310** corollary: on the zero locus, the CM substitution
preserves the equation `Y² - X³ - X = 0`.

Proof: rewrite via `gaussianCMAction_coordinate_polynomial_preserves`,
then substitute `h` and simplify `-0 = 0`. -/
theorem gaussianCMAction_coordinate_polynomial_preserves_zero
    (x y : GaussianRationalFieldCandidate)
    (h : y^2 - x^3 - x = 0) :
    (gaussianRationalI * y)^2 - (-x)^3 - (-x) = 0 := by
  rw [gaussianCMAction_coordinate_polynomial_preserves, h, neg_zero]

/-! ## Section 2: ideal-level target (marker only) -/

/-- **R310 target**: the principal ideal generated by `Y² - X³ - X`
in `K[X, Y]` is sent into itself under the substitution
`X ↦ -X, Y ↦ i·Y`. Equivalently, the generator is mapped to `-1`
times itself, which lies in the same ideal.

This is the IDEAL-THEORETIC reformulation of
`gaussianCMAction_coordinate_polynomial_preserves`. Closing it would
require importing `Mathlib.RingTheory.MvPolynomial.Basic` and Ideal
API, which is heavy machinery the function-level identity does not
need. -/
def Target_gaussianCMAction_coordinateRing_preserves_principalIdeal :
    Prop := True

/-! ## Section 3: status / closure -/

/-- **R310 status**: coordinate-polynomial preservation identity
closed. -/
def R310_Status_Coordinate_Polynomial_Preserves : Prop := True

/-- **R310 status**: zero-locus corollary closed. -/
def R310_Status_Coordinate_Polynomial_Preserves_Zero : Prop := True

/-! ## Section 4: next-target markers (R311+) -/

/-- **R311 next target**: package the coordinate-ring preservation as
an affine algebraic-morphism interface (a structure carrying the
coordinate maps, the equation-preservation hypothesis, and a bridge
to the point-level map). -/
def L4_G_CoordinateRingPreservation_To_AlgebraicMorphism :
    Prop := True

/-- **R310 missing infrastructure**: the coordinate-ring quotient
`K[X, Y] / (Y² - X³ - X)` is not constructed in Mathlib for our
curve. Closing this requires MvPolynomial + Ideal.span + quotient
API. -/
def L4_G_CoordinateRingPreservation_MissingCoordinateRingQuotient :
    Prop := True

/-- **R310 missing infrastructure**: the scheme-morphism structure
`Spec(K[X, Y] / (Y² - X³ - X)) → Spec(K[X, Y] / (Y² - X³ - X))`
induced by the substitution is not constructed. Closing this requires
algebraic-geometry API (Spec, scheme morphism). -/
def L4_G_CoordinateRingPreservation_MissingSchemeMorphism : Prop := True

/-! ## Section 5: explicit non-closure -/

/-- **R310 non-closure (1/4)**: does NOT construct a scheme-morphism
on `Spec(K[X, Y] / (Y² - X³ - X))`. -/
theorem R310_does_not_construct_scheme_morphism : True := trivial

/-- **R310 non-closure (2/4)**: does NOT construct an algebraic
`End`-element (no End-ring is built here; that is the R293 Mathlib
gap). -/
theorem R310_does_not_construct_algebraic_End : True := trivial

/-- **R310 non-closure (3/4)**: does NOT construct `End⁰` (the
`End`-ring tensored with ℚ); same R293 gap. -/
theorem R310_does_not_construct_End0 : True := trivial

/-- **R310 non-closure (4/4)**: does NOT close
`canonicalE7ShimuraTor`. -/
theorem R310_does_not_close_canonicalE7ShimuraTor : True := trivial

end HCGapL4
end HodgeReduction
