/-
# HC Gap L4 — Gaussian CM action affine algebraic-morphism interface (R311).

R310 established coordinate-ring preservation: substituting
`(x, y) ↦ (-x, i·y)` in `y² - x³ - x` gives `-(y² - x³ - x)`,
so the principal ideal generated by the Weierstrass polynomial is
preserved (mapped into itself).

R311 wraps R310 + R301-R303 (point map + nonsingular preservation)
into a local interface for an *affine algebraic self-map* of the
curve given by coordinate maps.

## What R311 provides (all kernel-pure)

* `AffineCurveSelfMapByCoordinatesSkeleton` — interface.
* `GaussianCMAction_AffineMorphismSkeleton` — instance for our curve.
* `GaussianCMAction_AffineMorphismSkeleton_equationPreservation_holds` —
  real theorem providing the equation-preservation witness.

## What R311 does NOT do

* Does NOT construct a scheme morphism.
* Does NOT construct algebraic `End(E)`.
* Does NOT close `canonicalE7ShimuraTor`.

All declarations kernel-pure.
-/

import HodgeReduction.HCGapL4.GaussianCMActionCoordinateRing
import HodgeReduction.HCGapL4.GaussianCMActionPointMap

namespace HodgeReduction
namespace HCGapL4

open HodgeReduction.HCGapL4.ComplexMultiplicationQuadraticFieldCandidate

/-! ## Section 1: interface skeleton -/

/-- **R311** local interface: an affine self-map of an elliptic curve
defined by coordinate maps `(x, y) ↦ (Mₓ x, M_y y)`. Records the
equation-preservation property and bridges to a point-level map. -/
structure AffineCurveSelfMapByCoordinatesSkeleton where
  /-- Base field. -/
  K : Type
  /-- The point type (left abstract). -/
  pointType : Type
  /-- The x-coordinate map. -/
  coordMapX : K → K
  /-- The y-coordinate map. -/
  coordMapY : K → K
  /-- Target: equation `Y² - X³ - X = 0` is preserved (Prop slot). -/
  equationPreservation : Prop
  /-- Target: induced point map exists. -/
  inducedPointMapTarget : Prop
  /-- Target: induced point map agrees with an externally given point map. -/
  agreesWithPointMapTarget : Prop

/-! ## Section 2: Gaussian CM instance -/

/-- **R311** Gaussian instance of the affine self-map interface. -/
noncomputable def GaussianCMAction_AffineMorphismSkeleton :
    AffineCurveSelfMapByCoordinatesSkeleton where
  K := GaussianRationalFieldCandidate
  pointType := GaussianCMEllipticCurveTargetBaseChange.toAffine.Point
  coordMapX := fun x => -x
  coordMapY := fun y => gaussianRationalI * y
  equationPreservation :=
    ∀ x y : GaussianRationalFieldCandidate,
      (gaussianRationalI * y)^2 - (-x)^3 - (-x) = -(y^2 - x^3 - x)
  inducedPointMapTarget := True
  agreesWithPointMapTarget := True

/-- **R311** witness theorem: the equation-preservation field of the
Gaussian instance is in fact provable (via R310). -/
theorem GaussianCMAction_AffineMorphismSkeleton_equationPreservation_holds :
    GaussianCMAction_AffineMorphismSkeleton.equationPreservation :=
  gaussianCMAction_coordinate_polynomial_preserves

/-! ## Section 3: bridge to point-level map (definitional) -/

/-- **R311** the coordinate map at the field level. -/
noncomputable def gaussianCMAction_coord_field :
    GaussianRationalFieldCandidate × GaussianRationalFieldCandidate →
      GaussianRationalFieldCandidate × GaussianRationalFieldCandidate :=
  fun ⟨x, y⟩ =>
    (GaussianCMAction_AffineMorphismSkeleton.coordMapX x,
     GaussianCMAction_AffineMorphismSkeleton.coordMapY y)

/-- **R311**: definitional unfold. -/
theorem gaussianCMAction_coord_field_apply
    (x y : GaussianRationalFieldCandidate) :
    gaussianCMAction_coord_field (x, y) = (-x, gaussianRationalI * y) := rfl

/-! ## Section 4: status / markers -/

/-- **R311 status**: interface defined. -/
def R311_Status_Interface_Defined : Prop := True

/-- **R311 status**: Gaussian instance populated. -/
def R311_Status_Gaussian_Instance_Populated : Prop := True

/-- **R311 status**: equation-preservation witness available. -/
def R311_Status_Equation_Preservation_Witness_Available : Prop := True

/-- **L4-G** bridge to algebraic End(E). -/
def L4_G_AffineMorphismInterface_To_AlgebraicEnd : Prop := True

/-- **L4-G** bridge to scheme morphism. -/
def L4_G_AffineMorphismInterface_To_SchemeMorphism : Prop := True

/-- **L4-G** bridge to End⁰(E). -/
def L4_G_AffineMorphismInterface_To_End0 : Prop := True

/-! ## Section 5: explicit non-closure -/

/-- **R311 non-closure (1/4)**: does NOT construct scheme morphism. -/
theorem R311_does_not_construct_scheme_morphism : True := trivial

/-- **R311 non-closure (2/4)**: does NOT construct algebraic `End(E)`. -/
theorem R311_does_not_construct_algebraic_End : True := trivial

/-- **R311 non-closure (3/4)**: does NOT construct `End⁰(E)`. -/
theorem R311_does_not_construct_End0 : True := trivial

/-- **R311 non-closure (4/4)**: does NOT close
`canonicalE7ShimuraTor`. -/
theorem R311_does_not_close_canonicalE7ShimuraTor : True := trivial

end HCGapL4
end HodgeReduction
