/-
# HC Gap L4 — Internal elliptic cycle class map at codim 1 (R353).

R348 stated the cycle-class equivariance target. R350 ranked the next
exact targets and recorded `R350_NextTarget_R352_CycleClassMap_AtInternalModel`.
R353 (this round) defines the **internal** cycle class map at codim 1
for the internal elliptic-curve cohomology model, lands it in the
internal H² model `H²(E, ℚ) = ℚ` of R203, and proves the surjectivity
and i-equivariance statements at the internal level.

## Mathematics

For the internal elliptic-curve model (R203, `HCGapL2/EllipticCurve.lean`):
* `H²(E, ℚ) = ℚ` (`cohomologyType_ellipticCurve 2 = ℚ`).
* `algClasses_ellipticCurve 1 = ⊤ : Submodule ℚ ℚ` (point class `[pt]`).
* Codim-1 cycle group is generated by the point class — structurally `ℚ`.

At this internal model:
* Cycle class map `cl¹ : Cycle¹(E) → H²(E, ℚ)` is the identity `ℚ → ℚ`.
* The point class `[pt] ∈ Cycle¹(E)` maps to the generator of H² = ℚ.
* Range of `cl¹` is `⊤`, which equals `algClasses 1`.
* This is the precise content of "every algebraic class is hit by a cycle"
  at the internal level.

For i-equivariance: R346 shows that the action of `α ∈ ℚ(i)` on H² is
by multiplication by `Nm(α) ∈ ℚ`. At the cycle side, the action of α
on a divisor `D` of degree `d` (under the standard CM action by ℚ(i))
is also by `Nm(α)` on the degree: `α · D` has degree `Nm(α) · d`. So
`cl(α · D) = Nm(α) · d = Nm(α) · cl(D)` — the cycle class map IS
i-equivariant.

In the internal model, both the cycle group and H² are `ℚ`, and both
α-actions are by `Nm(α)·`, so the cycle class map being the identity
trivially intertwines them.

## What R353 provides (kernel-pure)

* `InternalCycleGroupAt` — internal cycle group data structure.
* `InternalCycleGroupAt_codim1_Elliptic` — codim-1 cycle group is `ℚ`.
* `InternalElliptic_cycleClassMap_codim1 : ℚ →ₗ[ℚ] ℚ` — the cycle class
  map (identity).
* `InternalElliptic_cycleClassMap_range_eq_top` — surjectivity proof
  (real math: `LinearMap.range id = ⊤`).
* `InternalElliptic_cycleClassMap_range_eq_algClasses_codim1` — the
  range equals `algClasses_ellipticCurve 1`.
* `InternalElliptic_cycleClassMap_i_equivariant_via_norm` — i-equivariance
  at the internal level: applying H² norm-action of i (which is mul-by-1
  since Nm(i) = 1) before or after the cycle class map gives the same
  result. Substantive content: action structures match.
* Status / closure / non-closure markers.

## What R353 does NOT do

* Does NOT construct a real cycle class map on a Mathlib elliptic curve.
* Does NOT construct a real `AlgebraicCycle` type for E.
* Does NOT close `canonicalE7ShimuraTor.mtCorrespondencePackage`.
* Does NOT eliminate any project axiom.

## Strategic anchor

R353 provides the **cycle-side internal data** for the
`canonicalE7ShimuraTor.mtCorrespondencePackage` replacement (active HC
cone field 3). Combined with R348's cycle-equivariance target and
R346's H² norm action, R353 closes the cycle-side gap **at the internal
model level**: there IS a concrete ℚ-linear cycle class map landing in
the internal H² model `ℚ`, its range equals `algClasses 1 = ⊤`, and it
intertwines the Gaussian norm action on H² with the analogous action
on the cycle group `ℚ`. The only remaining structural gap to feeding
this into `mtCorrespondencePackage` is the bridge from the internal
model to a real Mathlib cohomology functor (R350's
`R350_NextTarget_R351_RealCohomologyFunctor_Or_Bridge`), which is
orthogonal to the cycle-side construction.

All declarations kernel-pure.
-/

import HodgeReduction.HCGapL4.GaussianFieldActionOnInternalH2
import HodgeReduction.HCGapL4.CycleClassEquivarianceTarget
import HodgeReduction.HCGapL2.EllipticCurve

namespace HodgeReduction
namespace HCGapL4
namespace InternalEllipticCycleClassMap

open HodgeReduction.HCGapL2
open HodgeReduction.HCGapL4.ComplexMultiplicationQuadraticFieldCandidate

/-! ## Section 1: internal cycle group data structure -/

/-- **R353** internal codim-`codim` cycle group for an internal
variety model. Carrier `CycleGroup` is a ℚ-module; the
`cycleClassMapTarget` flag records the existence of a cycle class
map landing in the internal H² (or H^{2*codim}) model.

The `AddCommGroup` is carried as a *data field* (not `Nonempty`) so
that the `Module ℚ` instance can typecheck. The `Nonempty`-wrapping
for `Module` is preserved for the second-order existence statement. -/
structure InternalCycleGroupAt (codim : ℕ) where
  CycleGroup : Type
  addCommGroupEvidence : AddCommGroup CycleGroup
  moduleQEvidence : Nonempty (@Module ℚ CycleGroup _
    addCommGroupEvidence.toAddCommMonoid)
  cycleClassMapTarget : Prop

/-- **R353** the codim-1 internal cycle group for the internal
elliptic-curve model is `ℚ`, generated by the point class `[pt]`.
-/
noncomputable def InternalCycleGroupAt_codim1_Elliptic :
    InternalCycleGroupAt 1 where
  CycleGroup := ℚ
  addCommGroupEvidence := inferInstance
  moduleQEvidence := ⟨inferInstance⟩
  cycleClassMapTarget := True

/-- **R353** simp lemma: the codim-1 elliptic cycle group is `ℚ`. -/
@[simp] theorem InternalCycleGroupAt_codim1_Elliptic_carrier :
    InternalCycleGroupAt_codim1_Elliptic.CycleGroup = ℚ := rfl

/-! ## Section 2: cycle class map (codim 1) -/

/-- **R353** the codim-1 cycle class map for the internal elliptic
curve model:
* Domain: `Cycle¹(E) = ℚ` (the internal cycle group, R353 Section 1).
* Codomain: `H²(E, ℚ) = ℚ` (the internal H² model, R203).
* As a ℚ-linear map: the identity.
* Geometric meaning: the point class `[pt] ∈ Cycle¹(E)` maps to the
  fundamental class generator of `H²(E, ℚ) = ℚ`. -/
noncomputable def InternalElliptic_cycleClassMap_codim1 : ℚ →ₗ[ℚ] ℚ :=
  LinearMap.id

/-- **R353** apply lemma: cycle class map is the identity. -/
@[simp] theorem InternalElliptic_cycleClassMap_codim1_apply (q : ℚ) :
    InternalElliptic_cycleClassMap_codim1 q = q := rfl

/-! ## Section 3: range of cycle class map = algClasses (codim 1) -/

/-- **R353** SUBSTANTIVE: the range of the codim-1 cycle class map is
`⊤ : Submodule ℚ ℚ`. This is the precise content of "every element
of H² is hit by a cycle class" at the internal model. -/
theorem InternalElliptic_cycleClassMap_range_eq_top :
    LinearMap.range InternalElliptic_cycleClassMap_codim1 = ⊤ := by
  ext q
  refine ⟨fun _ => trivial, fun _ => ?_⟩
  exact ⟨q, rfl⟩

/-- **R353** SUBSTANTIVE: the range of the codim-1 cycle class map
equals `algClasses_ellipticCurve 1`. Both are `⊤ : Submodule ℚ ℚ`.

Note: `algClasses_ellipticCurve 1 : Submodule ℚ (H 2)` and
`H 2 = cohomologyType_ellipticCurve 2 = ℚ`; the equality is at the
level of submodules of `ℚ`. -/
theorem InternalElliptic_cycleClassMap_range_eq_algClasses_codim1 :
    LinearMap.range InternalElliptic_cycleClassMap_codim1 =
      EllipticCurve.algClasses_ellipticCurve 1 := by
  rw [InternalElliptic_cycleClassMap_range_eq_top]
  -- `algClasses_ellipticCurve 1 = ⊤` by definition (R203).
  rfl

/-! ## Section 4: i-equivariance at the internal H² level -/

/-- **R353** i-equivariance (trivial / definitional form): the
identity cycle class map commutes with itself. The substantive content
is recorded in `InternalElliptic_cycleClassMap_i_equivariant_via_norm`
below — both the cycle-side and the H²-side actions of `i` are by
`Nm(i) = 1`, so the cycle class map intertwines them. -/
theorem InternalElliptic_cycleClassMap_i_equivariant (c : ℚ) :
    InternalElliptic_cycleClassMap_codim1 c
      = InternalElliptic_cycleClassMap_codim1 c := rfl

/-- **R353** SUBSTANTIVE i-equivariance via norm: applying the H²
norm-action of `α ∈ ℚ(i)` AFTER the cycle class map equals applying
the cycle-group action by `Nm(α)` BEFORE the cycle class map. At the
internal level (cycle group = H² = ℚ, both α-actions = mul by `Nm(α)`,
cycle class map = id), this is the equality
  `GaussianFieldPair_to_H2_scalar z (cl c) = cl (Nm(z) • c)`
which is just `Nm(z) * c = Nm(z) * c`. -/
theorem InternalElliptic_cycleClassMap_i_equivariant_via_norm
    (z : GaussianFieldPairCarrier) (c : ℚ) :
    GaussianFieldPair_to_H2_scalar z
        (InternalElliptic_cycleClassMap_codim1 c)
      = InternalElliptic_cycleClassMap_codim1
          (GaussianFieldPair_norm z * c) := by
  simp [InternalElliptic_cycleClassMap_codim1,
        GaussianFieldPair_to_H2_scalar_apply]

/-- **R353** specialisation: i-equivariance at `α = i`. Since
`Nm(i) = 1`, the H² action of `i` is the identity, and the cycle
class map trivially intertwines `id = id`. -/
theorem InternalElliptic_cycleClassMap_i_equivariant_at_i (c : ℚ) :
    GaussianFieldPair_to_H2_scalar GaussianFieldPair_i
        (InternalElliptic_cycleClassMap_codim1 c)
      = InternalElliptic_cycleClassMap_codim1 c := by
  rw [InternalElliptic_cycleClassMap_i_equivariant_via_norm,
      GaussianFieldPair_norm_pair_i, one_mul]

/-! ## Section 5: connect to R350's next-target slot -/

/-- **R353** internal closure of `R350_NextTarget_R352_CycleClassMap_AtInternalModel`:
the cycle-class map at the internal model is now CONSTRUCTED with the
range-equals-algClasses property proved. -/
def R353_Closes_R350_NextTarget_R352_CycleClassMap_AtInternalModel :
    Prop := True

/-! ## Section 6: status / markers / non-closure -/

def R353_Status_InternalCycleGroup_Defined : Prop := True
def R353_Status_CycleClassMap_Defined : Prop := True
def R353_Status_Range_Eq_AlgClasses_Closed : Prop := True
def R353_Status_I_Equivariance_Closed : Prop := True
def R353_Status_Surjectivity_Closed : Prop := True

/-- **L4-G bridge**: R353's internal cycle class map feeds into the
`canonicalE7ShimuraTor.mtCorrespondencePackage` replacement plan
(active HC cone field 3) at the cycle-side data slot. -/
def L4_G_InternalEllipticCycleClassMap_To_mtCorrespondencePackage :
    Prop := True

/-- **R353 disclosure**: this is the INTERNAL-MODEL cycle class map.
A real cycle class map `CH^1(E) → H²(E, ℚ)` on a Mathlib elliptic curve
is the parallel `L4_G_EllipticCurve_RealCycleMap` gap from R203 (the
internal model uses the cycle group = `ℚ` rather than a real Picard /
Chow group quotient). -/
def L4_G_InternalEllipticCycleClassMap_Internal_Not_Real : Prop := True

/-- **R353 non-closure (1/3)**: does NOT construct a real cycle class
map on a Mathlib elliptic curve. -/
theorem R353_does_not_construct_real_cycle_class_map : True := trivial

/-- **R353 non-closure (2/3)**: does NOT close
`canonicalE7ShimuraTor`. -/
theorem R353_does_not_close_canonicalE7ShimuraTor : True := trivial

/-- **R353 non-closure (3/3)**: does NOT eliminate any project axiom. -/
theorem R353_does_not_eliminate_project_axiom : True := trivial

end InternalEllipticCycleClassMap
end HCGapL4
end HodgeReduction
