import HodgeReduction.HCGapL4.GenericCycleActionMultiStep
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.GenericCycleActionMultiStep
open HodgeReduction

#print axioms SHSM2_point_to_E_from_internalCycleAction_via_compose3
#print axioms VarietyHCAt_ellipticCurve_codim1_via_internalCycleAction_compose3
#print axioms VarietyHCAt_of_internalCycleAction_SHSM2_composed3
#print axioms R222_does_not_close_mtCorrespondencePackage
#print axioms R222_does_not_implement_real_chow_functoriality
#print axioms R222_does_not_implement_real_product_cycle_provenance
#print axioms R222_only_verifies_factory_multistep_integration
#print axioms hodgeConjectureReal_canonical
