import HodgeReduction.HCGapL4.ProductCohomologyProjectiveLineSelf
import HodgeReduction.HCGapL4.ProductCycleFactoryProjectiveLineSelf
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.ProductCohomologyProjectiveLineSelf
open HodgeReduction.HCGapL4.ProductCycleFactoryProjectiveLineSelf
open HodgeReduction

#print axioms VarietyCohomologyData_projectiveLineSelf
#print axioms projectiveLineSelfCycleClassFamily
#print axioms AlgebraicClassesData_projectiveLineSelf
#print axioms cycleAction_H0_to_H0_pointToProjectiveLine
#print axioms cycleAction_H0_to_H2_projectiveLineSelf
#print axioms internalCycleActionData_SHSM_WithProductCycle_point_to_projectiveLine_codim0_to_codim0
#print axioms internalCycleActionData_SHSM_WithProductCycle_projectiveLine_self_codim0_to_codim1
#print axioms SHSM2_point_to_projectiveLine_via_two_nontrivial_productCycleFactories
#print axioms VarietyHCAt_projectiveLine_codim1_via_two_nontrivial_productCycleFactories
#print axioms R227_does_not_close_mtCorrespondencePackage
#print axioms R227_does_not_implement_true_chow_composition
#print axioms R227_does_not_prove_cycles_induce_actions
#print axioms R227_only_two_nontrivial_factory_SHSM2_chain
#print axioms hodgeConjectureReal_canonical
