import HodgeReduction.HCGapL4.E7ShimuraToyCarrier
import HodgeReduction.HCGapL4.ProductCohomologyPointTimesE7ShimuraToy
import HodgeReduction.HCGapL4.E7ShimuraToyProductCycleFactory
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.E7ShimuraToyCarrier
open HodgeReduction.HCGapL4.ProductCohomologyPointTimesE7ShimuraToy
open HodgeReduction.HCGapL4.E7ShimuraToyProductCycleFactory
open HodgeReduction

#print axioms VarietyCohomologyData_E7ShimuraToy
#print axioms AlgebraicClassesData_E7ShimuraToy
#print axioms VarietyCohomologyData_pointTimesE7ShimuraToy
#print axioms pointTimesE7ShimuraToyCycleClassFamily
#print axioms AlgebraicClassesData_pointTimesE7ShimuraToy
#print axioms cycleAction_H0_point_to_H2_E7ShimuraToy
#print axioms internalCycleActionData_SHSM_WithProductCycle_point_to_E7ShimuraToy
#print axioms SHSM2_point_to_E7ShimuraToy_from_productCycleFactory
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_productCycleFactory
#print axioms R229_does_not_close_canonicalE7ShimuraTor
#print axioms R229_does_not_alter_hodgeConjectureReal_canonical
#print axioms R229_does_not_claim_real_E7Shimura
#print axioms R229_does_not_implement_real_chow_or_V56
#print axioms R229_only_first_E7ShimuraToy_factory_route
#print axioms hodgeConjectureReal_canonical
