import HodgeReduction.HCGapL4.E7ShimuraToyMTCorrespondencePackage
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.E7ShimuraToyMTCorrespondencePackage
open HodgeReduction

#print axioms E7ShimuraToy_MTCorrespondencePackageSkeleton
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_MTCorrespondencePackageSkeleton
#print axioms E7ShimuraToy_WithMTCorrespondencePackageSkeleton
#print axioms VarietyHCAt_E7ShimuraToyWithMTCorrespondencePackageSkeleton_codim1
#print axioms R235_does_not_close_canonicalE7ShimuraTor
#print axioms R235_does_not_implement_real_mtCorrespondencePackage
#print axioms R235_does_not_implement_real_chow_correspondence
#print axioms R235_does_not_implement_real_shimura_datum
#print axioms R235_does_not_implement_real_mumford_tate
#print axioms R235_does_not_prove_cm_abelian_hodge_conjecture
#print axioms R235_does_not_identify_toy_with_real_E7Shimura
#print axioms hodgeConjectureReal_canonical
