import HodgeReduction.HCGapL4.CMAbelianToySkeleton
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.CMAbelianToySkeleton
open HodgeReduction

#print axioms CMAbelianVarietyToySkeleton_ellipticCurveLike
#print axioms cycleAction_H2_ellipticCurve_to_H2_E7ShimuraToy
#print axioms internalCycleActionData_SHSM_ellipticCurve_to_E7ShimuraToy
#print axioms SHSM2_ellipticCurve_to_E7ShimuraToy_codim1_to_codim1
#print axioms E7ShimuraToy_MTCorrespondencePackageFromCMAbelianToySkeleton
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_CMAbelianToy_MTCorrespondencePackageSkeleton
#print axioms R236_does_not_close_canonicalE7ShimuraTor
#print axioms R236_does_not_implement_real_cm_abelian_variety
#print axioms R236_does_not_prove_deligne_1982
#print axioms R236_does_not_implement_cm_endomorphisms
#print axioms R236_does_not_implement_abelian_variety_structure
#print axioms R236_does_not_identify_toy_with_real_E7Shimura
#print axioms R236_does_not_replace_R235_point_source_package
#print axioms hodgeConjectureReal_canonical
