import HodgeReduction.HCGapL4.CMAbelianToyProductCycleToE7ShimuraToy
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.CMAbelianToyProductCycleToE7ShimuraToy
open HodgeReduction

#print axioms VarietyCohomologyData_ellipticCurveTimesE7ShimuraToy
#print axioms ellipticCurveTimesE7ShimuraToyCycleClassFamily
#print axioms AlgebraicClassesData_ellipticCurveTimesE7ShimuraToy
#print axioms internalCycleActionData_SHSM_WithProductCycle_ellipticCurve_to_E7ShimuraToy
#print axioms SHSM2_ellipticCurve_to_E7ShimuraToy_from_CMProductCycleFactory
#print axioms E7ShimuraToy_MTCorrespondencePackageFromCMAbelianToyWithProductCycleSkeleton
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_CMAbelianToy_ProductCycle_MTCorrespondencePackageSkeleton
#print axioms R237_does_not_close_canonicalE7ShimuraTor
#print axioms R237_does_not_implement_real_cm_abelian_variety
#print axioms R237_does_not_prove_deligne_1982
#print axioms R237_does_not_implement_true_chow_correspondence
#print axioms R237_does_not_prove_cycle_induces_action
#print axioms R237_does_not_implement_true_ellipticCurve_times_E7Shimura
#print axioms R237_does_not_identify_toy_with_real_E7Shimura
#print axioms hodgeConjectureReal_canonical
