import HodgeReduction.HCGapL4.E7ShimuraToyMTCorrespondenceRealization
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.E7ShimuraToyMTCorrespondenceRealization
open HodgeReduction

#print axioms VarietyHCAt_E7ShimuraToy_codim1_of_MTCorrespondenceRealizationSkeleton
#print axioms E7ShimuraToy_MTRealizationSkeleton_pointSource
#print axioms E7ShimuraToy_MTRealizationSkeleton_CMSourceDirect
#print axioms E7ShimuraToy_MTRealizationSkeleton_CMSourceProductCycle
#print axioms E7ShimuraToy_MTRealizationSkeleton_CMChain
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_v3_pointSource
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_v3_CMSourceDirect
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_v3_CMSourceProductCycle
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_v3_CMChain
#print axioms R239_does_not_close_canonicalE7ShimuraTor
#print axioms R239_does_not_implement_real_mtCorrespondencePackage
#print axioms R239_does_not_implement_true_chow_correspondence
#print axioms R239_does_not_prove_deligne_1982
#print axioms R239_does_not_identify_toy_with_real_E7Shimura
#print axioms R239_only_unifies_existing_realization_patterns
#print axioms hodgeConjectureReal_canonical
