import HodgeReduction.HCGapL4.E7ShimuraTorToyContainer
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.E7ShimuraTorToyContainer
open HodgeReduction

#print axioms E7ShimuraTorToyContainerSkeleton_canonicalToy
#print axioms VarietyHCAt_E7ShimuraTorToyContainerSkeleton_codim1
#print axioms E7ShimuraTorToyToRealGapSkeleton_current
#print axioms R243_does_not_close_canonicalE7ShimuraTor
#print axioms R243_does_not_replace_canonicalE7ShimuraTor
#print axioms R243_does_not_change_hodgeConjectureReal_canonical
#print axioms R243_does_not_implement_real_E7_shimura_variety
#print axioms R243_does_not_implement_real_chow_groups
#print axioms R243_does_not_implement_real_mt_correspondence_package
#print axioms R243_only_mirrors_proof_cone_shape_in_toy_form
#print axioms hodgeConjectureReal_canonical
