import HodgeReduction.HCGapL4.MTCorrespondenceMathlibAudit
import HodgeReduction.HCGapL4.MTCorrespondenceReplacementDependencyMap
import HodgeReduction.HCGapL4.MTCorrespondenceReplacementNextTarget
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.MTCorrespondenceMathlibAudit
open HodgeReduction.HCGapL4.MTCorrespondenceReplacementDependencyMap
open HodgeReduction.HCGapL4.MTCorrespondenceReplacementNextTarget
open HodgeReduction

-- R254
#print axioms MTCorrespondenceMathlibAuditToySkeleton_current
#print axioms AuditMissing_AbelianVarietyBundle
#print axioms AuditMissing_ComplexMultiplicationStructure
#print axioms AuditMissing_AbelianVarietyEndomorphismAlgebra
#print axioms AuditMissing_AlgebraicGroupBundle
#print axioms AuditMissing_AlgebraicTorus
#print axioms AuditMissing_MumfordTateGroupModule
#print axioms AuditMissing_ChowGroupModule
#print axioms AuditMissing_AlgebraicCorrespondenceModule
#print axioms AuditMissing_WeilRestrictionOfSchemes
#print axioms AuditMissing_MotiveCategory
#print axioms AuditMissing_AlbanesePicardScheme

-- R255
#print axioms MTCorrespondenceReplacementDependencyMapToySkeleton_E7Shimura
#print axioms MTCorrespondenceReplacementRouteCMSourceToySkeleton_marker
#print axioms MTCorrespondenceReplacementRouteChowCorrespondenceToySkeleton_marker
#print axioms MTCorrespondenceReplacementRouteMumfordTateToySkeleton_marker
#print axioms MTCorrespondenceReplacementRouteMotivicFactorizationToySkeleton_marker
#print axioms MTCorrespondenceReplacementRecommendedFirstRouteToy

-- R256
#print axioms MTCorrespondenceReplacementNextTargetToySkeleton_chosen
#print axioms Target_AbstractCMAbelianHCSource_PlusMTCorrespondenceAdapter
#print axioms L4_G_NextMTCorrespondenceReplacementTarget_To_R247Plan
#print axioms VarietyHCAt_of_AbstractCMAbelianHCSource_and_MTCorrespondence
#print axioms AbstractCMAbelianHCSource_fromR236_ECbased
#print axioms AbstractMTCorrespondenceToTarget_R236_ECtoE7ShimuraToy
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_AbstractCMSourceInterface

-- Headline guard
#print axioms hodgeConjectureReal_canonical
