import HodgeReduction.HCGapL4.AbelianVarietyInterface
import HodgeReduction.HCGapL4.ComplexMultiplicationInterface
import HodgeReduction.HCGapL4.Deligne1982BoundaryInterface
import HodgeReduction.HCGapL4.CMSourceReplacementBridge
import HodgeReduction.HCGapL4.CMSourceBridgeNextTarget
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.AbelianVarietyInterface
open HodgeReduction.HCGapL4.ComplexMultiplicationInterface
open HodgeReduction.HCGapL4.Deligne1982BoundaryInterface
open HodgeReduction.HCGapL4.CMSourceReplacementBridge
open HodgeReduction.HCGapL4.CMSourceBridgeNextTarget
open HodgeReduction

-- R260
#print axioms EllipticCurveAsAbelianVarietyInterfaceSkeleton
#print axioms EllipticCurveAsAbelianVarietyHCSourceInterfaceSkeleton
#print axioms AbstractCMAbelianHCSource_of_AbelianVarietyHCSourceInterface
#print axioms AbstractCMAbelianHCSource_from_EllipticCurveAVInterface
#print axioms L4_G_AbelianVarietyInterface_To_RealMathlibAbelianVariety
#print axioms L4_G_AbelianVarietyInterface_MissingGroupScheme
#print axioms L4_G_AbelianVarietyInterface_MissingProjectiveSmoothProperProof
#print axioms L4_G_AbelianVarietyInterface_To_AbstractCMAbelianHCSource

-- R261
#print axioms CMAbelianVarietyInterfaceSkeleton_ellipticCurveLike
#print axioms AbstractCMAbelianHCSource_of_CMAbelianVarietyInterface
#print axioms AbstractCMAbelianHCSource_from_CMAbelianVarietyInterface_ellipticCurveLike
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_CMAbelianVarietyInterface_ellipticCurveLike
#print axioms L4_G_CMInterface_To_RealComplexMultiplication
#print axioms L4_G_CMInterface_MissingEndomorphismAlgebra
#print axioms L4_G_CMInterface_MissingCMFieldDegreeCondition
#print axioms L4_G_CMInterface_To_Deligne1982

-- R262
#print axioms Deligne1982HCInterfaceSkeleton_ellipticCurveRegression
#print axioms AbstractCMAbelianHCSource_of_Deligne1982HCInterface
#print axioms AbstractCMAbelianHCSource_from_Deligne1982BoundaryInterface_ellipticCurveRegression
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_Deligne1982BoundaryInterface_regression
#print axioms Target_Library_Deligne1982_HC_For_CMAbelianVarieties
#print axioms L4_G_Deligne1982BoundaryInterface_To_ExternalLibraryTheorem
#print axioms L4_G_Deligne1982BoundaryInterface_MissingProof
#print axioms L4_G_Deligne1982BoundaryInterface_To_AbstractCMAbelianHCSource
#print axioms L4_G_Deligne1982BoundaryInterface_To_mtCorrespondencePackage

-- R263
#print axioms CMSourceReplacementBridgeSkeleton_ellipticCurveRegression
#print axioms L4_G_CMSourceReplacementBridge_To_MTCorrespondenceReplacementPlan
#print axioms AbstractHCDataWithMTTransfer_E7ShimuraToy_from_CMSourceBridge
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_CMSourceReplacementBridge
#print axioms L4_G_CMSourceReplacementBridge_To_RealCMAbelianVariety
#print axioms L4_G_CMSourceReplacementBridge_To_Deligne1982
#print axioms L4_G_CMSourceReplacementBridge_To_canonicalE7ShimuraTor_mtCorrespondencePackage
#print axioms L4_G_CMSourceReplacementBridge_MissingActualAbelianVariety

-- R264
#print axioms CMSourceBridgeNextTargetSkeleton_chosen
#print axioms Target_AbelianVarietyInterfaceFromEllipticCurveGroup
#print axioms Target_CMEndomorphismAlgebraInterfaceForEllipticCurve
#print axioms CMSourceBridgeRecommendedNextTarget

-- Headline guard
#print axioms hodgeConjectureReal_canonical
