import HodgeReduction.HCGapL4.AbelianVarietyInterfaceECProjectiveRealization
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.AbelianVarietyInterfaceECProjectiveRealization
open HodgeReduction

-- R265-B
#print axioms ellipticCurve_projectivePoint_type_available
#print axioms ellipticCurve_projectivePoint_has_addCommGroup
#print axioms ellipticCurve_projective_affine_addEquiv
#print axioms EllipticCurveProjectiveModelEvidenceSkeleton_Q
#print axioms AuditMissing_EllipticCurve_ProjectiveModelAsProjectiveScheme
#print axioms EllipticCurveAsAbelianVarietyInterfaceSkeleton_RealizedGroupLaw_Projective_instance
#print axioms AbstractCMAbelianHCSource_from_EllipticCurveRealizedGroupLawProjectiveInterface
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_ECRealizedGroupLawProjectiveInterface
#print axioms L4_G_ECProjectiveEvidence_To_AbelianVarietyInterface
#print axioms L4_G_ECProjectiveEvidence_MissingProjectiveSchemeProof
#print axioms L4_G_ECProjectiveEvidence_MissingClosedEmbeddingIntoProjectivePlane
#print axioms L4_G_ECProjectiveEvidence_MissingSmoothProperProof
#print axioms L4_G_ECProjectiveEvidence_To_CMSourceBridge

-- Headline guard
#print axioms hodgeConjectureReal_canonical
