import HodgeReduction.HCGapL4.ComplexMultiplicationInterfaceECRealization
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4.ComplexMultiplicationInterfaceECRealization
open HodgeReduction

-- R266
#print axioms rationalEndomorphismAlgebraEvidence_for_EC_CMInterface_proved
#print axioms rationalEndomorphismAlgebra_has_QAlgebraEvidence_proved
#print axioms ellipticCurve_H1_has_QModule_for_CMInterface
#print axioms ellipticCurve_H2_has_QModule_for_CMInterface
#print axioms EllipticCurveCMInterfacePartialRealizationSkeleton_instance
#print axioms AbstractCMAbelianHCSource_from_EllipticCurveCMPartialRealization
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_EllipticCurveCMPartialRealization
#print axioms L4_G_ECCMPartialRealization_To_CMInterface
#print axioms L4_G_ECCMPartialRealization_RationalEndomorphismAlgebraOnly
#print axioms L4_G_ECCMPartialRealization_MissingActualCMField
#print axioms L4_G_ECCMPartialRealization_MissingRankCondition
#print axioms L4_G_ECCMPartialRealization_MissingTrueEnd0

-- Headline guard
#print axioms hodgeConjectureReal_canonical
