import HodgeReduction.HCGapL4.CMFieldInterfaceSkeleton
import HodgeReduction.HCGapL4.GaussianRationalNumberFieldTarget
import HodgeReduction.HCGapL4.ImaginaryQuadraticFieldInterfaceSkeleton
import HodgeReduction.HCGapL4.EllipticCurveEnd0ActionBoundary
import HodgeReduction.HCGapL4.CMFieldSequenceStoppingAudit
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R268
#print axioms CMFieldInterfaceData_GaussianCandidate
#print axioms CMFieldInterfaceEvidenceData_GaussianCandidate
#print axioms EllipticCurveCMInterfaceWithCMFieldCandidateBundle_instance
#print axioms AbstractCMAbelianHCSource_from_EllipticCurveCMFieldCandidateInterface
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_EllipticCurveCMFieldCandidateInterface
#print axioms L4_G_CMFieldInterfaceSkeleton_To_MathlibCMField
#print axioms L4_G_CMFieldInterfaceSkeleton_GaussianCandidate_To_ImaginaryQuadraticField
#print axioms L4_G_CMFieldInterfaceSkeleton_MissingNumberFieldInstance
#print axioms L4_G_CMFieldInterfaceSkeleton_MissingEnd0Action
#print axioms L4_G_CMFieldInterfaceSkeleton_To_Deligne1982

-- R269
#print axioms AuditStillMissing_GaussianRationalFieldCandidate_NumberFieldInstance
#print axioms gaussianIntI
#print axioms GaussianRationalNumberFieldTargetSkeleton_current
#print axioms Target_GaussianRationalFieldCandidate_basis_one_I
#print axioms Target_GaussianRationalFieldCandidate_finiteDimensional_over_Q
#print axioms Target_GaussianRationalFieldCandidate_finrank_eq_two
#print axioms CMFieldInterfaceWithNumberFieldTargetSkeleton_Gaussian
#print axioms L4_G_GaussianNumberFieldTarget_To_NumberFieldInstance
#print axioms L4_G_GaussianNumberFieldTarget_To_FiniteDimensionalProof
#print axioms L4_G_GaussianNumberFieldTarget_To_BasisOneI
#print axioms L4_G_GaussianNumberFieldTarget_To_CMFieldInterface

-- R270
#print axioms gaussianInt_has_StarRing
#print axioms AuditMissing_GaussianRationalFieldCandidate_StarRing
#print axioms ImaginaryQuadraticFieldInterfaceSkeleton_Gaussian
#print axioms EllipticCurveCMInterfaceWithImaginaryQuadraticCandidateSkeleton_instance
#print axioms AbstractCMAbelianHCSource_from_EllipticCurveImaginaryQuadraticCandidate
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_EllipticCurveImaginaryQuadraticCandidate
#print axioms L4_G_ImaginaryQuadraticFieldInterface_To_CMField
#print axioms L4_G_ImaginaryQuadraticFieldInterface_MissingNumberFieldProof
#print axioms L4_G_ImaginaryQuadraticFieldInterface_MissingConjugation
#print axioms L4_G_ImaginaryQuadraticFieldInterface_MissingEmbeddingIntoC
#print axioms L4_G_ImaginaryQuadraticFieldInterface_MissingEnd0Action

-- R271
#print axioms EllipticCurveEnd0ActionBoundarySkeleton_Gaussian
#print axioms EllipticCurveCMInterfaceWithEnd0BoundarySkeleton_instance
#print axioms AbstractCMAbelianHCSource_from_EllipticCurveEnd0Boundary
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_EllipticCurveEnd0Boundary
#print axioms L4_G_End0ActionBoundary_To_RealEnd0EllipticCurve
#print axioms L4_G_End0ActionBoundary_To_GaussianCMAction
#print axioms L4_G_End0ActionBoundary_MissingEndomorphismRing
#print axioms L4_G_End0ActionBoundary_MissingTensorWithQ
#print axioms L4_G_End0ActionBoundary_MissingCohomologyAction

-- R272
#print axioms CMFieldSequenceStoppingAuditSkeleton_current
#print axioms R272_RecommendedStopCondition_R26x_CMFieldPath
#print axioms R272_RecommendedNextBranch_ChowOrTopLevel
#print axioms R272_AlternativeNextBranch_MathlibPRForNumberField
#print axioms R272_AlternativeNextBranch_MathlibPRForEnd0

-- Headline guard
#print axioms hodgeConjectureReal_canonical
