import HodgeReduction.HCGapL4.GaussianIntNormConjugate
import HodgeReduction.HCGapL4.GaussianIntActionNormConjugate
import HodgeReduction.HCGapL4.GaussianIntActionInvertibility
import HodgeReduction.HCGapL4.GaussianFieldLocalizationTarget
import HodgeReduction.HCGapL4.MTCorrespondenceAfterInvertibility
import HodgeReduction.HCGapL4.HCFrontierAfterInvertibility
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R327: GaussianInt norm/conjugate
#print axioms gaussianIntNormInt
#print axioms gaussianIntNormInt_nonneg
#print axioms gaussianIntNormInt_eq_zero_iff
#print axioms gaussianInt_mul_star_eq_norm
#print axioms gaussianIntNormInt_pos_of_ne_zero
#print axioms gaussianIntNormQ_ne_zero_of_ne_zero

-- R328: action norm-conjugate
#print axioms pointEndHom_to_PointEndHomQ_mul_compat
#print axioms GaussianInt_to_PointEndHom_formula_intCast
#print axioms gaussianInt_action_mul_star_eq_norm_smul
#print axioms gaussianInt_action_mul_star_eq_normQ_smul

-- R329: invertibility
#print axioms gaussianInt_inverseAction
#print axioms GaussianInt_to_PointEndHomQ_eq_tmul
#print axioms gaussianInt_action_mul_inverseAction
#print axioms gaussianIntNormInt_star
#print axioms gaussianIntNormQ_star
#print axioms gaussianInt_inverseAction_mul_action

-- R330: localization target (markers only)
#print axioms Target_GaussianField_To_PointEndHomQ_via_localization
#print axioms BlockingLemma_R330_IsLocalization_lift_requires_CommRing

-- R331: mtCorrespondence bridge update
#print axioms MTCorrespondenceAfterInvertibilitySkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_MTCorrespondenceAfterInvertibility

-- R332: frontier audit
#print axioms HCFrontierAfterInvertibilitySkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_HCFrontierAfterInvertibility

-- Final-goal markers (axiom-free)
#print axioms R332_HC_FinalGoal_KernelOnly
#print axioms R332_CurrentProjectAxiom_canonicalE7ShimuraTor
#print axioms R332_ActiveField_mtCorrespondencePackage_UnderAttack
#print axioms R332_NextTarget_CommutativeSubring_Of_PointEndHomQ

-- Headline guard
#print axioms hodgeConjectureReal_canonical
