import HodgeReduction.HCGapL4.GaussianFieldSubringPointEndQ
import HodgeReduction.HCGapL4.GaussianFieldSubringCommRing
import HodgeReduction.HCGapL4.GaussianIntActionLandsInSubfield
import HodgeReduction.HCGapL4.GaussianFieldActionViaSubring
import HodgeReduction.HCGapL4.MTCorrespondenceAfterGaussianFieldAction
import HodgeReduction.HCGapL4.HCFrontierAfterGaussianFieldAction
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R333: commutative subspace
#print axioms GaussianFieldSubspace_PointEndQ
#print axioms pointEnd_id_Q_mem_GaussianFieldSubspace
#print axioms gaussianCM_phi_Q_mem_GaussianFieldSubspace
#print axioms linear_combination_mem_GaussianFieldSubspace
#print axioms mem_GaussianFieldSubspace_iff_exists
#print axioms GaussianFieldSubspace_mul_normal_form
#print axioms GaussianFieldSubspace_mul_mem
#print axioms GaussianFieldSubspace_mul_comm

-- R335: CommRing pair carrier
#print axioms GaussianFieldPairCarrier.instCommRing
#print axioms GaussianFieldPair_to_PointEndHomQ
#print axioms GaussianFieldPair_to_PointEndHomQ_zero
#print axioms GaussianFieldPair_to_PointEndHomQ_one
#print axioms GaussianFieldPair_to_PointEndHomQ_add
#print axioms GaussianFieldPair_to_PointEndHomQ_neg

-- R334: GaussianInt action lands in subspace
#print axioms GaussianInt_to_PointEndHomQ_mem_GaussianFieldSubspace
#print axioms GaussianInt_to_PointEndHomQ_normal_form

-- R336: pair embedding mul preservation
#print axioms GaussianFieldPair_to_PointEndHomQ_mul

-- R337: bridge update
#print axioms MTCorrespondenceAfterGaussianFieldActionSkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_MTCorrespondenceAfterGaussianFieldAction

-- R338: frontier audit
#print axioms HCFrontierAfterGaussianFieldActionSkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_HCFrontierAfterGaussianFieldAction

-- Final-goal markers (axiom-free)
#print axioms R338_HC_FinalGoal_KernelOnly
#print axioms R338_canonicalE7ShimuraTor_StillOnlyProjectAxiom
#print axioms R338_mtCorrespondencePackage_SourceSideProgress
#print axioms R338_NextTarget_CohomologyAction

-- Headline guard
#print axioms hodgeConjectureReal_canonical
