import HodgeReduction.HCGapL4.GaussianFieldActionOnInternalH1
import HodgeReduction.HCGapL4.GaussianFieldActionOnInternalH2
import HodgeReduction.HCGapL4.HodgeDecompositionCompatibility
import HodgeReduction.HCGapL4.CycleClassEquivarianceTarget
import HodgeReduction.HCGapL4.MTCorrespondenceAfterCohomologyAction
import HodgeReduction.HCGapL4.HCFrontierAfterCohomologyAction
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R345: internal H¹ action
#print axioms GaussianFieldPair_to_H1LinearMap
#print axioms GaussianFieldPair_to_H1LinearMap_one
#print axioms GaussianFieldPair_to_H1LinearMap_add
#print axioms GaussianFieldPair_to_H1LinearMap_mul
#print axioms GaussianFieldPair_to_H1LinearMap_i_sq
#print axioms GaussianField_to_H1LinearMap
#print axioms GaussianField_to_H1LinearMap_map_one
#print axioms GaussianField_to_H1LinearMap_map_add
#print axioms GaussianField_to_H1LinearMap_map_mul

-- R346: H² action via norm
#print axioms GaussianFieldPair_norm
#print axioms GaussianFieldPair_norm_mul
#print axioms GaussianFieldPair_to_H2_scalar
#print axioms GaussianFieldPair_to_H2_scalar_one
#print axioms GaussianFieldPair_to_H2_scalar_mul
#print axioms GaussianField_to_H2_scalar
#print axioms GaussianField_to_H2_scalar_one
#print axioms GaussianField_to_H2_scalar_mul

-- R347: Hodge minimal polynomial
#print axioms GaussianFieldPair_to_H1LinearMap_pair_i_min_poly
#print axioms GaussianField_to_H1LinearMap_gaussianRationalI_min_poly

-- R348: cycle class equivariance target (markers)
#print axioms Target_R348_CycleClassMap_Exists
#print axioms BlockingLemma_R348_Mathlib_No_CycleClassMap_For_EllipticCurves

-- R349: bridge update
#print axioms MTCorrespondenceAfterCohomologyActionSkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_MTCorrespondenceAfterCohomologyAction

-- R350: frontier audit
#print axioms HCFrontierAfterCohomologyActionSkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_HCFrontierAfterCohomologyAction

-- Final-goal markers (axiom-free)
#print axioms R350_HC_FinalGoal_KernelOnly
#print axioms R350_canonicalE7ShimuraTor_StillOnlyProjectAxiom
#print axioms R350_mtCorrespondencePackage_SourceSideProgress
#print axioms R350_NextTarget_Bridge_InternalToRealCohomology

-- Headline guard
#print axioms hodgeConjectureReal_canonical
