import HodgeReduction.HCGapL4.EllipticCurveCohomologyRealizationAudit
import HodgeReduction.HCGapL4.InternalMTCorrespondencePackage
import HodgeReduction.HCGapL4.InternalEllipticCycleClassMap
import HodgeReduction.HCGapL4.InternalMTPackageWithCycleData
import HodgeReduction.HCGapL4.E7ToCMCorrespondenceTargetRefined
import HodgeReduction.HCGapL4.HCFrontierAfterInternalMTPackage
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R351: Mathlib audit
#print axioms R351_AuditResult_current
#print axioms R351_Decision_Use_Internal_Model_Fallback

-- R352: internal MT package
#print axioms HodgeReduction.HCGapL4.InternalMTCorrespondencePackage.InternalCMSourceMTData_GaussianElliptic

-- R353: internal cycle class map
#print axioms HodgeReduction.HCGapL4.InternalEllipticCycleClassMap.InternalCycleGroupAt_codim1_Elliptic
#print axioms HodgeReduction.HCGapL4.InternalEllipticCycleClassMap.InternalElliptic_cycleClassMap_codim1
#print axioms HodgeReduction.HCGapL4.InternalEllipticCycleClassMap.InternalElliptic_cycleClassMap_range_eq_top
#print axioms HodgeReduction.HCGapL4.InternalEllipticCycleClassMap.InternalElliptic_cycleClassMap_i_equivariant_via_norm

-- R354: combined package
#print axioms InternalCMSourceWithCycleAndCohomologyPackage_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_InternalMTPackageWithCycleData

-- R355: E7-to-CM target refinement
#print axioms E7ToCMCorrespondenceTargetRefined_current
#print axioms MTCorrespondenceGapAfterInternalSourceClosure_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_E7ToCMCorrespondenceTargetRefined

-- R356: frontier audit
#print axioms HCFrontierAfterInternalMTPackageSkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_HCFrontierAfterInternalMTPackage

-- Final-goal markers (axiom-free)
#print axioms R356_HC_FinalGoal_KernelOnly
#print axioms R356_canonicalE7ShimuraTor_StillOnlyProjectAxiom
#print axioms R356_mtCorrespondencePackage_SourceSideMostlyClosed
#print axioms R356_NextTarget_E7ToCMCorrespondence

-- Headline guard
#print axioms hodgeConjectureReal_canonical
