import HodgeReduction.HCGapL4.InternalE7ToCMMTPackageAt
import HodgeReduction.HCGapL4.MTCorrespondenceAfterInternalE7ToCMPackage
import HodgeReduction.HCGapL4.HCFrontierAfterInternalMTPackageAtClosure
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R360 internal MTPackageAt HC transfer
#print axioms InternalE7ToCM_MTPackage_HC_Transfer_codim1
#print axioms InternalE7ToCM_MTPackage_codim1

-- R361 bridge update
#print axioms MTCorrespondenceAfterInternalE7ToCMPackageSkeleton_current
#print axioms MTCorrespondenceRemainingGapsAfterInternalE7ToCM_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_MTCorrespondenceAfterInternalE7ToCMPackage

-- R362 frontier audit
#print axioms HCFrontierAfterInternalMTPackageAtClosureSkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_HCFrontierAfterInternalMTPackageAtClosure

-- Final-goal markers (axiom-free)
#print axioms R362_HC_FinalGoal_KernelOnly
#print axioms R362_Internal_mtCorrespondencePackageAt_Closed
#print axioms R362_canonicalE7ShimuraTor_StillOnlyProjectAxiom
#print axioms R362_NextTarget_TrueE7ToCMCorrespondence_Or_InternalToRealBridge
#print axioms R362_HonestPosition_Internal_Closed_Real_Open

-- Headline guard
#print axioms hodgeConjectureReal_canonical
