import HodgeReduction.HCGapL4.InternalToRealCohomologyBridge
import HodgeReduction.HCGapL4.InternalToRealChowBridge
import HodgeReduction.HCGapL4.CanonicalE7ShimuraTorReplacementInterface
import HodgeReduction.HCGapL4.HCFrontierAfterBridgeInterface
import HodgeReduction.MainTheorem

open HodgeReduction.HCGapL4
open HodgeReduction

-- R363 cohomology bridge
#print axioms InternalToRealCohomologyBridge_E7ShimuraToy
#print axioms InternalToRealCohomologyBridge_GaussianCMSource

-- R364 Chow bridge
#print axioms InternalToRealChowBridge_E7ShimuraToy
#print axioms InternalToRealChowBridge_GaussianCMSource
#print axioms InternalCycleMapToRealChowBridge_current

-- R365 canonical replacement interface
#print axioms CanonicalE7ShimuraTorReplacementInterface_internalCurrent
#print axioms R365_internal_replacement_interface_available

-- R366 frontier audit
#print axioms HCFrontierAfterBridgeInterfaceSkeleton_current
#print axioms VarietyHCAt_E7ShimuraToy_codim1_via_HCFrontierAfterBridgeInterface

-- Final-goal markers (axiom-free)
#print axioms R366_HC_FinalGoal_KernelOnly
#print axioms R366_canonicalE7ShimuraTor_StillOnlyProjectAxiom
#print axioms R366_InternalReplacementInterface_Available
#print axioms R366_NextTarget_FieldwiseReplacementOrRealBridge
#print axioms R366_HonestPosition_Interface_Available_Refactor_Not_Authorized

-- Headline guard
#print axioms hodgeConjectureReal_canonical
