/-
Copyright (c) 2026 Alex Chengyu Li. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.GroupTheory.Coxeter.Basic
import Mathlib.GroupTheory.Coxeter.Matrix
import Mathlib.Algebra.Module.Submodule.Basic
import Mathlib.Algebra.Group.Submonoid.Basic
import Mathlib.Algebra.Module.LinearMap.Defs
import HodgeReduction.Infrastructure.CartanMatrices
import HodgeReduction.Infrastructure.CoxeterDegrees

/-!
# The Weyl group `W(E_7)` via Mathlib's Coxeter framework

Connects `CartanMatrices.lean` + `CoxeterDegrees.lean` with Mathlib's
Coxeter framework (`CoxeterMatrix.E₇`, `CoxeterMatrix.group`). Adds
substantive typeclasses:

* `WeylGroupActionData W V` — `action : W →* (V →ₗ[ℚ] V)` plus
  reflection-group existential generation axiom.
* `WE7CoxeterPresentationData` — `s : Fin 7 → W` simple reflections
  with substantive Coxeter relations.
* `WE7InvariantsData` — substantive `W(E_7)`-invariant `Submodule ℚ V`.

## References

* N. Bourbaki, *Groupes et algèbres de Lie*, Ch. VI Planche VI
  (Hermann 1968).
* J. E. Humphreys, *Reflection Groups and Coxeter Groups*, CUP 1990,
  §2.13.
* R. W. Carter, *Simple Groups of Lie Type*, Wiley 1972, §13.2.
* C. Chevalley, "Invariants of finite groups generated by
  reflections", *Amer. J. Math.* **77** (1955), 778-782.

## Tags

Coxeter group, Weyl group, E_7, Dynkin diagram, reflection
representation, invariant ring, Chevalley-Shephard-Todd
-/

namespace HodgeReduction.Infrastructure

open CoxeterMatrix

/-- The (abstract) Coxeter group `W(E_7)`, defined via Mathlib's
`CoxeterMatrix.E₇`. -/
def WE7 : Type := CoxeterMatrix.Group (E₇ : CoxeterMatrix (Fin 7))

/-- `WE7` is a group (inheriting from Mathlib's `CoxeterMatrix.Group`). -/
instance : Group WE7 := inferInstanceAs (Group (CoxeterMatrix.Group _))

/-- The Coxeter matrix of `WE7` is the standard `E₇` matrix from Mathlib. -/
theorem WE7.coxeterMatrix_def :
    (CoxeterMatrix.E₇ : CoxeterMatrix (Fin 7)).M =
      !![1, 2, 3, 2, 2, 2, 2;
         2, 1, 2, 3, 2, 2, 2;
         3, 2, 1, 3, 2, 2, 2;
         2, 3, 3, 1, 3, 2, 2;
         2, 2, 2, 3, 1, 3, 2;
         2, 2, 2, 2, 3, 1, 3;
         2, 2, 2, 2, 2, 3, 1] := rfl

/-- Connection to our `cartanE7` infrastructure:
the off-diagonal Coxeter-3 entries correspond to the
Cartan -1 entries (edges of the Dynkin diagram). -/
theorem WE7.coxeterEntry_node_0_1 :
    (CoxeterMatrix.E₇ : CoxeterMatrix (Fin 7)).M 0 1 = 2 := rfl

theorem WE7.coxeterEntry_node_0_2 :
    (CoxeterMatrix.E₇ : CoxeterMatrix (Fin 7)).M 0 2 = 3 := rfl

/-- The Coxeter degrees `[2, 6, 8, 10, 12, 14, 18]` are the
fundamental invariant degrees of `W(E_7)`. The product equals
the order of the group: `2 · 6 · 8 · 10 · 12 · 14 · 18 = 2903040`. -/
theorem WE7.invariant_degrees_product :
    HodgeReduction.Infrastructure.wE7Degrees.prod = 2903040 :=
  HodgeReduction.Infrastructure.wE7_order

/-! ## Weyl-group action on a rational vector space

A finite Weyl group `W` acts on its reflection representation `V ≅ ℚ^n`
by `ℚ`-linear endomorphisms (Humphreys §1.3, Bourbaki Ch. V §4). The
substantive axioms are (i) `action` is a `MonoidHom`, (ii) `W` is
generated by a set of reflections (Humphreys §1.1, Bourbaki Ch. V §3.2).
-/

/-- **Abstract Weyl-group action data**: substantive `MonoidHom`
`action : W →* (V →ₗ[ℚ] V)` (reflection representation) together with
the **reflection-group axiom** — a substantive existential asserting
that some set of reflections generates `W` as a `Submonoid`
(Humphreys §1.1; Bourbaki Ch. V §3.2). -/
class WeylGroupActionData (W : Type*) [Group W] (V : Type*)
    [AddCommGroup V] [Module ℚ V] where
  /-- The substantive Weyl-action `W →* (V →ₗ[ℚ] V)`. -/
  action : W →* (V →ₗ[ℚ] V)
  /-- **Reflection-group axiom**: there exists a set of reflections
  whose `Submonoid` closure contains every element of `W`. This is the
  substantive existential generation statement (Humphreys §1.1). -/
  reflection_generation :
    ∃ (refls : Set W), ∀ w : W, w ∈ Submonoid.closure refls

namespace WeylGroupActionData

variable {W : Type*} [Group W] {V : Type*} [AddCommGroup V] [Module ℚ V]
  [WeylGroupActionData W V]

/-! ### Derived consequences of the Weyl-action axioms -/

/-- **Identity preservation**: the unit of `W` acts as the identity
linear map (consequence of `action` being a `MonoidHom`). -/
theorem action_one : action (W := W) (V := V) (1 : W) = LinearMap.id :=
  map_one (action (W := W) (V := V))

/-- **Multiplicative compatibility**: the action of a product is the
composition of actions (consequence of `action` being a `MonoidHom`,
where multiplication in `V →ₗ[ℚ] V` is composition). -/
theorem action_mul (w₁ w₂ : W) :
    action (W := W) (V := V) (w₁ * w₂) =
      action (W := W) (V := V) w₁ * action (W := W) (V := V) w₂ :=
  map_mul (action (W := W) (V := V)) w₁ w₂

/-- **Inverse-product cancels to identity** (group-action consequence):
the action of `w * w⁻¹ = 1` is the identity. Derived from `action_one`
combined with `action_mul`. -/
theorem action_mul_inv (w : W) :
    action (W := W) (V := V) w * action (W := W) (V := V) w⁻¹ =
      LinearMap.id := by
  rw [← action_mul, mul_inv_cancel, action_one]

/-- **Re-export** of the reflection-generation existential — exposed
under a theorem-level name for downstream use. The theorem statement
mentions `V` implicitly via the typeclass instance so the existential
on `W` is extracted with the correct typeclass-elaboration context. -/
theorem exists_reflection_set (V : Type*) [AddCommGroup V] [Module ℚ V]
    [WeylGroupActionData W V] :
    ∃ (refls : Set W), ∀ w : W, w ∈ Submonoid.closure refls :=
  WeylGroupActionData.reflection_generation (W := W) (V := V)

end WeylGroupActionData

/-! ## Coxeter presentation data for `W(E_7)`

`W(E_7)` admits a presentation by 7 simple reflections subject to the
relations `(s_i s_j)^{m_{ij}} = 1`, where `m_{ij}` is the
`(i,j)`-entry of the Coxeter matrix `CoxeterMatrix.E₇.M`
(Bourbaki Ch. VI Planche VI; Humphreys §2.13). Encoded here as a
typeclass on a carrier group `W` with simple-reflection function
`s : Fin 7 → W` and the substantive relation axiom.
-/

/-- **`W(E_7)` Coxeter-presentation data**: 7 simple reflections
`s : Fin 7 → W` and the substantive Coxeter relation
`(s i * s j)^(CoxeterMatrix.E₇.M i j) = 1` for every pair `(i, j)`
(Bourbaki Ch. VI Planche VI; Humphreys §2.13). Encodes the diagonal
involution (`m_{ii} = 1`), commutations (`m_{ij} = 2`), and braid
relations (`m_{ij} = 3`) of `W(E_7)`. -/
class WE7CoxeterPresentationData (W : Type*) [Group W] where
  /-- The 7 simple reflections `s_0, …, s_6 : W`. -/
  s : Fin 7 → W
  /-- **Coxeter relations**: `(s i * s j)^(CoxeterMatrix.E₇.M i j) = 1`
  for every pair `(i, j) ∈ Fin 7 × Fin 7`. -/
  relation : ∀ (i j : Fin 7),
    (s i * s j) ^ ((CoxeterMatrix.E₇ : CoxeterMatrix (Fin 7)).M i j) = 1

namespace WE7CoxeterPresentationData

variable {W : Type*} [Group W] [WE7CoxeterPresentationData W]

/-! ### Derived consequences of the Coxeter presentation -/

/-- **Diagonal involution**: each simple reflection squared is the
identity, derived from `relation i i` with the diagonal entry
`M.M i i = 1`. Specialised: `(s i * s i)^1 = 1` ⟹ `s i * s i = 1`. -/
theorem s_mul_self_eq_one (i : Fin 7) :
    s (W := W) i * s (W := W) i = 1 := by
  have h := relation (W := W) i i
  -- diagonal entry is `1`, so `(s i * s i)^1 = s i * s i = 1`.
  have hdiag : (CoxeterMatrix.E₇ : CoxeterMatrix (Fin 7)).M i i = 1 := by
    fin_cases i <;> rfl
  rw [hdiag, pow_one] at h
  exact h

/-- **Commutation relation between nodes 0 and 1**:
`(s 0 * s 1)^2 = 1` since the `(0,1)`-entry of the Coxeter matrix is
`2`. Derived as a specialisation of `relation`. -/
theorem s_0_1_braid_2 :
    (s (W := W) 0 * s (W := W) 1) ^ 2 = 1 := by
  have h := relation (W := W) 0 1
  have hentry : (CoxeterMatrix.E₇ : CoxeterMatrix (Fin 7)).M 0 1 = 2 := rfl
  rw [hentry] at h
  exact h

/-- **Braid relation between nodes 0 and 2**:
`(s 0 * s 2)^3 = 1` since the `(0,2)`-entry of the Coxeter matrix is
`3` (the Dynkin edge from node 0 to node 2). Derived from `relation`. -/
theorem s_0_2_braid_3 :
    (s (W := W) 0 * s (W := W) 2) ^ 3 = 1 := by
  have h := relation (W := W) 0 2
  have hentry : (CoxeterMatrix.E₇ : CoxeterMatrix (Fin 7)).M 0 2 = 3 := rfl
  rw [hentry] at h
  exact h

end WE7CoxeterPresentationData

/-! ## `W(E_7)`-invariant polynomial algebra description

By Chevalley-Shephard-Todd 1954/55, the `W(E_7)`-invariant polynomial
ring has 7 algebraically independent generators of degrees
`{2, 6, 8, 10, 12, 14, 18}` (matching `wE7Degrees`). At the linear-
action level we package the invariant subspace as a designated
`Submodule ℚ V` with the substantive `W`-invariance equation.
-/

/-- **`W(E_7)`-invariant subspace data**: companion to
`WeylGroupActionData W V` with designated `invariants : Submodule ℚ V`
and substantive `W`-invariance equation `action w v = v` for every
`v ∈ invariants` and `w : W` (Bourbaki Ch. V §5.1; Chevalley 1955). -/
class WE7InvariantsData (W : Type*) [Group W] (V : Type*)
    [AddCommGroup V] [Module ℚ V] [WeylGroupActionData W V] where
  /-- The substantive `W`-invariant `Submodule ℚ V`. -/
  invariants : Submodule ℚ V
  /-- **`W`-invariance equation**: every `v ∈ invariants` is fixed by
  every Weyl-action. -/
  is_invariant :
    ∀ {v : V}, v ∈ invariants → ∀ w : W,
      WeylGroupActionData.action (W := W) (V := V) w v = v

namespace WE7InvariantsData

variable {W : Type*} [Group W] {V : Type*} [AddCommGroup V] [Module ℚ V]
  [WeylGroupActionData W V] [WE7InvariantsData W V]

/-! ### Derived consequences of the invariant axioms -/

/-- **Re-export** of the substantive `is_invariant` equation. -/
theorem action_fixes (w : W) {v : V} (hv : v ∈ invariants (W := W)) :
    WeylGroupActionData.action (W := W) (V := V) w v = v :=
  is_invariant hv w

/-- **Sum of invariants is invariant**: closure of the invariant
subspace under addition is automatic since `invariants` is a
`Submodule`. Restated here under a theorem-level name. -/
theorem add_mem_invariants {v₁ v₂ : V}
    (h₁ : v₁ ∈ invariants (W := W)) (h₂ : v₂ ∈ invariants (W := W)) :
    v₁ + v₂ ∈ invariants (W := W) :=
  Submodule.add_mem _ h₁ h₂

/-- **Scalar multiple of an invariant is invariant**. Restated under a
theorem-level name. -/
theorem smul_mem_invariants (r : ℚ) {v : V} (h : v ∈ invariants (W := W)) :
    r • v ∈ invariants (W := W) :=
  Submodule.smul_mem _ r h

/-- **Zero is invariant**. -/
theorem zero_mem_invariants : (0 : V) ∈ invariants (W := W) :=
  Submodule.zero_mem _

end WE7InvariantsData

/-! ## Trivial inhabiting instances

Inhabiting instances on `W := PUnit` acting trivially on `V := ℚ`, with
empty reflection set (the identity is in `Submonoid.closure ∅` since
any submonoid contains `1`) and invariant subspace `⊤`. Witnesses non-
emptiness of all three typeclasses. -/

namespace Trivial

/-- **Trivial Weyl-action of `PUnit` on `ℚ`**: every element of
`PUnit` (only the unit) maps to the identity linear endomorphism of
`ℚ`. -/
instance weylActionPunitQ : WeylGroupActionData PUnit ℚ where
  action :=
    { toFun := fun _ => LinearMap.id
      map_one' := rfl
      map_mul' := fun _ _ => by
        -- `LinearMap.id * LinearMap.id = LinearMap.id` as endomorphism mult.
        show LinearMap.id = LinearMap.id * LinearMap.id
        ext; rfl }
  reflection_generation := by
    -- Take `refls = ∅`. Then `Submonoid.closure ∅ = ⊥ = {1}` and every
    -- element of `PUnit` equals `1`.
    refine ⟨∅, fun w => ?_⟩
    -- `w = 1` in `PUnit`, and `1 ∈ Submonoid.closure ∅` since any
    -- submonoid contains `1`.
    have hw : w = (1 : PUnit) := rfl
    rw [hw]
    exact Submonoid.one_mem _

/-- **Trivial `W(E_7)` Coxeter presentation on `PUnit`**: every
simple reflection is the unit, and the Coxeter relations are
trivially `1 = 1`. -/
instance we7CoxeterPunit : WE7CoxeterPresentationData PUnit where
  s _ := (1 : PUnit)
  relation _ _ := by
    -- `(1 * 1)^k = 1` for any `k` in `PUnit`.
    show ((1 : PUnit) * 1) ^ _ = 1
    rw [mul_one, one_pow]

/-- **Trivial `W(E_7)`-invariant subspace on `ℚ`**: the entire space
`⊤` is invariant (since the action is the identity). -/
instance we7InvariantsPunitQ : WE7InvariantsData PUnit ℚ where
  invariants := ⊤
  is_invariant := by
    intro v _ w
    -- The trivial action sends `v` to `v` (it's the identity).
    show (WeylGroupActionData.action (W := PUnit) (V := ℚ) w) v = v
    -- By definition of `weylActionPunitQ.action`, applying it to `v` is
    -- `LinearMap.id v = v`.
    rfl

end Trivial

end HodgeReduction.Infrastructure
