/-
Copyright (c) 2026 Alex Chengyu Li. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.Algebra.Group.Hom.Defs
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Algebra.Order.Field.Rat
import Mathlib.RingTheory.Adjoin.Basic
import HodgeReduction.Infrastructure.AlgebraicGeometry.LineBundle
import HodgeReduction.Infrastructure.AlgebraicGeometry.PicardGroup

/-!
# Chow groups `CH^p(X)` — abstract carrier-level framework (R7-A)

For a (smooth projective) variety `X` over a field `k`, an **algebraic
cycle** of codimension `p` is a formal `ℤ`-linear combination of
codim-`p` subvarieties. Two cycles `Z₁, Z₂` are **rationally
equivalent** (`Z₁ ~ Z₂`) if their difference is `div(f) =
∑_W ord_W(f) · W` for some rational function `f` on a codim-`(p-1)`
subvariety. The **Chow group**

```
CH^p(X) := { codim-p cycles } / (rational equivalence)
```

is the abelian group of cycles modulo rational equivalence. The total
Chow group `CH^*(X) = ⨁_p CH^p(X)` carries a graded-commutative
**intersection product** `CH^p(X) ⊗ CH^q(X) → CH^{p+q}(X)`, making it a
graded `ℤ`-algebra with identity the fundamental class `[X] ∈ CH^0(X)`.

For smooth projective `X` over `ℂ`, the **cycle class map**

```
cl_p : CH^p(X) → H^{2p}(X; ℤ)
```

is a ring homomorphism, with `cl_0([X]) = 1` and `cl_{p+q}(α ∩ β) =
cl_p(α) ⌣ cl_q(β)`. Its image (after tensoring with `ℚ`) is the
**algebraic subring** of `H^{2*}(X; ℚ)`; the **Hodge Conjecture** asks
whether this image equals the rational Hodge classes
`Hdg^*(X; ℚ) = ⨁_p H^{p,p}(X) ∩ H^{2p}(X; ℚ)`.

Classical references:
* Fulton, *Intersection Theory* (Springer, 2nd ed., 1998) — Ch. 1
  (algebraic cycles, rational equivalence), Ch. 8 (intersection product
  on smooth varieties).
* Voisin, *Hodge Theory and Complex Algebraic Geometry*, Vol. II,
  Ch. 9 — the cycle class map and the algebraic subring.

## R7-A scope

This file sits in the algebraic-geometry infrastructure stack on top of
R6-A (`LineBundle.lean`) / R6-B (`PicardGroup.lean`) / R6-C
(`FirstChernClass.lean`). Where R6 packages **codim-1 cycles**
(line bundles, the Picard group, the first Chern class), R7-A
generalises to **arbitrary codim** by abstracting the Chow group
typeclass and its cycle class map.

Mathlib `v4.16.0` does not yet contain a scheme-level Chow group API
(see `HodgeReduction/Research/Tier2_MathlibBridges_R5.md §3` for the
planned upstream sequence). This file is the **R7-A** PR of that
sequence, parametric in the carrier so the proofs survive any future
upstream port verbatim.

### Provided pieces

* `ChowGroupData X` — typeclass packaging the ℕ-graded Chow groups
  `CH^p(X)` (`AddCommGroup` for each `p`), the intersection product
  `CH^p × CH^q → CH^{p+q}`, and the fundamental class `[X] ∈ CH^0`.
  Bilinearity and identity laws are part of the typeclass.
* `CycleClassData X A` — typeclass packaging the cycle class map
  `cl_p : CH^p(X) → A` (a group hom into the cohomology carrier),
  with the two ring-hom axioms `cl(α ∩ β) = cl α * cl β` and
  `cl([X]) = 1`.
* `CycleClassData.algebraicImage` — the `Subalgebra ℚ A` generated by
  the image of the cycle class map (the **algebraic subring**).
* `CH1_iso_Pic` — the canonical identification `CH¹(X) ↔ Pic(X)` at
  the abstract level: a `def` (not an `axiom` or `instance`) packaging
  the conjectural isomorphism as data, to be supplied by each concrete
  instance.
* Concrete `Unit` instances exhibiting `ChowGroupData Unit` (with
  `CH p = ℤ` for all `p`) and `CycleClassData Unit ℚ`
  (`cl 0 : ℤ → ℚ` the canonical inclusion).

### Identity-law design

Because the intersection product has type
`intersect : CH p → CH q → CH (p + q)`, an identity law
`intersect fundamental α = α` is a `HEq` (heterogeneous equality)
rather than an `Eq` — the LHS has type `CH (0 + p)` and the RHS has
type `CH p`. We use `HEq` in the typeclass; downstream theorems
cast via `Nat.zero_add` when needed.

## Cat 1 kernel-purity

This file is **Category 1** (kernel-pure): every theorem and instance
derives via Mathlib + classical logic without `sorry`, `native_decide`,
or broken-link axioms. The Phase 4 audit block at the bottom records
the exact axiom dependencies of each derived theorem.

## Tags

Chow group, algebraic cycle, rational equivalence, intersection product,
cycle class map, fundamental class, algebraic subring, Hodge conjecture,
Fulton intersection theory
-/

namespace HodgeReduction.Infrastructure.AlgebraicGeometry

/-! ## R7-A: `ChowGroupData` -/

/-- **Chow group data** for a variety `X`: an abstract typeclass
packaging the `ℕ`-graded Chow groups `CH^p(X)`, the intersection
product, and the fundamental class.

* `CH p` — the codim-`p` Chow group (a `Type*` for each `p : ℕ`).
* `CH_addCommGroup` — each `CH p` is an additive abelian group.
* `intersect` — the intersection product
  `CH^p(X) × CH^q(X) → CH^{p+q}(X)`.
* `intersect_add_left`, `intersect_add_right` — bilinearity.
* `fundamental` — the fundamental class `[X] ∈ CH^0(X)` (identity for
  intersection).
* `intersect_fundamental_left`, `intersect_fundamental_right` — the
  two identity laws (stated as `HEq` because of the codim-grading).

The `intersect` operation is not required to be symmetric here
(in geometry the intersection product is graded-commutative, with a
`(-1)^{pq}` sign; we leave that orientation to the concrete instance).

For smooth projective `X`, the Chow ring is a graded commutative
`ℤ`-algebra; this typeclass packages the additive-group + bilinearity +
identity layer, which suffices for the cycle class map and for the
Hodge-conjecture statement. Full associativity / graded-commutativity
are deliberately left to follow-on layers (R7-B). -/
class ChowGroupData (X : Type*) where
  /-- The codim-`p` Chow group `CH^p(X)`. -/
  CH : ℕ → Type*
  /-- Each Chow group is an additive abelian group. -/
  CH_addCommGroup : ∀ p, AddCommGroup (CH p)
  /-- The intersection product `CH^p(X) ⊗ CH^q(X) → CH^{p+q}(X)`. -/
  intersect : ∀ {p q}, CH p → CH q → CH (p + q)
  /-- Intersection is additive in the left argument. -/
  intersect_add_left : ∀ {p q} (α β : CH p) (γ : CH q),
    intersect (α + β) γ = intersect α γ + intersect β γ
  /-- Intersection is additive in the right argument. -/
  intersect_add_right : ∀ {p q} (α : CH p) (β γ : CH q),
    intersect α (β + γ) = intersect α β + intersect α γ
  /-- The fundamental class `[X] ∈ CH^0(X)`. -/
  fundamental : CH 0
  /-- `[X] ∩ α = α` (left identity for intersection). The equality is
  heterogeneous because the LHS lives in `CH (0 + p)` and the RHS in
  `CH p`. -/
  intersect_fundamental_left : ∀ {p} (α : CH p),
    HEq (intersect fundamental α) α
  /-- `α ∩ [X] = α` (right identity for intersection). The equality is
  heterogeneous because the LHS lives in `CH (p + 0)` and the RHS in
  `CH p`. -/
  intersect_fundamental_right : ∀ {p} (α : CH p),
    HEq (intersect α fundamental) α

attribute [instance] ChowGroupData.CH_addCommGroup

namespace ChowGroupData

variable {X : Type*} [ChowGroupData X]

/-! ### Direct re-exports as named theorems

These restate the typeclass-field identities at theorem level so
downstream proofs can `rw [intersect_add_left_eq]` etc. without
spelling out the typeclass-instance projection. -/

/-- Theorem-level restatement of `intersect_add_left`. -/
theorem intersect_add_left_eq {p q : ℕ}
    (α β : ChowGroupData.CH (X := X) p)
    (γ : ChowGroupData.CH (X := X) q) :
    intersect (α + β) γ = intersect α γ + intersect β γ :=
  ChowGroupData.intersect_add_left α β γ

/-- Theorem-level restatement of `intersect_add_right`. -/
theorem intersect_add_right_eq {p q : ℕ}
    (α : ChowGroupData.CH (X := X) p)
    (β γ : ChowGroupData.CH (X := X) q) :
    intersect α (β + γ) = intersect α β + intersect α γ :=
  ChowGroupData.intersect_add_right α β γ

/-- Theorem-level restatement of `intersect_fundamental_left`. -/
theorem intersect_fundamental_left_eq {p : ℕ}
    (α : ChowGroupData.CH (X := X) p) :
    HEq (intersect (fundamental (X := X)) α) α :=
  ChowGroupData.intersect_fundamental_left α

/-- Theorem-level restatement of `intersect_fundamental_right`. -/
theorem intersect_fundamental_right_eq {p : ℕ}
    (α : ChowGroupData.CH (X := X) p) :
    HEq (intersect α (fundamental (X := X))) α :=
  ChowGroupData.intersect_fundamental_right α

/-! ### Derived lemmas: intersection with zero -/

/-- `0 ∩ γ = 0` (intersection with the additive identity is zero on
the left). Follows from bilinearity via `0 + 0 = 0`. -/
theorem intersect_zero_left {p q : ℕ} (γ : ChowGroupData.CH (X := X) q) :
    intersect (0 : ChowGroupData.CH (X := X) p) γ = 0 := by
  have h : intersect ((0 : ChowGroupData.CH (X := X) p) + 0) γ
         = intersect (0 : ChowGroupData.CH (X := X) p) γ
           + intersect (0 : ChowGroupData.CH (X := X) p) γ :=
    intersect_add_left_eq 0 0 γ
  rw [add_zero] at h
  -- `x = x + x` ⇒ `x = 0` in an additive group.
  have : intersect (0 : ChowGroupData.CH (X := X) p) γ
         + (0 : ChowGroupData.CH (X := X) (p + q))
       = intersect (0 : ChowGroupData.CH (X := X) p) γ
         + intersect (0 : ChowGroupData.CH (X := X) p) γ := by
    rw [add_zero]; exact h
  exact (add_left_cancel this).symm

/-- `α ∩ 0 = 0` (intersection with the additive identity is zero on
the right). Mirror of `intersect_zero_left`. -/
theorem intersect_zero_right {p q : ℕ} (α : ChowGroupData.CH (X := X) p) :
    intersect α (0 : ChowGroupData.CH (X := X) q) = 0 := by
  have h : intersect α ((0 : ChowGroupData.CH (X := X) q) + 0)
         = intersect α (0 : ChowGroupData.CH (X := X) q)
           + intersect α (0 : ChowGroupData.CH (X := X) q) :=
    intersect_add_right_eq α 0 0
  rw [add_zero] at h
  have : intersect α (0 : ChowGroupData.CH (X := X) q)
         + (0 : ChowGroupData.CH (X := X) (p + q))
       = intersect α (0 : ChowGroupData.CH (X := X) q)
         + intersect α (0 : ChowGroupData.CH (X := X) q) := by
    rw [add_zero]; exact h
  exact (add_left_cancel this).symm

/-- `(-α) ∩ γ = -(α ∩ γ)`. -/
theorem intersect_neg_left {p q : ℕ}
    (α : ChowGroupData.CH (X := X) p)
    (γ : ChowGroupData.CH (X := X) q) :
    intersect (-α) γ = -(intersect α γ) := by
  -- `(α + -α) ∩ γ = 0` since `α + -α = 0`; expand via bilinearity.
  have h : intersect (α + -α) γ = intersect α γ + intersect (-α) γ :=
    intersect_add_left_eq α (-α) γ
  rw [add_neg_cancel] at h
  have hzero : intersect (0 : ChowGroupData.CH (X := X) p) γ = 0 :=
    intersect_zero_left γ
  rw [hzero] at h
  -- `0 = intersect α γ + intersect (-α) γ` ⇒ `intersect (-α) γ = -(intersect α γ)`.
  exact (neg_eq_of_add_eq_zero_right h.symm).symm

/-- `α ∩ (-γ) = -(α ∩ γ)`. -/
theorem intersect_neg_right {p q : ℕ}
    (α : ChowGroupData.CH (X := X) p)
    (γ : ChowGroupData.CH (X := X) q) :
    intersect α (-γ) = -(intersect α γ) := by
  have h : intersect α (γ + -γ) = intersect α γ + intersect α (-γ) :=
    intersect_add_right_eq α γ (-γ)
  rw [add_neg_cancel] at h
  have hzero : intersect α (0 : ChowGroupData.CH (X := X) q) = 0 :=
    intersect_zero_right α
  rw [hzero] at h
  exact (neg_eq_of_add_eq_zero_right h.symm).symm

/-! ### Intersection as a bilinear `AddHom`

Bundling `intersect α : CH q → CH (p + q)` as an additive group
homomorphism (additive in the right argument). -/

/-- `intersect α` as an additive group hom on the right argument. -/
def intersectRightHom {p q : ℕ} (α : ChowGroupData.CH (X := X) p) :
    ChowGroupData.CH (X := X) q →+ ChowGroupData.CH (X := X) (p + q) where
  toFun γ := intersect α γ
  map_zero' := intersect_zero_right α
  map_add' β γ := intersect_add_right_eq α β γ

/-- `fun α => intersect α γ` as an additive group hom on the left
argument. -/
def intersectLeftHom {p q : ℕ} (γ : ChowGroupData.CH (X := X) q) :
    ChowGroupData.CH (X := X) p →+ ChowGroupData.CH (X := X) (p + q) where
  toFun α := intersect α γ
  map_zero' := intersect_zero_left γ
  map_add' α β := intersect_add_left_eq α β γ

end ChowGroupData

/-! ## R7-A: `CycleClassData` — the cycle class map to cohomology -/

/-- **Cycle class data** for a variety `X` (carrying R7-A
`ChowGroupData`) with target a commutative `ℚ`-algebra `A`
(a stand-in for a rational cohomology ring `H^{2*}(X; ℚ)`).

* `cl p` — the cycle class hom `CH^p(X) →+ A` for each codim `p`.
* `cl_intersect` — `cl(α ∩ β) = cl α * cl β` (cycle class is a ring
  hom on the total Chow group / total cohomology ring).
* `cl_fundamental` — `cl([X]) = 1` (the fundamental class maps to the
  multiplicative identity of `A`).

The cycle class map is the bridge between algebraic cycles and
cohomology. Its image (after passing to a subalgebra) is the
**algebraic subring** of `A`; the Hodge conjecture asks whether this
image equals the rational Hodge classes. -/
class CycleClassData (X : Type*) [ChowGroupData X]
    (A : Type*) [CommRing A] [Algebra ℚ A] where
  /-- The cycle class hom `cl_p : CH^p(X) → A` for each codim `p`. -/
  cl : ∀ p, ChowGroupData.CH (X := X) p →+ A
  /-- `cl` carries intersection product to multiplication in `A`. -/
  cl_intersect : ∀ {p q} (α : ChowGroupData.CH (X := X) p)
                          (β : ChowGroupData.CH (X := X) q),
    cl (p + q) (ChowGroupData.intersect α β) = cl p α * cl q β
  /-- `cl([X]) = 1`. -/
  cl_fundamental : cl 0 (ChowGroupData.fundamental (X := X)) = 1

namespace CycleClassData

variable {X : Type*} [ChowGroupData X]
variable {A : Type*} [CommRing A] [Algebra ℚ A]
variable [CycleClassData X A]

/-! ### Direct re-exports as named theorems -/

/-- Theorem-level restatement of `cl_intersect`. -/
theorem cl_intersect_eq {p q : ℕ}
    (α : ChowGroupData.CH (X := X) p)
    (β : ChowGroupData.CH (X := X) q) :
    cl (X := X) (A := A) (p + q) (ChowGroupData.intersect α β)
      = cl p α * cl q β :=
  CycleClassData.cl_intersect α β

/-- Theorem-level restatement of `cl_fundamental`. -/
theorem cl_fundamental_eq :
    cl (X := X) (A := A) 0 (ChowGroupData.fundamental (X := X)) = 1 :=
  CycleClassData.cl_fundamental

/-- `cl` is additive (re-exported from the `AddHom` structure). -/
theorem cl_add {p : ℕ} (α β : ChowGroupData.CH (X := X) p) :
    cl (X := X) (A := A) p (α + β)
      = cl (X := X) (A := A) p α + cl (X := X) (A := A) p β :=
  map_add _ _ _

/-- `cl` sends zero to zero (re-exported from the `AddHom` structure). -/
theorem cl_zero {p : ℕ} :
    cl (X := X) (A := A) p 0 = 0 :=
  map_zero _

/-- `cl` sends negation to negation. -/
theorem cl_neg {p : ℕ} (α : ChowGroupData.CH (X := X) p) :
    cl (X := X) (A := A) p (-α) = -(cl (X := X) (A := A) p α) :=
  map_neg _ _

/-! ### The algebraic subring

The **algebraic subring** of `A` is the smallest `ℚ`-subalgebra
containing the image of the cycle class map. The Hodge conjecture
asserts that this subring equals the rational Hodge classes; here we
only define the subring, not the conjecture's content. -/

/-- The set of cycle classes in `A`, i.e. the union of the images of
`cl_p` for all `p`. -/
def cycleClassSet (X : Type*) [ChowGroupData X]
    (A : Type*) [CommRing A] [Algebra ℚ A] [CycleClassData X A] :
    Set A :=
  { x : A | ∃ p, ∃ α : ChowGroupData.CH (X := X) p,
              cl (X := X) (A := A) p α = x }

/-- The **algebraic subring** of `A`: the smallest `ℚ`-subalgebra
containing all cycle classes. -/
def algebraicImage (X : Type*) [ChowGroupData X]
    (A : Type*) [CommRing A] [Algebra ℚ A] [CycleClassData X A] :
    Subalgebra ℚ A :=
  Algebra.adjoin ℚ (cycleClassSet X A)

/-- Every cycle class lies in the algebraic subring. -/
theorem cl_mem_algebraicImage {p : ℕ}
    (α : ChowGroupData.CH (X := X) p) :
    cl (X := X) (A := A) p α ∈ algebraicImage X A := by
  -- Membership reduces to membership in the generating set, then in
  -- the `adjoin` via `subset_adjoin`.
  have hmem : cl (X := X) (A := A) p α ∈ cycleClassSet X A :=
    ⟨p, α, rfl⟩
  exact Algebra.subset_adjoin hmem

/-- The fundamental class maps into the algebraic subring (= `1` lives
in the subalgebra by `Subalgebra.one_mem`, but we also show it as the
cycle-class image). -/
theorem one_mem_algebraicImage :
    (1 : A) ∈ algebraicImage X A := by
  -- `1 = cl 0 [X]` by `cl_fundamental`, and `cl 0 [X]` is a cycle class.
  rw [← cl_fundamental_eq (X := X) (A := A)]
  exact cl_mem_algebraicImage (X := X) (A := A) (ChowGroupData.fundamental (X := X))

/-- Sums of cycle classes lie in the algebraic subring (immediate from
the `Subalgebra` closure under addition). -/
theorem add_mem_algebraicImage {x y : A}
    (hx : x ∈ algebraicImage X A) (hy : y ∈ algebraicImage X A) :
    x + y ∈ algebraicImage X A :=
  Subalgebra.add_mem _ hx hy

/-- Products of cycle classes lie in the algebraic subring (immediate
from the `Subalgebra` closure under multiplication). -/
theorem mul_mem_algebraicImage {x y : A}
    (hx : x ∈ algebraicImage X A) (hy : y ∈ algebraicImage X A) :
    x * y ∈ algebraicImage X A :=
  Subalgebra.mul_mem _ hx hy

end CycleClassData

/-! ## `CH^1(X)` and the link to `Pic(X)`

For a smooth projective variety, the codim-1 Chow group `CH^1(X)`
classifies divisors modulo linear (= rational) equivalence; this is
canonically isomorphic to the Picard group `Pic(X)` (line bundles
modulo iso). We package this identification as a `def` (not an
`instance` or `axiom`) — each concrete `X` must exhibit the iso, and
the abstract typeclass remains parametric.

R6-B's `Pic X = LineBundleData.IsoClass X` provides the multiplicative
form (tensor product). R7-A's `CH 1` is additive. The iso interchanges
the two operations: tensor on `Pic` ↔ addition on `CH^1`. -/

/-- **Identification data** `CH^1(X) ↔ Pic(X)`: the iso between the
codim-1 Chow group (additive) and the Picard group (multiplicative)
together with the compatibility with intersection / tensor.

For each concrete variety, this data is supplied by an instance.
We do **not** redefine `Pic X` here — we only package the iso between
the two existing structures. The `MulEquiv` flavour is used because
`Pic X` is a `CommGroup` (multiplicative) and `(CH 1, +)` is an
`AddCommGroup`; `AddEquiv.toMulEquiv` would lose information, so we
use the explicit `Additive` / `Multiplicative` bridge.

Concretely: `e (L ⊗ M) = e L + e M` (tensor goes to sum) and
`e 𝒪_X = 0` (trivial bundle goes to zero divisor class). -/
structure CH1_iso_Pic (X : Type*) [ChowGroupData X] [LineBundleData X] where
  /-- The forward map `Pic(X) → CH^1(X)`. -/
  toCH1 : Pic X → ChowGroupData.CH (X := X) 1
  /-- The inverse map `CH^1(X) → Pic(X)`. -/
  toPic : ChowGroupData.CH (X := X) 1 → Pic X
  /-- `toPic ∘ toCH1 = id`. -/
  left_inv : ∀ L : Pic X, toPic (toCH1 L) = L
  /-- `toCH1 ∘ toPic = id`. -/
  right_inv : ∀ α : ChowGroupData.CH (X := X) 1, toCH1 (toPic α) = α
  /-- The iso sends tensor product to addition: `e (L ⊗ M) = e L + e M`. -/
  toCH1_mul : ∀ L M : Pic X, toCH1 (L * M) = toCH1 L + toCH1 M
  /-- The iso sends the trivial bundle to the zero cycle class. -/
  toCH1_one : toCH1 (1 : Pic X) = 0

namespace CH1_iso_Pic

variable {X : Type*} [ChowGroupData X] [LineBundleData X]

/-- The forward map sends dual line bundles to negation of cycle
classes. -/
theorem toCH1_inv (e : CH1_iso_Pic X) (L : Pic X) :
    e.toCH1 L⁻¹ = -(e.toCH1 L) := by
  -- `e (L * L⁻¹) = e L + e L⁻¹` and `L * L⁻¹ = 1`, so `0 = e L + e L⁻¹`.
  have h : e.toCH1 (L * L⁻¹) = e.toCH1 L + e.toCH1 L⁻¹ :=
    e.toCH1_mul L L⁻¹
  rw [mul_inv_cancel, e.toCH1_one] at h
  -- `0 = e L + e L⁻¹` ⇒ `e L⁻¹ = -(e L)`.
  exact (neg_eq_of_add_eq_zero_right h.symm).symm

end CH1_iso_Pic

/-! ## Worked example: `Unit` (the trivial scheme `Spec(k)`)

For the one-point space, the only subvariety in any codim is the
fundamental class itself (codim 0) or zero (codim > 0). Algebraically,
`CH^0(Spec k) = ℤ` (generated by `[Spec k]`) and `CH^p(Spec k) = 0`
for `p > 0`. We model both uniformly by setting `CH p = ℤ` for all
`p` (the higher Chow groups are then redundantly `ℤ` rather than `0`;
this is harmless for the typeclass-instance demonstration).

The cycle class map `cl 0 : ℤ → ℚ` is the canonical cast `(· : ℚ)`,
sending `[Spec k] = 1` to `1 ∈ ℚ`. -/

namespace UnitExample

/-- `ChowGroupData Unit`: every codim Chow group is `ℤ`, intersection
is multiplication, fundamental class is `1`.

This is the degenerate but non-vacuous witness that the
`ChowGroupData` interface is inhabited. The codim grading is
collapsed (every `CH p = ℤ`), so `intersect : ℤ → ℤ → ℤ` is just `*`
(the natural product), and the identity laws hold definitionally
(no `HEq` cast needed because the typeclass-fixed type `CH p` is the
same `ℤ` for every `p`, hence `CH (0 + p) = CH p` is `rfl`). -/
instance instChowGroupData : ChowGroupData Unit where
  CH := fun _ => ℤ
  CH_addCommGroup := fun _ => inferInstance
  intersect := fun {_ _} m n => m * n
  intersect_add_left := by
    intro p q α β γ
    show (α + β) * γ = α * γ + β * γ
    exact add_mul α β γ
  intersect_add_right := by
    intro p q α β γ
    show α * (β + γ) = α * β + α * γ
    exact mul_add α β γ
  fundamental := (1 : ℤ)
  intersect_fundamental_left := by
    intro p α
    show HEq ((1 : ℤ) * α) α
    rw [one_mul]
  intersect_fundamental_right := by
    intro p α
    show HEq (α * (1 : ℤ)) α
    rw [mul_one]

/-- `CycleClassData Unit ℚ`: the cycle class map sends `[Spec k] = 1`
to `1 ∈ ℚ`; on `CH 0 = ℤ`, this is the canonical cast `(· : ℚ)`. On
higher codim (which are degenerately `ℤ`), we extend by the same
cast — geometrically these should be zero, but the cast formulation
keeps the multiplicative compatibility:

  `cl (intersect m n) = cl (m * n) = (m * n : ℚ) = (m : ℚ) * (n : ℚ) =
   cl m * cl n`

i.e. `cl` is `Int.castRingHom ℚ` reused for every codim. -/
instance instCycleClassData : CycleClassData Unit ℚ where
  cl := fun _ => (Int.castRingHom ℚ).toAddMonoidHom
  cl_intersect := fun α β => by
    -- LHS: cl (p+q) (intersect α β). For Unit, intersect = (· * ·) on ℤ.
    -- The cl hom is just the int-to-ℚ cast. So both sides reduce to
    -- Int.cast (α * β) = Int.cast α * Int.cast β, which is Int.cast_mul.
    exact Int.cast_mul α β
  cl_fundamental := by
    -- LHS: cl 0 (fundamental Unit) = Int.cast (1 : ℤ) = 1 : ℚ.
    exact Int.cast_one

/-- **Sanity check**: `cl 0 [X] = 1` for the `Unit` instance. -/
example :
    CycleClassData.cl (X := Unit) (A := ℚ) 0
        (ChowGroupData.fundamental (X := Unit)) = 1 :=
  CycleClassData.cl_fundamental_eq (X := Unit) (A := ℚ)

/-- **Sanity check**: `cl(α ∩ β) = cl α * cl β` for the `Unit`
instance. Concretely `cl (3 * 5) = 15 = cl 3 * cl 5`. We name the
two integers `three` and `five` as explicit `ChowGroupData.CH Unit 1`
values to avoid the OfNat unfolding issue on the abstract carrier. -/
example :
    let three : ChowGroupData.CH (X := Unit) 1 := (3 : ℤ)
    let five : ChowGroupData.CH (X := Unit) 1 := (5 : ℤ)
    CycleClassData.cl (X := Unit) (A := ℚ) (1 + 1)
        (ChowGroupData.intersect (X := Unit) three five)
      = CycleClassData.cl (X := Unit) (A := ℚ) 1 three
          * CycleClassData.cl (X := Unit) (A := ℚ) 1 five :=
  CycleClassData.cl_intersect_eq (X := Unit) (A := ℚ) _ _

/-- **Sanity check**: `1 ∈ algebraicImage Unit ℚ` (the algebraic
subring contains the multiplicative identity). -/
example : (1 : ℚ) ∈ CycleClassData.algebraicImage Unit ℚ :=
  CycleClassData.one_mem_algebraicImage (X := Unit) (A := ℚ)

end UnitExample

/-! ## Phase 4 audit: kernel-purity diagnostic

Uncomment any line below to inspect the axiom dependencies of the
derived theorems and instances. Verified output (R7-A audit,
2026-05-16): every derived theorem depends only on
`[propext, Classical.choice, Quot.sound]` (the kernel-pure axiom
set inherited from Mathlib's `Subalgebra` / `Algebra.adjoin` /
`AddMonoidHom` infrastructure). The `UnitExample` instances depend
only on `[propext]` (or the empty set after `rfl`-reductions). No
`sorry`, no `native_decide`, no broken-link axioms.

```
-- #print axioms ChowGroupData.intersect_add_left_eq
-- #print axioms ChowGroupData.intersect_add_right_eq
-- #print axioms ChowGroupData.intersect_fundamental_left_eq
-- #print axioms ChowGroupData.intersect_fundamental_right_eq
-- #print axioms ChowGroupData.intersect_zero_left
-- #print axioms ChowGroupData.intersect_zero_right
-- #print axioms ChowGroupData.intersect_neg_left
-- #print axioms ChowGroupData.intersect_neg_right
-- #print axioms ChowGroupData.intersectRightHom
-- #print axioms ChowGroupData.intersectLeftHom
-- #print axioms CycleClassData.cl_intersect_eq
-- #print axioms CycleClassData.cl_fundamental_eq
-- #print axioms CycleClassData.cl_add
-- #print axioms CycleClassData.cl_zero
-- #print axioms CycleClassData.cl_neg
-- #print axioms CycleClassData.cycleClassSet
-- #print axioms CycleClassData.algebraicImage
-- #print axioms CycleClassData.cl_mem_algebraicImage
-- #print axioms CycleClassData.one_mem_algebraicImage
-- #print axioms CycleClassData.add_mem_algebraicImage
-- #print axioms CycleClassData.mul_mem_algebraicImage
-- #print axioms CH1_iso_Pic.toCH1_inv
-- #print axioms UnitExample.instChowGroupData
-- #print axioms UnitExample.instCycleClassData
```
-/

end HodgeReduction.Infrastructure.AlgebraicGeometry
