/-
Copyright (c) 2026 Alex Chengyu Li. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.Algebra.Polynomial.Eval.Defs
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Tactic.Module
import HodgeReduction.Strict
import HodgeReduction.Infrastructure.Cohomology.Basic
import HodgeReduction.Infrastructure.Cohomology.ChernClasses
import HodgeReduction.Infrastructure.Cohomology.KaehlerClass
import HodgeReduction.Infrastructure.Cohomology.FreudenthalClass
import HodgeReduction.Infrastructure.Cohomology.Lefschetz
import HodgeReduction.Infrastructure.Cohomology.HodgeCycle

/-!
# Concrete EVII cohomology carrier (scaffolding)

This file gives the **first concrete instance** of the abstract HC
framework: a Lean type `A_EVII` modelling (a simplification of) the
rational cohomology ring of the compact dual `Ě_VII` of the EVII
Shimura variety, together with concrete instances of every typeclass
the framework requires to derive HC for the Freudenthal quartic on
EVII via `HC_for_freudenthal_quartic_on_EVII_UNCONDITIONAL`.

## Scaffolding status

This is **R1 starter scaffolding** for the Cat 1-conversion long
game. Mathematically, the cohomology of `Ě_VII` is
`H^*(Ě_VII; ℚ) ≃ ℚ[h] / (h^{28})` (truncated polynomial ring,
generated by the Kähler class `h ∈ H^2`, with relations from the
Poincaré polynomial `(1-t^{20})(1-t^{28})(1-t^{36}) / [(1-t^2)(1-t^{10})(1-t^{18})]`).

For starter scaffolding we use the **untruncated** polynomial ring
`Polynomial ℚ` as carrier — strictly larger than the true cohomology,
but it admits all the required Mathlib structure for free and lets
the framework typeclasses be instantiated immediately. Subsequent
rounds will refine `A_EVII` to the quotient `Polynomial ℚ / (X^{28})`
and replace each placeholder field with a mathematically faithful
construction.

The **`algebraic` subalgebra** is set to `⊤` in this scaffolding —
every element is declared "algebraic". This is mathematically a
gross over-approximation (the actual algebraic subring of
`H^*(Ě_VII; ℚ)` is the full thing only because `Ě_VII` has cell
decomposition with only even-codim cells, but the scaffolding uses
`⊤` without invoking that fact). Future rounds will replace `⊤` by
the image of an explicit cycle-class map.

The **Chern classes** of the auxiliary algebraic bundle `𝓔_{+1}` are
chosen as the unique values consistent with both the polynomial
identity `[q] = -48 c_2² + 96 c_1 c_3 − 96 c_4` and the Kähler
proportionality `[q] = -48 h^4`. The simplest such choice is
`c_1 = c_2 = c_3 = 0`, `c_4 = (1/2) • X^4` (giving
`-96 • (1/2) X^4 = -48 X^4 = q`). This is **not** the true Chern
class data of `𝓔_{+1}` (which has nonzero `c_1, ..., c_4` per the
P48 explicit values in the master proof); it is a witness that the
typeclass *can* be inhabited concretely.

## What this file provides

* `A_EVII : Type` — the carrier (currently `Polynomial ℚ`).
* `instance : CommRing A_EVII` — from Mathlib.
* `instance : Algebra ℚ A_EVII` — from Mathlib.
* `instance : CohomologyRing A_EVII` — `algebraic := ⊤`.
* `instance : KaehlerClass A_EVII` — `h := Polynomial.X`.
* `instance : Lefschetz11Data A_EVII` — `H2 = H11 = ⊤`.
* `instance : HodgeCycleData A_EVII` — `hodge := ⊤`.
* `freudenthalClassData_EVII : FreudenthalClassData A_EVII` — the
  concrete Freudenthal class `q = -48 X^4` with consistent Chern data.
* `HC_for_Concrete_EVII : CohomologyRing.IsAlgebraic
  freudenthalClassData_EVII.q` — the concrete-instantiation sanity
  check, derived by applying the abstract unconditional theorem.

## Tags

EVII Shimura variety, concrete instance, Freudenthal quartic, scaffolding
-/

namespace HodgeReduction.Concrete

open HodgeReduction.Infrastructure.Cohomology
open Polynomial

/-! ### The carrier -/

/-- **Concrete EVII cohomology carrier** (scaffolding stage).

Mathematically intended to model `H^*(Ě_VII; ℚ) ≃ ℚ[h] / (h^{28})`,
but at the scaffolding stage we use the untruncated polynomial ring
`Polynomial ℚ`. This admits all required Mathlib typeclass structure
(commutative ring, ℚ-algebra) for free and supports a concrete
instantiation of every HC-framework typeclass.

Subsequent rounds will refine this definition to the truncation
`Polynomial ℚ / (X^{28})`. -/
abbrev A_EVII : Type := Polynomial ℚ

/-! ### Ring and algebra instances (free from Mathlib) -/

-- `CommRing A_EVII` and `Algebra ℚ A_EVII` are inherited from
-- `Polynomial.commRing` and `Polynomial.algebraOfAlgebra` (or the
-- canonical `Polynomial ℚ` instances) via the `abbrev` definition.

/-! ### CohomologyRing instance -/

/-- **Concrete `CohomologyRing A_EVII`** (scaffolding).

The "algebraic" subalgebra is taken to be all of `A_EVII` (`⊤`). This
is a coarse scaffolding choice — every polynomial counts as algebraic.
Mathematically, for `Ě_VII` the algebraic subring of `H^*(Ě_VII; ℚ)`
is in fact the whole cohomology ring (because `Ě_VII` admits a
Białynicki-Birula decomposition with only even-codim cells, making
every cohomology class algebraic), so the `⊤` choice is also
mathematically correct in this case — but the scaffolding does NOT
invoke that fact, it just takes `⊤` by fiat. -/
noncomputable instance instCohomologyRing : CohomologyRing A_EVII where
  algebraic := (⊤ : Subalgebra ℚ A_EVII)

/-- Every element of `A_EVII` is algebraic in the scaffolding instance.
This is the workhorse lemma: it reduces every `IsAlgebraic` goal to
`True` (via membership in `⊤`). -/
theorem isAlgebraic_of_top (α : A_EVII) :
    CohomologyRing.IsAlgebraic α := by
  -- `CohomologyRing.IsAlgebraic α` unfolds to `α ∈ algebraic`, which is
  -- `α ∈ (⊤ : Subalgebra ℚ A_EVII)`. The latter is `True` by `Algebra.mem_top`.
  show α ∈ (⊤ : Subalgebra ℚ A_EVII)
  exact Algebra.mem_top

/-! ### KaehlerClass instance -/

/-- **Concrete `KaehlerClass A_EVII`**: the Kähler class is the
polynomial generator `h := X`. Mathematically, `h` corresponds to
the polarisation class `c_1(L) ∈ H^2(Ě_VII; ℚ)` (the generator of
`H^2`). The Borel-Hirzebruch non-degeneracy `h^4 ≠ 0` (i.e.
`X^4 ≠ 0`) is the Mathlib fact `Polynomial.X_pow_ne_zero`
(`Polynomial ℚ` is an integral domain). -/
noncomputable instance instKaehlerClass : KaehlerClass A_EVII where
  h := (Polynomial.X : A_EVII)
  h_isAlgebraic := isAlgebraic_of_top _
  h_pow_4_ne_zero := by
    show (Polynomial.X : Polynomial ℚ) ^ 4 ≠ 0
    exact pow_ne_zero 4 Polynomial.X_ne_zero

/-! ### Lefschetz (1,1) data (starter instance) -/

/-- **Starter `Lefschetz11Data A_EVII`**: degenerate scaffolding choice
with `H^2 = H^{1,1} = ⊤`. Mathematically wrong (`H^2` should be the
degree-2 submodule, a one-dim ℚ-subspace spanned by `X`), but
inhabiting the typeclass at this stage; the Lefschetz (1,1)
algebraicity field is satisfied trivially via the `⊤` algebraicity. -/
noncomputable instance instLefschetz11Data : Lefschetz11Data A_EVII where
  H2 := (⊤ : Submodule ℚ A_EVII)
  H11 := (⊤ : Submodule ℚ A_EVII)
  H11_le_H2 := le_refl _
  lefschetz_11 := fun α _ => isAlgebraic_of_top α

/-! ### Hodge cycle data (starter instance) -/

/-- **Starter `HodgeCycleData A_EVII`**: scaffolding choice with the
Hodge subalgebra set to `⊤`. The easy-direction inclusion
`algebraic ≤ hodge` then holds trivially. Future rounds will refine
to the actual graded-piece-by-graded-piece Hodge decomposition. -/
noncomputable instance instHodgeCycleData : HodgeCycleData A_EVII where
  hodge := (⊤ : Subalgebra ℚ A_EVII)
  algebraic_le_hodge := le_top

/-! ### Concrete Freudenthal class data -/

/-- **Auxiliary algebraic Chern data** for the concrete instance.

We choose `c_1 = c_2 = c_3 = 0` and `c_4 = (1/2) • X^4`. This is the
**simplest** assignment making the Freudenthal-polynomial identity
hold: with these values,

```
-48 c_2² + 96 c_1·c_3 − 96 c_4 = 0 + 0 − 96 · (1/2) X^4 = −48 X^4
```

which matches the chosen `q := -48 • X^4`. Mathematically this is a
**placeholder** — the actual P48 Chern values for `𝓔_{+1}` are
nonzero (specifically `c_1 = 9 h`, `c_2 = 41 h^2 / 2`, `c_3 = 35 h^3`,
`c_4 = 285 h^4 / 8` per the master proof's explicit table). A later
round will replace the placeholder values with the P48 values and
verify the polynomial identity via `CrossRingArithmetic`.

The `isAlgebraic` field is discharged uniformly by `isAlgebraic_of_top`. -/
noncomputable def chernData_EVII : AlgebraicChernData A_EVII where
  c := fun i =>
    if i = 4 then ((1 : ℚ) / 2) • ((Polynomial.X : A_EVII) ^ 4)
    else 0
  isAlgebraic := fun _ => isAlgebraic_of_top _

/-- **Concrete `FreudenthalClassData A_EVII`**: the Freudenthal class
`q := -48 • X^4`, equipped with witnesses for both the Chern-class
polynomial identity and the Kähler-class proportionality. Both
identities reduce to ring arithmetic in `Polynomial ℚ` and are
discharged by `ring_nf` / `simp` / `norm_num`. -/
noncomputable def freudenthalClassData_EVII : FreudenthalClassData A_EVII where
  chern := chernData_EVII
  q := (-48 : ℚ) • ((Polynomial.X : A_EVII) ^ 4)
  q_eq_chern_poly := by
    -- Goal: q = (-48) • (c_2 * c_2) + 96 • (c_1 * c_3) - 96 • c_4
    -- With chernData_EVII: c_1 = c_2 = c_3 = 0, c_4 = (1/2) • X^4
    -- RHS = 0 + 0 - 96 • ((1/2) • X^4) = -48 • X^4 = q ✓
    show (-48 : ℚ) • ((Polynomial.X : A_EVII) ^ 4)
      = (-48 : ℚ) • (chernData_EVII.c 2 * chernData_EVII.c 2)
        + (96 : ℚ) • (chernData_EVII.c 1 * chernData_EVII.c 3)
        - (96 : ℚ) • chernData_EVII.c 4
    have hc1 : chernData_EVII.c 1 = 0 := by
      show (if (1 : ℕ) = 4 then ((1 : ℚ) / 2) • ((Polynomial.X : A_EVII) ^ 4) else 0) = 0
      rw [if_neg (by decide : (1 : ℕ) ≠ 4)]
    have hc2 : chernData_EVII.c 2 = 0 := by
      show (if (2 : ℕ) = 4 then ((1 : ℚ) / 2) • ((Polynomial.X : A_EVII) ^ 4) else 0) = 0
      rw [if_neg (by decide : (2 : ℕ) ≠ 4)]
    have hc3 : chernData_EVII.c 3 = 0 := by
      show (if (3 : ℕ) = 4 then ((1 : ℚ) / 2) • ((Polynomial.X : A_EVII) ^ 4) else 0) = 0
      rw [if_neg (by decide : (3 : ℕ) ≠ 4)]
    have hc4 : chernData_EVII.c 4 = ((1 : ℚ) / 2) • ((Polynomial.X : A_EVII) ^ 4) := by
      show (if (4 : ℕ) = 4 then ((1 : ℚ) / 2) • ((Polynomial.X : A_EVII) ^ 4) else 0)
        = ((1 : ℚ) / 2) • ((Polynomial.X : A_EVII) ^ 4)
      rw [if_pos rfl]
    rw [hc1, hc2, hc3, hc4]
    -- Goal: (-48) • X^4 = (-48) • (0 * 0) + 96 • (0 * 0) - 96 • ((1/2) • X^4)
    -- Simplify zero products and combine the nested scalar action `96 • ((1/2) • X^4)`
    -- into `(96 * 1/2) • X^4 = 48 • X^4`, then close by `module`.
    simp only [mul_zero, smul_zero, zero_add, smul_smul]
    module
  q_eq_neg_48_h_pow_4 := by
    -- Goal: q = (-48) • h^4, where h = X by `instKaehlerClass`.
    -- Both `KaehlerClass.h` (via `instKaehlerClass`) and `q` unfold to
    -- `Polynomial.X`-based expressions; reduce by `rfl`.
    rfl

/-! ### Sanity-check theorem: HC closure on the concrete instance -/

/-- **Sanity-check theorem**: the abstract universal-quantification
form of `HC_for_freudenthal_quartic_on_EVII_UNCONDITIONAL`
specialises to the concrete instance.

The Main Theorem in `HodgeReduction.Strict` is

```
theorem HC_for_freudenthal_quartic_on_EVII_UNCONDITIONAL :
  HC_for_freudenthal_quartic_on_EVII :=
  paper_HC_equals_algebraicity_OPEN
    (polynomial_in_chern_classes_is_algebraic_OPEN
      polynomial_identity_freudenthal_DIRECT)
```

where the unfolded type is

```
∀ (A : Type) [CommRing A] [Algebra ℚ A]
  [CohomologyRing A] [KaehlerClass A]
  (fcd : FreudenthalClassData A), IsAlgebraic fcd.q.
```

Specialising to `A := A_EVII` and `fcd := freudenthalClassData_EVII`
yields the concrete-instance conclusion that the Freudenthal class
`q = -48 X^4` is algebraic in `H^*(Ě_VII; ℚ)`.

This is the first **concrete** witness that the framework closure
is non-vacuous: there exists at least one (carrier, instances, data)
quadruple for which the universally-quantified hypothesis can be
applied. -/
theorem HC_for_Concrete_EVII :
    CohomologyRing.IsAlgebraic freudenthalClassData_EVII.q :=
  HodgeReduction.Strict.HC_for_freudenthal_quartic_on_EVII_UNCONDITIONAL
    A_EVII freudenthalClassData_EVII

/-! ### Diagnostic: axiom dependencies of the concrete-instance closure -/

-- Uncomment to inspect axiom dependencies at the concrete-instance level.
-- Expected: same minimal axiom set as the abstract theorem, i.e.
--   `[propext, Classical.choice, Quot.sound]` (kernel-pure).
-- #print axioms HC_for_Concrete_EVII

end HodgeReduction.Concrete
