/-
Copyright (c) 2026 Alex Chengyu Li. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.RingTheory.Adjoin.Polynomial
import Mathlib.Algebra.Polynomial.Eval.Defs
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Tactic.LinearCombination
import HodgeReduction.Strict
import HodgeReduction.CrossRingArithmetic
import HodgeReduction.Infrastructure.Cohomology.Basic
import HodgeReduction.Infrastructure.Cohomology.ChernClasses
import HodgeReduction.Infrastructure.Cohomology.AlgebraicBundle
import HodgeReduction.Infrastructure.Cohomology.KaehlerClass
import HodgeReduction.Infrastructure.Cohomology.FreudenthalClass
import HodgeReduction.Infrastructure.Cohomology.Lefschetz
import HodgeReduction.Infrastructure.Cohomology.HodgeCycle
import HodgeReduction.Infrastructure.Cohomology.HodgeRefinementCarriers

/-!
# Concrete EVII cohomology carrier (R5-A: P48-Chern upgrade)

This file gives the **first concrete instance** of the abstract HC
framework: a Lean type `A_EVII` modelling (a simplification of) the
rational cohomology ring of the compact dual `Ě_VII` of the EVII
Shimura variety, together with concrete instances of every typeclass
the framework requires to derive HC for the Freudenthal quartic on
EVII via `HC_for_freudenthal_quartic_on_EVII_UNCONDITIONAL`.

## Carrier choice

Mathematically, `H^*(Ě_VII; ℚ)` is a graded `ℚ`-algebra generated by
the Kähler class `h ∈ H^2`, with Poincaré polynomial
`(1-t^{20})(1-t^{28})(1-t^{36}) / [(1-t^2)(1-t^{10})(1-t^{18})]`. As
a graded ring it is `ℚ[h] / (relations in degree ≥ 28)`.

For the **R5-A upgrade** we keep the carrier `Polynomial ℚ` (which
is graded by polynomial degree and admits the full Mathlib
infrastructure) but **replace every typeclass field placeholder with
a real-content witness**:

* `algebraic` is now `Algebra.adjoin ℚ {X}` — the `ℚ`-subalgebra
  generated by the polarisation class `h = X`. (By
  `Polynomial.adjoin_X` this equals `⊤`, but the *form* now exhibits
  algebraicity as adjunction of the polarisation, not by fiat.)
* `H2` and `H11` are now `Submodule.span ℚ {X}` — the genuine
  one-dimensional degree-2 piece, matching `b_2(Ě_VII) = 1` and the
  Hermitian-symmetric identification `H^{1,1} = H^2`.
* `hodge` is the same `Algebra.adjoin ℚ {X}` (since `Ě_VII` admits
  a Białynicki-Birula decomposition with only even-codim cells, the
  full cohomology equals the union of `(p,p)`-pieces).
* The Chern data uses the **P48 explicit ℚ-coefficients**
  `c_1 = -9 h, c_2 = 41 h², c_3 = -125 h³, c_4 = 285 h⁴`
  (`HodgeReduction.CrossRingArithmetic.c1/c2/c3/c4`), no longer the
  R1 placeholder `c_1 = c_2 = c_3 = 0, c_4 = (1/2)·X^4`.
* `q := -48 X^4` is unchanged. The Chern-polynomial identity
  `q = -48 c_2² + 96 c_1 c_3 - 96 c_4` is now the substantive
  polynomial identity `−48·(41)² + 96·(−9)·(−125) − 96·(285) = −48`
  (= `polynomial_identity_value`), discharged by `ring` after
  unfolding.

## What this file provides

* `A_EVII : Type` — the carrier (`Polynomial ℚ`).
* `instance : CommRing A_EVII` — from Mathlib.
* `instance : Algebra ℚ A_EVII` — from Mathlib.
* `instance : CohomologyRing A_EVII` — `algebraic := adjoin ℚ {X}`.
* `instance : KaehlerClass A_EVII` — `h := X`, algebraicity via adjoin.
* `instance : Lefschetz11Data A_EVII` — `H2 = H11 = span ℚ {X}`,
  Lefschetz (1,1) via scalar multiples of an algebraic generator.
* `instance : HodgeCycleData A_EVII` — `hodge := adjoin ℚ {X}`.
* `chernData_EVII : AlgebraicChernData A_EVII` — P48 values.
* `bundleEplus1_EVII : AlgebraicVectorBundle A_EVII` — rank-27
  algebraic bundle with the P48 Chern classes.
* `freudenthalClassData_EVII : FreudenthalClassData A_EVII` — the
  Freudenthal class `q = -48 X^4`, with the P48-Chern polynomial
  identity discharged via `polynomial_identity_value`.
* `instance : FreudenthalChernSubalgebraPlacementData _
  freudenthalClassData_EVII` — placement of `q` in the Chern subalgebra.
* `HC_for_Concrete_EVII_Freudenthal` — sanity-check theorem (alias of
  `HC_for_Concrete_EVII`).

## Tags

EVII Shimura variety, concrete instance, Freudenthal quartic,
P48 Chern values, polarisation class, ℚ-subalgebra adjoin
-/

namespace HodgeReduction.Concrete

open HodgeReduction.Infrastructure.Cohomology
open Polynomial

/-! ### The carrier -/

/-- **Concrete EVII cohomology carrier**.

Mathematically intended to model `H^*(Ě_VII; ℚ) ≃ ℚ[h] / (relations)`,
realised concretely as `Polynomial ℚ`. The grading by polynomial
degree corresponds to the cohomological grading; the Kähler class
`h` is identified with `Polynomial.X`. -/
abbrev A_EVII : Type := Polynomial ℚ

/-! ### Ring and algebra instances (free from Mathlib) -/

-- `CommRing A_EVII` and `Algebra ℚ A_EVII` are inherited from the
-- canonical `Polynomial ℚ` instances via the `abbrev` definition.

/-! ### CohomologyRing instance -/

/-- **Concrete `CohomologyRing A_EVII`**.

The algebraic subalgebra is `Algebra.adjoin ℚ {X}` — the
`ℚ`-subalgebra generated by the polarisation class `h = X`. By
`Polynomial.adjoin_X` this set-theoretically equals `⊤`, but the
adjunction form expresses the *content* of algebraicity: every class
arises from the polarisation by ring-theoretic operations and rational
scaling. This matches the geometric fact that `H^*(Ě_VII; ℚ)` is
generated as a `ℚ`-algebra by `h = c_1(L_amp)`. -/
noncomputable instance instCohomologyRing : CohomologyRing A_EVII where
  algebraic := Algebra.adjoin ℚ ({(Polynomial.X : A_EVII)} : Set A_EVII)

/-- The polarisation class `X` is in the algebraic subalgebra
(by `Algebra.subset_adjoin` applied to the singleton generating set). -/
theorem X_isAlgebraic : CohomologyRing.IsAlgebraic (Polynomial.X : A_EVII) :=
  Algebra.subset_adjoin (Set.mem_singleton _)

/-- Every element of `A_EVII` is algebraic (since
`Algebra.adjoin ℚ {X} = ⊤` in `Polynomial ℚ` by `Polynomial.adjoin_X`).
This is the workhorse lemma used to discharge Lefschetz/Hodge
membership goals. -/
theorem isAlgebraic_of_adjoin_X (α : A_EVII) :
    CohomologyRing.IsAlgebraic α := by
  show α ∈ Algebra.adjoin ℚ ({(Polynomial.X : A_EVII)} : Set A_EVII)
  rw [Polynomial.adjoin_X]
  exact Algebra.mem_top

/-! ### KaehlerClass instance -/

/-- **Concrete `KaehlerClass A_EVII`**: the Kähler class is
`h := X`. Algebraicity is `X_isAlgebraic` (membership in the
generating singleton). The Borel-Hirzebruch non-degeneracy `h^4 ≠ 0`
is `Polynomial.X_ne_zero` + `pow_ne_zero` (`Polynomial ℚ` is an
integral domain). -/
noncomputable instance instKaehlerClass : KaehlerClass A_EVII where
  h := (Polynomial.X : A_EVII)
  h_isAlgebraic := X_isAlgebraic
  h_pow_4_ne_zero := pow_ne_zero 4 Polynomial.X_ne_zero

/-! ### Lefschetz (1,1) data -/

/-- **Concrete `Lefschetz11Data A_EVII`**: `H^2 = H^{1,1} = ℚ·X`.

* `H2 := Submodule.span ℚ {X}` — the genuine one-dimensional
  degree-2 cohomology (`b_2(Ě_VII) = 1`).
* `H11 := H2` — for a Hermitian-symmetric variety the entire `H^2`
  is of type `(1,1)` (since `H^{2,0} = H^{0,2} = 0`).
* `lefschetz_11`: every element of `ℚ·X` equals `r • X` for some
  `r : ℚ` (`Submodule.mem_span_singleton`) and is therefore algebraic
  via `isAlgebraic_smul` applied to `X_isAlgebraic`. -/
noncomputable instance instLefschetz11Data : Lefschetz11Data A_EVII where
  H2 := Submodule.span ℚ ({(Polynomial.X : A_EVII)} : Set A_EVII)
  H11 := Submodule.span ℚ ({(Polynomial.X : A_EVII)} : Set A_EVII)
  H11_le_H2 := le_refl _
  lefschetz_11 := by
    intro α hα
    rcases Submodule.mem_span_singleton.mp hα with ⟨r, rfl⟩
    exact CohomologyRing.isAlgebraic_smul r X_isAlgebraic

/-! ### Hodge cycle data -/

/-- **Concrete `HodgeCycleData A_EVII`**: `hodge := Algebra.adjoin ℚ {X}`.

Mathematically, `Ě_VII` admits a Białynicki-Birula decomposition with
only even-codimensional cells, so every cohomology class is of
type `(p,p)` for some `p`, i.e. the entire cohomology ring is the
union of Hodge `(p,p)`-pieces. The Hodge subalgebra therefore
coincides with the algebraic subalgebra (both equal `adjoin ℚ {X}`).
The `algebraic_le_hodge` inclusion is then reflexive. -/
noncomputable instance instHodgeCycleData : HodgeCycleData A_EVII where
  hodge := Algebra.adjoin ℚ ({(Polynomial.X : A_EVII)} : Set A_EVII)
  algebraic_le_hodge := le_refl _

/-! ### Concrete Chern data with P48 explicit ℚ-coefficients -/

/-- **P48 Chern data** for the rank-27 Hodge sub-bundle `𝓔_{+1}` on EVII.

`HodgeReduction.CrossRingArithmetic` (proved kernel-pure by `norm_num`)
provides the four explicit ℚ-coefficients
`c_1 = -9, c_2 = 41, c_3 = -125, c_4 = 285`. We package them as
elements of the cohomology ring `A_EVII`:
* `c_1 = -9 · X` (degree 2)
* `c_2 = 41 · X²` (degree 4)
* `c_3 = -125 · X³` (degree 6)
* `c_4 = 285 · X⁴` (degree 8)
* `c_0 = 1` (the unit class, `c_0(E) = 1` for any vector bundle)
* `c_i = 0` for `i ≥ 5` (vanishing above rank ... well, above the four
  Chern classes that enter the Freudenthal-polynomial identity; the
  rank-27 bundle has higher Chern classes too, but only `c_1, …, c_4`
  are load-bearing here).

Each `c_i` lies in `Algebra.adjoin ℚ {X}` (powers of `X` adjoined to
ℚ-scalars), hence is algebraic. -/
noncomputable def chernData_EVII : AlgebraicChernData A_EVII where
  c
  | 0 => 1
  | 1 => HodgeReduction.CrossRingArithmetic.c1 • (Polynomial.X : A_EVII)
  | 2 => HodgeReduction.CrossRingArithmetic.c2 • ((Polynomial.X : A_EVII) ^ 2)
  | 3 => HodgeReduction.CrossRingArithmetic.c3 • ((Polynomial.X : A_EVII) ^ 3)
  | 4 => HodgeReduction.CrossRingArithmetic.c4 • ((Polynomial.X : A_EVII) ^ 4)
  | _ + 5 => 0
  isAlgebraic := fun _ => isAlgebraic_of_adjoin_X _

/-- **Closed-form values of the P48 Chern data**, useful for unfolding
in the polynomial-identity proof. Each lemma is `rfl` because
`chernData_EVII.c` is defined by pattern matching on the literal
indices `0, 1, 2, 3, 4`. -/
theorem chernData_EVII_c0 : chernData_EVII.c 0 = 1 := rfl

theorem chernData_EVII_c1 :
    chernData_EVII.c 1
      = HodgeReduction.CrossRingArithmetic.c1 • (Polynomial.X : A_EVII) := rfl

theorem chernData_EVII_c2 :
    chernData_EVII.c 2
      = HodgeReduction.CrossRingArithmetic.c2 • ((Polynomial.X : A_EVII) ^ 2) := rfl

theorem chernData_EVII_c3 :
    chernData_EVII.c 3
      = HodgeReduction.CrossRingArithmetic.c3 • ((Polynomial.X : A_EVII) ^ 3) := rfl

theorem chernData_EVII_c4 :
    chernData_EVII.c 4
      = HodgeReduction.CrossRingArithmetic.c4 • ((Polynomial.X : A_EVII) ^ 4) := rfl

/-! ### Algebraic vector bundle wrapper

The P48 Chern data is the Chern data of an algebraic vector bundle —
the Hodge sub-bundle `𝓔_{+1}` of rank 27 on EVII. We package this as
an `AlgebraicVectorBundle` instance for downstream use; it tracks the
rank and the `c_0 = 1` convention. -/

/-- **The rank-27 algebraic vector bundle `𝓔_{+1}`** on the EVII
compact dual, with its P48 Chern classes. -/
noncomputable def bundleEplus1_EVII : AlgebraicVectorBundle A_EVII where
  rank := 27
  chern := chernData_EVII.c
  chern_zero := chernData_EVII_c0
  chern_above_rank := by
    intro i hi
    -- `i > 27 ⟹ i ≥ 28 ⟹ i ≥ 5`. Rewrite `i = k + 5` for some `k : ℕ`
    -- and reduce via the `_ + 5 => 0` pattern-match branch of `c`.
    obtain ⟨k, rfl⟩ : ∃ k, i = k + 5 := ⟨i - 5, by omega⟩
    rfl
  chern_isAlgebraic := chernData_EVII.isAlgebraic

/-! ### Concrete Freudenthal class data

The Freudenthal class `q = -48 X^4` together with both witnesses:
* the **Chern-polynomial identity** `q = -48 c_2² + 96 c_1 c_3 - 96 c_4`,
  reduced via the P48 explicit values to the kernel-checked identity
  `-48·41² + 96·(-9)·(-125) - 96·285 = -48` (`polynomial_identity_value`);
* the **Kähler-class proportionality** `q = -48 · h^4`, definitional
  given `h := X`. -/

noncomputable def freudenthalClassData_EVII : FreudenthalClassData A_EVII where
  chern := chernData_EVII
  q := (-48 : ℚ) • ((Polynomial.X : A_EVII) ^ 4)
  q_eq_chern_poly := by
    -- Substitute the P48 explicit Chern values (recorded by the
    -- `chernData_EVII_cᵢ` lemmas). Then collapse the smul-mul cross terms
    -- via `smul_mul_smul_comm` and `pow_succ` so that both sides are
    -- ℚ-scalar multiples of `X^4`. The resulting scalar identity
    -- `-48·41² + 96·(-9)·(-125) - 96·285 = -48`
    -- = `HodgeReduction.CrossRingArithmetic.polynomial_identity_value`
    -- is decided by `norm_num` after collapsing nested `smul`s.
    rw [chernData_EVII_c1, chernData_EVII_c2, chernData_EVII_c3, chernData_EVII_c4]
    -- Goal: (-48) • X^4 =
    --   (-48) • ((c2 • X²) * (c2 • X²)) + 96 • ((c1 • X) * (c3 • X³))
    --     - 96 • (c4 • X^4)
    -- Collapse smul-mul cross terms: `(r • a) * (s • b) = (r * s) • (a * b)`.
    simp only [smul_mul_smul_comm, smul_smul]
    -- Goal: (-48) • X^4 =
    --   ((-48) * (c2 * c2)) • (X² * X²) + (96 * (c1 * c3)) • (X * X³)
    --     - (96 * c4) • X^4
    -- Combine the polynomial monomials `X² * X² = X * X³ = X^4`.
    have hX22 : ((Polynomial.X : A_EVII) ^ 2) * ((Polynomial.X : A_EVII) ^ 2)
        = (Polynomial.X : A_EVII) ^ 4 := by ring
    have hX13 : (Polynomial.X : A_EVII) * ((Polynomial.X : A_EVII) ^ 3)
        = (Polynomial.X : A_EVII) ^ 4 := by ring
    rw [hX22, hX13]
    -- Goal: (-48) • X^4 =
    --   ((-48) * (c2 * c2)) • X^4 + (96 * (c1 * c3)) • X^4
    --     - (96 * c4) • X^4
    -- Combine into a single scalar via `add_smul`/`sub_smul`.
    rw [← add_smul, ← sub_smul]
    -- Goal: (-48) • X^4 = ((-48) * (c2 * c2) + 96 * (c1 * c3) - 96 * c4) • X^4
    -- The scalar identity `-48 = (-48) * c2² + 96 * c1 * c3 - 96 * c4`
    -- is `polynomial_identity_value` (proved kernel-pure by `norm_num`).
    congr 1
    -- Goal: (-48 : ℚ) = (-48) * (c2 * c2) + 96 * (c1 * c3) - 96 * c4
    -- Reverse and convert `c2 * c2` ↔ `c2 ^ 2`, then close via
    -- `polynomial_identity_value` (proved kernel-pure by `norm_num`).
    have h := HodgeReduction.CrossRingArithmetic.polynomial_identity_value
    -- `h : -48 * c2^2 + 96 * c1 * c3 - 96 * c4 = -48`.
    linear_combination -h
  q_eq_neg_48_h_pow_4 := by
    -- Goal: q = (-48) • h^4. Both sides unfold to the same expression
    -- in `Polynomial.X`, so reduce by `rfl`.
    rfl

/-! ### Freudenthal Chern-subalgebra placement instance -/

/-- **Concrete `FreudenthalChernSubalgebraPlacementData`**: the
Freudenthal class `q = -48 X^4` lies in the `ℚ`-subalgebra generated
by the Chern classes of `𝓔_{+1}`.

Proof: `q = -48 c_2² + 96 c_1 c_3 - 96 c_4` (the typeclass field
`q_eq_chern_poly` of `freudenthalClassData_EVII`). Each `c_i` is in
`Set.range chern.c`, hence in `Algebra.adjoin ℚ (Set.range chern.c)`;
the adjoin is closed under sum, product, and rational scaling, so the
linear combination is also a member. -/
noncomputable instance instFreudenthalChernSubalgebraPlacementData :
    FreudenthalChernSubalgebraPlacementData (A := A_EVII)
      freudenthalClassData_EVII where
  placement_holds := by
    -- Use `q_eq_chern_poly` to rewrite `q` in terms of `c_1, c_2, c_3, c_4`,
    -- then close by the closure of `Algebra.adjoin` under the ring operations
    -- and ℚ-scalar action, using `subset_adjoin` for each `c_i`.
    rw [freudenthalClassData_EVII.q_eq_chern_poly]
    -- The target is now `(-48) • (c2 * c2) + 96 • (c1 * c3) - 96 • c4 ∈
    -- Algebra.adjoin ℚ (Set.range chern.c)`.
    -- Each `c_i = chern.c i ∈ Set.range chern.c ⊆ Algebra.adjoin _ _`.
    -- The adjoin is a `Subalgebra` so it is closed under the ring
    -- operations (`mul_mem`, `add_mem`, `sub_mem`) and the ℚ-scalar
    -- action (`smul_mem`).
    have hc1 :
        freudenthalClassData_EVII.chern.c 1
          ∈ Algebra.adjoin ℚ (Set.range freudenthalClassData_EVII.chern.c) :=
      Algebra.subset_adjoin (Set.mem_range_self 1)
    have hc2 :
        freudenthalClassData_EVII.chern.c 2
          ∈ Algebra.adjoin ℚ (Set.range freudenthalClassData_EVII.chern.c) :=
      Algebra.subset_adjoin (Set.mem_range_self 2)
    have hc3 :
        freudenthalClassData_EVII.chern.c 3
          ∈ Algebra.adjoin ℚ (Set.range freudenthalClassData_EVII.chern.c) :=
      Algebra.subset_adjoin (Set.mem_range_self 3)
    have hc4 :
        freudenthalClassData_EVII.chern.c 4
          ∈ Algebra.adjoin ℚ (Set.range freudenthalClassData_EVII.chern.c) :=
      Algebra.subset_adjoin (Set.mem_range_self 4)
    refine Subalgebra.sub_mem _ (Subalgebra.add_mem _ ?_ ?_) ?_
    · exact Subalgebra.smul_mem _ (Subalgebra.mul_mem _ hc2 hc2) (-48 : ℚ)
    · exact Subalgebra.smul_mem _ (Subalgebra.mul_mem _ hc1 hc3) (96 : ℚ)
    · exact Subalgebra.smul_mem _ hc4 (96 : ℚ)

/-! ### Sanity-check theorem: HC closure on the concrete instance -/

/-- **Sanity-check theorem**: the abstract universal-quantification form
of `HC_for_freudenthal_quartic_on_EVII_UNCONDITIONAL` specialises to
the concrete instance.

The Main Theorem in `HodgeReduction.Strict` is

```
theorem HC_for_freudenthal_quartic_on_EVII_UNCONDITIONAL :
  HC_for_freudenthal_quartic_on_EVII :=
  paper_HC_equals_algebraicity_OPEN
    (polynomial_in_chern_classes_is_algebraic_OPEN
      polynomial_identity_freudenthal_DIRECT)
```

where the unfolded type is

```
∀ (A : Type) [CommRing A] [Algebra ℚ A]
  [CohomologyRing A] [KaehlerClass A]
  (fcd : FreudenthalClassData A), IsAlgebraic fcd.q.
```

Specialising to `A := A_EVII` and `fcd := freudenthalClassData_EVII`
yields the concrete-instance conclusion that the Freudenthal class
`q = -48 X^4` is algebraic in `H^*(Ě_VII; ℚ)`. -/
theorem HC_for_Concrete_EVII :
    CohomologyRing.IsAlgebraic freudenthalClassData_EVII.q :=
  HodgeReduction.Strict.HC_for_freudenthal_quartic_on_EVII_UNCONDITIONAL
    A_EVII freudenthalClassData_EVII

/-- **Alias**: the same closure derived directly through the concrete
typeclass. This is the version requested in the R5-A brief and makes the
shape of the conclusion (`IsAlgebraic q` of the *concrete* `q`)
explicit. -/
theorem HC_for_Concrete_EVII_Freudenthal :
    CohomologyRing.IsAlgebraic (freudenthalClassData_EVII.q : A_EVII) :=
  freudenthalClassData_EVII.isAlgebraic

/-! ### Diagnostic: axiom dependencies of the concrete-instance closure -/

-- Uncomment to inspect axiom dependencies at the concrete-instance level.
-- Expected: same minimal axiom set as the abstract theorem, i.e.
--   `[propext, Classical.choice, Quot.sound]` (kernel-pure).
-- #print axioms HC_for_Concrete_EVII
-- #print axioms HC_for_Concrete_EVII_Freudenthal

end HodgeReduction.Concrete
