/-
Copyright (c) 2026 Alex Chengyu Li. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import HodgeReduction.Infrastructure.Cohomology.Basic
import HodgeReduction.Infrastructure.Cohomology.ChernClasses

/-!
# Classifying-space cohomology presentations (BE_6, BE_7, B(E_6 × U(1)))

For a compact connected Lie group `G`, the rational cohomology
`H^*(BG; ℚ)` of its classifying space is a polynomial algebra on
generators of even degree (Borel 1953). For the exceptional groups:

* `H^*(BE_6; ℚ) = ℚ[c_2, c_5, c_6, c_8, c_9, c_{12}]` — generated
  by the Chern classes of the **27-dimensional minuscule
  representation** `V_27` (Toda 1975, *On the cohomology of classifying
  spaces of exceptional Lie groups*).
* `H^*(BE_7; ℚ) = ℚ[c_2, c_6, c_8, c_{10}, c_{12}, c_{14}, c_{18}]` —
  generated by the Chern classes of the **56-dimensional minuscule
  representation** `V_56` (Kono-Mimura 1976, *Cohomology mod 2 of the
  classifying space of compact connected Lie group of type E_7*).
* `H^*(B(E_6 × U(1)); ℚ) = H^*(BE_6; ℚ) ⊗ ℚ[t]` — polynomial on the
  `V_27` Chern classes together with the `U(1)`-character `t = c_1`
  (Borel-Hirzebruch 1958-60 I §13-15, II §28-30; Toda 1975).

For the Hodge-conjecture reduction on EVII, these presentations are
load-bearing in two places:

* **§3.3 (P53-P57 cross-ring)**: the cohomology of the compact dual
  `Ě_VII = E_{7,C}/P_7` is computed as the coinvariant algebra
  `H^*(B(E_6 × U(1)); ℚ) / (H^*(BE_7; ℚ)^+)`, and this requires the
  `BE_7`/`B(E_6 × U(1))` presentations to be polynomial on Chern
  classes of the respective minuscule representations.
* **§3.4.2 (P39 augmentation phenomenon)**: the Freudenthal class
  `[q]` lives in the augmentation ideal of the coinvariant algebra
  precisely because `q` is `W(E_7)`-invariant of degree 4, and the
  coinvariant presentation lets us compute `[q]` via Chern-class
  arithmetic in the polynomial algebras.

## Abstraction strategy

Rather than defining `BE_6`, `BE_7`, `B(E_6 × U(1))` as concrete
topological spaces (which would require all of Mathlib's algebraic
topology + Lie group cohomology), we abstract the **load-bearing
content** that the Hodge-reduction proof actually consumes:

* The cohomology ring `A` (the abstract `CohomologyRing` of the
  classifying space).
* A designated `ChernData` (the Chern classes of the relevant
  minuscule representation).
* The **generation property**: the Chern classes generate `A` as
  a `ℚ`-algebra (`Algebra.adjoin` of their image equals the top).

The fact that this `ChernData` IS the Chern classes of `V_27` / `V_56`
(rather than some other set of cohomology classes) is the
representation-theoretic content of Toda 1975 / Kono-Mimura 1976
/ Borel-Hirzebruch 1958; the Lean-level claim records the abstract
polynomial-generation property the downstream Hodge-reduction
argument actually consumes.

## Main definitions

* `ClassifyingSpaceData A V` : typeclass packaging a designated
  `ChernData` (representing Chern classes of representation `V`)
  on `A`, together with the polynomial-generation property of `A`
  as a `ℚ`-algebra.
* `ClassifyingSpaceData.generates` : the universal-quantified
  algebraic statement that every element of `A` is in
  `Algebra.adjoin ℚ` of the Chern classes.

## Tags

classifying space, BE_6, BE_7, Borel-Hirzebruch, Toda, Kono-Mimura,
minuscule representation, Chern class, polynomial cohomology
-/

namespace HodgeReduction.Infrastructure.Cohomology

variable (A : Type*) [CommRing A] [Algebra ℚ A] [CohomologyRing A]

/-- **Classifying-space cohomology data** for a cohomology ring `A`
viewed as `H^*(BG; ℚ)` for some Lie group `G`, together with a
designated finite list of Chern classes (of some representation `V`
of `G`) that **polynomially generate** `A`.

For the Hodge-reduction application this is instantiated three times:

* `G = E_6`, `V = V_27` → Toda 1975 generation.
* `G = E_7`, `V = V_56` → Kono-Mimura 1976 generation.
* `G = E_6 × U(1)`, `V = V_27 ⊕ (one-dim character)` →
  Borel-Hirzebruch 1958-60 polynomial presentation.

The typeclass packages BOTH the Chern-class data and the abstract
generation property as `Algebra.adjoin` membership. -/
class ClassifyingSpaceData where
  /-- The Chern classes of the chosen representation `V`. -/
  chernGenerators : ChernData A
  /-- The Chern classes **polynomially generate** the cohomology ring:
  every element of `A` lies in the `ℚ`-subalgebra generated by the
  image of `chernGenerators.c`. This IS the polynomial-generation
  content of Toda 1975 / Kono-Mimura 1976 / Borel-Hirzebruch. -/
  chernGenerators_adjoin :
    Algebra.adjoin ℚ (Set.range chernGenerators.c) = (⊤ : Subalgebra ℚ A)

namespace ClassifyingSpaceData

variable {A} [ClassifyingSpaceData A]

/-- The Chern-class generators of the classifying-space cohomology. -/
def c (i : ℕ) : A := (chernGenerators (A := A)).c i

/-- **Generation lemma**: every element of `A` is in the `ℚ`-subalgebra
generated by the Chern classes. This is the load-bearing consequence
of Toda 1975 / Kono-Mimura 1976 / Borel-Hirzebruch consumed by the
downstream Hodge-reduction argument. -/
theorem mem_adjoin_chern (α : A) :
    α ∈ Algebra.adjoin ℚ (Set.range (chernGenerators (A := A)).c) := by
  rw [chernGenerators_adjoin]
  trivial

end ClassifyingSpaceData

end HodgeReduction.Infrastructure.Cohomology
