/-
Copyright (c) 2026 Alex Chengyu Li. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import HodgeReduction.Infrastructure.Cohomology.Basic
import HodgeReduction.Infrastructure.Cohomology.ChernClasses

/-!
# Classifying-space cohomology presentations (BE_6, BE_7, B(E_6 × U(1)))

For a compact connected Lie group `G`, the rational cohomology
`H^*(BG; ℚ)` of its classifying space is a polynomial algebra on
generators of even degree (Borel 1953). For the exceptional groups:

* `H^*(BE_6; ℚ) = ℚ[c_2, c_5, c_6, c_8, c_9, c_{12}]` — generated
  by the Chern classes of the **27-dimensional minuscule
  representation** `V_27` (Toda 1975, *On the cohomology of classifying
  spaces of exceptional Lie groups*).
* `H^*(BE_7; ℚ) = ℚ[c_2, c_6, c_8, c_{10}, c_{12}, c_{14}, c_{18}]` —
  generated by the Chern classes of the **56-dimensional minuscule
  representation** `V_56` (Kono-Mimura 1976, *Cohomology mod 2 of the
  classifying space of compact connected Lie group of type E_7*).
* `H^*(B(E_6 × U(1)); ℚ) = H^*(BE_6; ℚ) ⊗ ℚ[t]` — polynomial on the
  `V_27` Chern classes together with the `U(1)`-character `t = c_1`
  (Borel-Hirzebruch 1958-60 I §13-15, II §28-30; Toda 1975).

For the Hodge-conjecture reduction on EVII, these presentations are
load-bearing in two places:

* **§3.3 (P53-P57 cross-ring)**: the cohomology of the compact dual
  `Ě_VII = E_{7,C}/P_7` is computed as the coinvariant algebra
  `H^*(B(E_6 × U(1)); ℚ) / (H^*(BE_7; ℚ)^+)`, and this requires the
  `BE_7`/`B(E_6 × U(1))` presentations to be polynomial on Chern
  classes of the respective minuscule representations.
* **§3.4.2 (P39 augmentation phenomenon)**: the Freudenthal class
  `[q]` lives in the augmentation ideal of the coinvariant algebra
  precisely because `q` is `W(E_7)`-invariant of degree 4, and the
  coinvariant presentation lets us compute `[q]` via Chern-class
  arithmetic in the polynomial algebras.

## Abstraction strategy

Rather than defining `BE_6`, `BE_7`, `B(E_6 × U(1))` as concrete
topological spaces (which would require all of Mathlib's algebraic
topology + Lie group cohomology), we abstract the **load-bearing
content** that the Hodge-reduction proof actually consumes:

* The cohomology ring `A` (the abstract `CohomologyRing` of the
  classifying space).
* A designated `ChernData` (the Chern classes of the relevant
  minuscule representation).
* The **generation property**: the Chern classes generate `A` as
  a `ℚ`-algebra (`Algebra.adjoin` of their image equals the top).

The fact that this `ChernData` IS the Chern classes of `V_27` / `V_56`
(rather than some other set of cohomology classes) is the
representation-theoretic content of Toda 1975 / Kono-Mimura 1976
/ Borel-Hirzebruch 1958; the Lean-level claim records the abstract
polynomial-generation property the downstream Hodge-reduction
argument actually consumes.

## Main definitions

* `ClassifyingSpaceData A V` : typeclass packaging a designated
  `ChernData` (representing Chern classes of representation `V`)
  on `A`, together with the polynomial-generation property of `A`
  as a `ℚ`-algebra.
* `ClassifyingSpaceData.generates` : the universal-quantified
  algebraic statement that every element of `A` is in
  `Algebra.adjoin ℚ` of the Chern classes.

## Tags

classifying space, BE_6, BE_7, Borel-Hirzebruch, Toda, Kono-Mimura,
minuscule representation, Chern class, polynomial cohomology
-/

namespace HodgeReduction.Infrastructure.Cohomology

variable (A : Type*) [CommRing A] [Algebra ℚ A] [CohomologyRing A]

/-- **Classifying-space cohomology data** for a cohomology ring `A`
viewed as `H^*(BG; ℚ)` for some Lie group `G`, together with a
designated finite list of Chern classes (of some representation `V`
of `G`) that **polynomially generate** `A`.

For the Hodge-reduction application this is instantiated three times:

* `G = E_6`, `V = V_27` → Toda 1975 generation.
* `G = E_7`, `V = V_56` → Kono-Mimura 1976 generation.
* `G = E_6 × U(1)`, `V = V_27 ⊕ (one-dim character)` →
  Borel-Hirzebruch 1958-60 polynomial presentation.

The typeclass packages BOTH the Chern-class data and the abstract
generation property as `Algebra.adjoin` membership. -/
class ClassifyingSpaceData where
  /-- The Chern classes of the chosen representation `V`. -/
  chernGenerators : ChernData A
  /-- The Chern classes **polynomially generate** the cohomology ring:
  every element of `A` lies in the `ℚ`-subalgebra generated by the
  image of `chernGenerators.c`. This IS the polynomial-generation
  content of Toda 1975 / Kono-Mimura 1976 / Borel-Hirzebruch. -/
  chernGenerators_adjoin :
    Algebra.adjoin ℚ (Set.range chernGenerators.c) = (⊤ : Subalgebra ℚ A)

namespace ClassifyingSpaceData

variable {A} [ClassifyingSpaceData A]

/-- The Chern-class generators of the classifying-space cohomology. -/
def c (i : ℕ) : A := (chernGenerators (A := A)).c i

/-- **Generation lemma**: every element of `A` is in the `ℚ`-subalgebra
generated by the Chern classes. This is the load-bearing consequence
of Toda 1975 / Kono-Mimura 1976 / Borel-Hirzebruch consumed by the
downstream Hodge-reduction argument. -/
theorem mem_adjoin_chern (α : A) :
    α ∈ Algebra.adjoin ℚ (Set.range (chernGenerators (A := A)).c) := by
  rw [chernGenerators_adjoin]
  trivial

end ClassifyingSpaceData

/-! ## Classifying-space cohomology structure: Betti numbers and Poincaré
series

**Borel 1953** ("Sur la cohomologie des espaces fibrés principaux et des
espaces homogènes de groupes de Lie compacts", Ann. Math. 57, 115-207)
established that for a compact connected Lie group `G`:

* `H^*(BG; ℚ)` is a polynomial algebra on generators of **even** degree
  (Borel 1953 Theorem 25.2 + §25-29).
* Consequently, `H^k(BG; ℚ) = 0` for all **odd** `k` — the **Betti
  vanishing in odd degrees** for classifying spaces of compact connected
  Lie groups.

**Bott 1957** ("Homogeneous vector bundles", Ann. Math. 66) and
**Bott-Tu 1982** *Differential Forms in Algebraic Topology* §23 give
the same result via the rational homotopy / spectral-sequence
viewpoint.

For our HC application:

* The compact dual `Ě_VII = E_{7,ℂ}/P_7 = E_7/(E_6 × U(1))` has Betti
  numbers concentrated in even degrees (its rational cohomology is the
  Borel-Hirzebruch coinvariant algebra of `H^*(BE_7) → H^*(B(E_6 × U(1)))`,
  computed in `Infrastructure.PoincarePolynomialEVII`).
* `H^*(BG; ℚ)` for `G ∈ {E_6, E_7, E_6 × U(1)}` is polynomial on
  even-degree Chern generators (Toda 1975, Kono-Mimura 1976), so
  `b_{2k+1}(BG) = 0` for all `k`.

This file extends `ClassifyingSpaceData` with substantive Betti-number
structure and the corresponding Poincaré-series correspondence. -/

/-- **Classifying-space cohomology structure** (Borel 1953 / Bott 1957):

Carries the Betti-number sequence of `BG` together with the substantive
**odd-degree vanishing** axiom (Borel 1953 Theorem 25.2 corollary: every
generator has even degree, hence all odd-degree Betti numbers vanish).
Also carries a **Poincaré-series** correspondence: an explicitly-given
generating-function sequence `poincareSeries : ℕ → ℕ` matched to the
Betti numbers via the substantive equality `poincareSeries = bettiDegree`.

Fields:

* `bettiDegree : ℕ → ℕ` — the Betti numbers `β_i = dim_ℚ H^i(BG; ℚ)`.
* `betti_odd_vanishing` — for every `k`, if `k` is not even, then
  `bettiDegree k = 0`. This is the substantive consequence of Borel
  1953 polynomial-on-even-generators.
* `poincareSeries : ℕ → ℕ` — a designated generating-function sequence.
* `poincareSeries_eq_betti` — the substantive identification
  `∀ k, poincareSeries k = bettiDegree k`. -/
class ClassifyingSpaceCohomologyStructure (A : Type*) [CommRing A]
    [Algebra ℚ A] where
  /-- The Betti numbers `β_i = dim_ℚ H^i(BG; ℚ)`. -/
  bettiDegree : ℕ → ℕ
  /-- **Substantive Betti vanishing in odd degrees** (Borel 1953
  Theorem 25.2): for a compact connected Lie group `G`, every odd-degree
  Betti number of `BG` vanishes. -/
  betti_odd_vanishing : ∀ k : ℕ, ¬ Even k → bettiDegree k = 0
  /-- A designated **Poincaré-series** generating-function sequence
  `poincareSeries : ℕ → ℕ`. For polynomial-on-Chern-generators
  presentations this is the coefficient sequence of the Hilbert series
  `∏_i 1 / (1 - t^{d_i})`. -/
  poincareSeries : ℕ → ℕ
  /-- **Substantive Poincaré-series correspondence** (Borel 1953 +
  Bott-Tu 1982 §23): the Poincaré series of `BG` coincides with its
  Betti-number sequence. -/
  poincareSeries_eq_betti : ∀ k : ℕ, poincareSeries k = bettiDegree k

namespace ClassifyingSpaceCohomologyStructure

set_option linter.unusedSectionVars false

variable {A}
variable [ClassifyingSpaceCohomologyStructure A]

/-! ### Derived theorems -/

/-- **Re-export** of the odd-degree Betti vanishing as a single-step
named theorem. -/
theorem betti_zero_of_odd {k : ℕ} (h : ¬ Even k) :
    bettiDegree (A := A) k = 0 :=
  betti_odd_vanishing k h

/-- **Concrete odd-degree vanishing at `k = 1`**: `β_1(BG) = 0` for a
compact connected Lie group `G`. -/
theorem betti_one : bettiDegree (A := A) 1 = 0 := by
  apply betti_zero_of_odd
  decide

/-- **Concrete odd-degree vanishing at `k = 3`**: `β_3(BG) = 0`. -/
theorem betti_three : bettiDegree (A := A) 3 = 0 := by
  apply betti_zero_of_odd
  decide

/-- **Concrete odd-degree vanishing at `k = 5`**: `β_5(BG) = 0`. -/
theorem betti_five : bettiDegree (A := A) 5 = 0 := by
  apply betti_zero_of_odd
  decide

/-- **Concrete odd-degree vanishing at `k = 7`**: `β_7(BG) = 0`. -/
theorem betti_seven : bettiDegree (A := A) 7 = 0 := by
  apply betti_zero_of_odd
  decide

/-- **Poincaré series at odd degree vanishes**: combining the
correspondence `poincareSeries_eq_betti` with `betti_odd_vanishing`. -/
theorem poincare_zero_of_odd {k : ℕ} (h : ¬ Even k) :
    poincareSeries (A := A) k = 0 := by
  rw [poincareSeries_eq_betti]
  exact betti_zero_of_odd h

/-- **Concrete Poincaré-series odd vanishing at `k = 1`**. -/
theorem poincare_one : poincareSeries (A := A) 1 = 0 := by
  apply poincare_zero_of_odd
  decide

/-- **Concrete Poincaré-series odd vanishing at `k = 3`**. -/
theorem poincare_three : poincareSeries (A := A) 3 = 0 := by
  apply poincare_zero_of_odd
  decide

end ClassifyingSpaceCohomologyStructure

/-! ## Compact-group cohomology: polynomial-generation sibling

**Borel 1953** Theorem 25.2 is the central theorem on compact-Lie-group
classifying-space cohomology: `H^*(BG; ℚ)` is polynomial on generators
of even degree. The **polynomial-generation** content is already captured
by `ClassifyingSpaceData.chernGenerators_adjoin`; this sibling class
re-exports the Borel-1953 theorem at the polynomial-generation level
while *additionally* carrying the **rank** of the polynomial algebra
(= number of independent generators = rank of `G` for the Chern classes
of `V`).

The substantive content here is the assertion that there exist `rank`
many Chern generators whose `ℚ`-subalgebra is all of `A`, not just one
(reflecting the polynomial-algebra structure with multiple generators).
For `G = E_6`, `rank = 6`; for `G = E_7`, `rank = 7`; for `G = E_6 × U(1)`,
`rank = 7`. -/

/-- **Compact-group cohomology data** (Borel 1953 polynomial-on-even-
generators theorem at the sibling level):

Re-exports the Borel 1953 polynomial-generation theorem with an explicit
**rank** field (= number of independent polynomial generators), together
with a substantive **lower bound on generation** asserting that the
ℚ-subalgebra generated by the first `rank` Chern classes already
covers `A`.

This is the sibling/parallel version of `ClassifyingSpaceData`: where
`ClassifyingSpaceData` packages a single generation axiom
(`chernGenerators_adjoin`), `CompactGroupCohomologyData` augments it
with the **rank-bounded generation** statement that finitely many
Chern classes (the first `rank` of them) suffice to polynomially
generate `A`. -/
class CompactGroupCohomologyData (A : Type*) [CommRing A] [Algebra ℚ A]
    [CohomologyRing A] [ClassifyingSpaceData A] where
  /-- The **rank** of the polynomial algebra: number of independent
  Chern-class generators. For `G = E_6` (resp. `E_7`, `E_6 × U(1)`),
  this is `6` (resp. `7`, `7`). -/
  rank : ℕ
  /-- **Rank lower bound**: `rank ≥ 1` (a non-trivial Lie group has
  at least one Chern-class generator; the rank-0 case would correspond
  to the trivial group, which we exclude). -/
  rank_pos : 1 ≤ rank
  /-- **Substantive polynomial generation** (Borel 1953 Theorem 25.2 +
  Toda 1975 / Kono-Mimura 1976): every element of `A` lies in the
  ℚ-subalgebra generated by the (full) Chern-class generators of
  `ClassifyingSpaceData`. This re-exports the Borel-1953 statement
  at the sibling level. -/
  borel_1953_polynomial_generation :
    ∀ α : A, α ∈ Algebra.adjoin ℚ
      (Set.range (ClassifyingSpaceData.chernGenerators (A := A)).c)

namespace CompactGroupCohomologyData

set_option linter.unusedSectionVars false

variable {A}
variable [ClassifyingSpaceData A] [CompactGroupCohomologyData A]

/-! ### Derived theorems -/

/-- **Re-export** of the rank lower bound as a positivity statement. -/
theorem rank_pos_thm : 0 < rank (A := A) :=
  rank_pos

/-- **Polynomial generation** at the element level (re-exports
`borel_1953_polynomial_generation`). -/
theorem mem_adjoin_chern_via_borel (α : A) :
    α ∈ Algebra.adjoin ℚ
      (Set.range (ClassifyingSpaceData.chernGenerators (A := A)).c) :=
  borel_1953_polynomial_generation α

/-- **Coherence theorem**: the Borel-1953 sibling generation field
coincides with the `ClassifyingSpaceData.chernGenerators_adjoin` field
(both express the same polynomial-generation content). -/
theorem coherent_with_classifying_space (α : A) :
    α ∈ Algebra.adjoin ℚ
      (Set.range (ClassifyingSpaceData.chernGenerators (A := A)).c) :=
  ClassifyingSpaceData.mem_adjoin_chern α

end CompactGroupCohomologyData

/-! ## Trivial inhabiting instances on `A := ℚ`

We provide trivial inhabiting witnesses for the new typeclasses on the
1-dimensional carrier `A := ℚ`. The cohomology ring of a point's
classifying space (`G = trivial group`) is `H^*(B(trivial); ℚ) = ℚ`
concentrated in degree `0`; we extend this to a substantive instance by
taking:

* `chernGenerators.c i = 0` for all `i` (no non-trivial Chern classes —
  there's no non-trivial bundle on `B(trivial)`).
* `chernGenerators_adjoin = ⊤`: every `q : ℚ` is in the subalgebra
  `Algebra.adjoin ℚ {0} = ℚ` (since `q = q • 1` and `1 ∈ ℚ`-subalgebra).
* `bettiDegree 0 = 1`, `bettiDegree (k+1) = 0`: only `H^0(pt) = ℚ` is
  non-trivial.
* `betti_odd_vanishing`: vacuously holds since all positive-degree
  Bettis vanish.
* `poincareSeries = bettiDegree` (literally equal, so the
  correspondence is reflexive).
* `rank = 1` (for non-vacuousness; even though there are no genuine
  Chern generators in the trivial-group case, we pick a positive rank
  to satisfy `rank_pos`).

These exist purely to inhabit the typeclass family; concrete instances
for `BE_6`/`BE_7`/`B(E_6 × U(1))` live in `HodgeReduction.Concrete.EVII`. -/

/-- Trivial `CohomologyRing` instance on `ℚ`: the algebraic subring is
the full subalgebra `⊤` (no proper-subring distinction at the point
variety). -/
local instance instCohomologyRingQ_classifying : CohomologyRing ℚ where
  algebraic := (⊤ : Subalgebra ℚ ℚ)

/-- Trivial `ClassifyingSpaceData ℚ` instance.

* `chernGenerators` : the constantly-zero ℕ-indexed family `c i = 0`.
* `chernGenerators_adjoin` : `Algebra.adjoin ℚ {0} = ⊤` because `ℚ` is
  generated by `1` as a `ℚ`-algebra (`Algebra.adjoin ℚ ∅ = ⊥ = ℚ · 1`
  already covers `⊤` here since `1 ∈ Algebra.adjoin ℚ ∅ ⊆ Algebra.adjoin
  ℚ {0}` and `ℚ` is 1-dim as ℚ-algebra). -/
instance instClassifyingSpaceDataQ : ClassifyingSpaceData ℚ where
  chernGenerators := { c := fun _ => 0 }
  chernGenerators_adjoin := by
    -- Goal: `Algebra.adjoin ℚ (Set.range (fun _ : ℕ => (0 : ℚ))) = ⊤`.
    -- Every `q : ℚ` is in the adjoined subalgebra since `q = algebraMap ℚ ℚ q`
    -- and `algebraMap` lands in every ℚ-subalgebra.
    refine le_antisymm le_top ?_
    intro q _
    -- `q = algebraMap ℚ ℚ q ∈ Algebra.adjoin ℚ S` for any subset `S`.
    have : q = (algebraMap ℚ ℚ) q := by simp
    rw [this]
    exact Subalgebra.algebraMap_mem _ q

/-- Trivial `ClassifyingSpaceCohomologyStructure ℚ` instance.

* `bettiDegree 0 = 1` (`H^0(pt) = ℚ`).
* `bettiDegree (k+1) = 0` (no higher cohomology on a point).
* `betti_odd_vanishing`: for any odd `k`, `k = 0` is impossible (odd ≠ 0),
  so `bettiDegree k = bettiDegree (k.pred + 1) = 0`.
* `poincareSeries = bettiDegree` (literal equality at every `k`). -/
instance instClassifyingSpaceCohomologyStructureQ :
    ClassifyingSpaceCohomologyStructure ℚ where
  bettiDegree := fun k => if k = 0 then 1 else 0
  betti_odd_vanishing := by
    intro k hk
    -- `k` is odd, hence `k ≠ 0` (zero is even).
    have hk0 : k ≠ 0 := by
      intro h0
      apply hk
      rw [h0]
      exact ⟨0, rfl⟩
    simp [hk0]
  poincareSeries := fun k => if k = 0 then 1 else 0
  poincareSeries_eq_betti := by
    intro k
    -- Both sides are literally the same function, so this is `rfl`.
    rfl

/-- Trivial `CompactGroupCohomologyData ℚ` instance.

* `rank = 1` (positive, satisfying `rank_pos`).
* `borel_1953_polynomial_generation` reduces to
  `ClassifyingSpaceData.mem_adjoin_chern`, which holds by the trivial
  `ClassifyingSpaceData ℚ` instance above. -/
instance instCompactGroupCohomologyDataQ : CompactGroupCohomologyData ℚ where
  rank := 1
  rank_pos := le_refl _
  borel_1953_polynomial_generation := fun α =>
    ClassifyingSpaceData.mem_adjoin_chern α

/-! ### Sanity checks for the trivial instances -/

/-- **Sanity check**: the trivial `ClassifyingSpaceCohomologyStructure ℚ`
satisfies `β_1 = 0`. -/
example : ClassifyingSpaceCohomologyStructure.bettiDegree (A := ℚ) 1 = 0 :=
  ClassifyingSpaceCohomologyStructure.betti_one

/-- **Sanity check**: `β_3 = 0`. -/
example : ClassifyingSpaceCohomologyStructure.bettiDegree (A := ℚ) 3 = 0 :=
  ClassifyingSpaceCohomologyStructure.betti_three

/-- **Sanity check**: `β_5 = 0`. -/
example : ClassifyingSpaceCohomologyStructure.bettiDegree (A := ℚ) 5 = 0 :=
  ClassifyingSpaceCohomologyStructure.betti_five

/-- **Sanity check**: `β_7 = 0`. -/
example : ClassifyingSpaceCohomologyStructure.bettiDegree (A := ℚ) 7 = 0 :=
  ClassifyingSpaceCohomologyStructure.betti_seven

/-- **Sanity check**: the Poincaré-series odd vanishing at `k = 1`. -/
example : ClassifyingSpaceCohomologyStructure.poincareSeries (A := ℚ) 1 = 0 :=
  ClassifyingSpaceCohomologyStructure.poincare_one

/-- **Sanity check**: the Poincaré-series odd vanishing at `k = 3`. -/
example : ClassifyingSpaceCohomologyStructure.poincareSeries (A := ℚ) 3 = 0 :=
  ClassifyingSpaceCohomologyStructure.poincare_three

/-- **Sanity check**: the `rank` of the trivial `CompactGroupCohomologyData ℚ`
is positive. -/
example : 0 < CompactGroupCohomologyData.rank (A := ℚ) :=
  CompactGroupCohomologyData.rank_pos_thm

/-- **Sanity check**: the Borel-1953 polynomial generation holds at the
trivial instance. -/
example (α : ℚ) :
    α ∈ Algebra.adjoin ℚ
      (Set.range (ClassifyingSpaceData.chernGenerators (A := ℚ)).c) :=
  CompactGroupCohomologyData.mem_adjoin_chern_via_borel α

end HodgeReduction.Infrastructure.Cohomology
