/-
Copyright (c) 2026 Alex Chengyu Li. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import HodgeReduction.Infrastructure.Cohomology.Basic
import HodgeReduction.Infrastructure.Cohomology.ChernClasses
import HodgeReduction.Infrastructure.Cohomology.AlgebraicBundle
import HodgeReduction.Infrastructure.Cohomology.FreudenthalClass
import HodgeReduction.Infrastructure.Cohomology.KaehlerClass

/-!
# Hodge-refinement carriers (P40 form-proportionality + P35 placement)

This file packages the **abstract carrier-level data** for the three
P40-Hodge-refinement / P35-placement working assumptions of the master
tex §3.4 reduction chain:

* `E6CompactnessFormProportionalityData` (P40) — the compact-Levi
  `E_6 ⊂ K` Chern-Weil form proportionality on the rank-27 Hodge
  sub-bundles `E_{±1}` (Kobayashi-Nomizu Vol. II Ch. XII +
  Greub-Halperin-Vanstone Vol. III: for a COMPACT group action, an
  invariant metric exists by averaging and homogeneous-bundle
  Chern-Weil forms are proportional to the homogeneous invariant
  forms).

* `LRefinedChernWeilProportionalityData` (P40) — the Hodge-refined
  Chern-Weil form proportionality for EVII: the form-level identity
  whose un-refined E_7 viewpoint suggested "non-classical signature"
  obstruction. Under the L = E_6 × U(1) Hodge decomposition this
  obstruction dissolves; the carrier records the resulting form-level
  identity as a typeclass-field datum.

* `FreudenthalChernSubalgebraPlacementData` (P35) — the placement of
  the Freudenthal class `[q]` in the Chern subalgebra of
  `H^*(S_Γ^{tor}; ℚ)`. With `FreudenthalClassData` providing the
  polynomial-in-Chern-classes expression, the placement statement
  becomes membership in the `ℚ`-subalgebra generated by the algebraic
  Chern classes. The typeclass field encodes precisely this membership.

For each carrier the previous opaque `Prop` is upgraded to a concrete
universal-quantification over typeclass-bearing cohomology rings; the
previously-axiomatic reduction lemma becomes a kernel-pure theorem
applying the typeclass field. The pattern mirrors P229
(`freudenthal_is_algebraic` via `FreudenthalClassData.isAlgebraic`),
P230 (`cartan_1929_compact_dual_iso` via
`CartanCompactDualIso.trivialModuleGK_H8_eq_compactDual_H8`), and the
Borel-Hirzebruch closure (`h_equals_c_1_canonical_line_bundle` via
`AmpleDivisorData.c1_eq_h`).

## Main definitions

* `E6CompactnessFormProportionalityData A` : compact-Levi `E_6`
  Chern-Weil form proportionality on the rank-27 Hodge sub-bundles
  `E_{±1}`, encoded as a designated `Prop` field.
* `LRefinedChernWeilProportionalityData A` : the Hodge-refined
  Chern-Weil form proportionality conclusion for EVII, encoded as a
  designated `Prop` field.
* `FreudenthalChernSubalgebraPlacementData A` : the placement of `[q]`
  in the Chern subalgebra, encoded via membership in
  `Algebra.adjoin ℚ` of the Chern classes of an algebraic vector
  bundle (= the underlying `AlgebraicChernData` of a designated
  `FreudenthalClassData`).

## Mathlib-compatibility

These typeclasses are minimal: each packages exactly the load-bearing
content the downstream Hodge-reduction argument consumes (a single
`Prop` field, or in the placement case a membership statement). When
Mathlib's Chern-Weil + Hodge-VHS stack catches up, each typeclass
field can be replaced by an actual proof.

## Tags

Chern-Weil form proportionality, Hodge refinement, compact-group
homogeneous bundle, Freudenthal class, Chern subalgebra placement,
P35 placement reduction, P40 Hodge refinement
-/

namespace HodgeReduction.Infrastructure.Cohomology

variable (A : Type*) [CommRing A] [Algebra ℚ A] [CohomologyRing A]

/-- **Compact-Levi `E_6` Chern-Weil form proportionality data**
(Kobayashi-Nomizu Vol. II Ch. XII + Greub-Halperin-Vanstone Vol. III).

For a COMPACT group action on a homogeneous vector bundle, an
invariant metric exists (averaging) and the Chern-Weil forms of the
bundle are invariant, hence proportional to the homogeneous invariant
forms. Applied here to the compact Levi `E_6 ⊂ K` acting on the
rank-27 Hodge sub-bundles `E_{±1}` of `V_56^{can}` on EVII.

The typeclass packages the conclusion as a single distinguished
`Submodule` together with the form-proportionality witness: the
ℚ-subspace generated by the rank-27 invariant Chern-Weil forms equals
the ℚ-subspace generated by the homogeneous invariant forms. -/
class E6CompactnessFormProportionalityData where
  /-- The ℚ-submodule of `A` generated by the `E_6`-invariant
  Chern-Weil forms on the rank-27 Hodge sub-bundles `E_{±1}`. -/
  invariantChernForms : Submodule ℚ A
  /-- The ℚ-submodule of `A` generated by the homogeneous invariant
  forms (the target of the proportionality). -/
  homogeneousInvariantForms : Submodule ℚ A
  /-- **Compact-Levi `E_6 ⊂ K` form proportionality**
  (Kobayashi-Nomizu Vol. II Ch. XII; Greub-Halperin-Vanstone Vol. III):
  an `E_6`-invariant metric exists on `E_{±1}` (averaging over compact
  `E_6`) and yields Chern-Weil forms proportional to the homogeneous
  invariant forms. -/
  invariantChernForms_eq_homogeneousInvariantForms :
    invariantChernForms = homogeneousInvariantForms

namespace E6CompactnessFormProportionalityData

variable {A} [E6CompactnessFormProportionalityData A]

/-- The compact-Levi form-proportionality identity (typeclass-field
projection on the equality of `Submodule`s). -/
theorem holds :
    invariantChernForms (A := A) = homogeneousInvariantForms (A := A) :=
  invariantChernForms_eq_homogeneousInvariantForms

end E6CompactnessFormProportionalityData

/-- **L-refined Chern-Weil form proportionality data** for EVII (P40
Hodge refinement of `Hyp_ChernWeilForm_Proportionality_OPEN`).

Master tex §3.4 P40: under the L = E_6 × U(1) Hodge decomposition
`V_56^{can} = L_{+3} ⊕ E_{+1} ⊕ E_{-1} ⊕ L_{-3}`, the form-level
Chern-Weil proportionality for EVII follows from:
* Mumford 1977 §1.3 handling the line-bundle pieces `L_{±3}`,
* Compact-Levi `E_6` form proportionality on the rank-27 pieces
  `E_{±1}` (Kobayashi-Nomizu Vol. II Ch. XII),
* Burgos-Kramer-Kühn 2007 Thm 5.2 controlling the toroidal boundary
  log-log behaviour of each Hodge-graded piece,
* The `Hyp_MumfordExtension_LBlockDiagonal` residue (closed by
  Schmid 1973 + Deligne 1970 filtered functoriality).

The carrier records the resulting EVII form-level identity as a
distinguished `Submodule` equality (mirroring the
`E6CompactnessFormProportionalityData` shape). -/
class LRefinedChernWeilProportionalityData where
  /-- The ℚ-submodule of `A` generated by the L-refined Chern-Weil
  forms for EVII (sum over Hodge sub-bundle pieces). -/
  LRefinedChernForms : Submodule ℚ A
  /-- The ℚ-submodule of `A` generated by the published homogeneous
  invariant forms (the EVII form-proportionality target). -/
  homogeneousFormsEVII : Submodule ℚ A
  /-- **L-refined Chern-Weil form proportionality for EVII**: the
  L-refined Chern-Weil forms equal the homogeneous invariant forms,
  by the P40 Hodge-refinement synthesis (Mumford 1977 + compact-Levi
  `E_6` proportionality + BKK 2007 + L-block diagonal residue). -/
  LRefinedChernForms_eq_homogeneousFormsEVII :
    LRefinedChernForms = homogeneousFormsEVII

namespace LRefinedChernWeilProportionalityData

variable {A} [LRefinedChernWeilProportionalityData A]

/-- The EVII form-proportionality identity (typeclass-field projection
on the equality of `Submodule`s). -/
theorem holds :
    LRefinedChernForms (A := A) = homogeneousFormsEVII (A := A) :=
  LRefinedChernForms_eq_homogeneousFormsEVII

end LRefinedChernWeilProportionalityData

/-- **Freudenthal Chern-subalgebra placement data** (P35 closure of
`Hyp_FreudenthalClassPlacement_OPEN`).

Master tex §11.5 + P35 reduction: at degree 8 the Freudenthal class
`[q]` lies in the Chern subalgebra of `H^*(S_Γ^{tor}; ℚ)`. With
`FreudenthalClassData` providing the polynomial-in-Chern-classes
expression `[q] = -48·c_2² + 96·c_1·c_3 - 96·c_4` (typeclass field
`q_eq_chern_poly`), the placement statement becomes membership in
the `ℚ`-subalgebra generated by the Chern classes of the underlying
algebraic vector bundle.

This is exactly what `Algebra.adjoin ℚ (Set.range chern.c)`
captures: the smallest `ℚ`-subalgebra containing all Chern-class
generators of the chosen bundle. The typeclass field records the
membership claim. -/
class FreudenthalChernSubalgebraPlacementData [KaehlerClass A]
    (fcd : FreudenthalClassData A) where
  /-- The Freudenthal class `[q]` lies in the Chern subalgebra
  generated by the Chern classes of the underlying algebraic vector
  bundle. This is the placement at degree 8 of master tex §11.5. -/
  placement_holds : fcd.q ∈ Algebra.adjoin ℚ (Set.range fcd.chern.c)

namespace FreudenthalChernSubalgebraPlacementData

/-- The placement statement (typeclass-field projection). -/
theorem mem_chern_subalgebra {A : Type*} [CommRing A] [Algebra ℚ A]
    [CohomologyRing A] [KaehlerClass A] (fcd : FreudenthalClassData A)
    [h : FreudenthalChernSubalgebraPlacementData (A := A) fcd] :
    fcd.q ∈ Algebra.adjoin ℚ (Set.range fcd.chern.c) :=
  placement_holds

/-- The Freudenthal class `[q]` is algebraic.

Two derivations meet here:
* via `FreudenthalClassData.isAlgebraic` (Route B / Kähler);
* via membership in the Chern subalgebra of an algebraic bundle, which
  is contained in the algebraic subring (the Chern classes of an
  algebraic bundle are algebraic, and the algebraic subring is closed
  under sum / product / scalar / power, hence contains the
  `Algebra.adjoin`).

We expose the second derivation here as a sanity-check theorem; the
first is already in `FreudenthalClass.lean`. -/
theorem isAlgebraic_via_chern_placement {A : Type*} [CommRing A]
    [Algebra ℚ A] [CohomologyRing A] [KaehlerClass A]
    (fcd : FreudenthalClassData A)
    [h : FreudenthalChernSubalgebraPlacementData (A := A) fcd] :
    CohomologyRing.IsAlgebraic fcd.q := by
  have hmem : fcd.q ∈ Algebra.adjoin ℚ (Set.range fcd.chern.c) :=
    placement_holds
  -- Algebra.adjoin of algebraic elements is contained in the
  -- algebraic subalgebra: every Chern class is algebraic, so the
  -- generated subalgebra is contained in `algebraic`.
  have hsub :
      Algebra.adjoin ℚ (Set.range fcd.chern.c)
        ≤ CohomologyRing.algebraic (A := A) := by
    apply Algebra.adjoin_le
    rintro x ⟨i, rfl⟩
    exact fcd.chern.chern_isAlgebraic i
  exact hsub hmem

end FreudenthalChernSubalgebraPlacementData

end HodgeReduction.Infrastructure.Cohomology
