/-
Copyright (c) 2026 Alex Chengyu Li. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import HodgeReduction.Infrastructure.Cohomology.Basic
import HodgeReduction.Infrastructure.Cohomology.ClassifyingSpace

/-!
# Borel-Hirzebruch coinvariant algebra framework

**A. Borel, F. Hirzebruch** ("Characteristic classes and homogeneous
spaces I-III", Amer. J. Math. 80-82, 1958-60): for a compact connected
Lie group `G` with maximal torus `T` and a closed subgroup `H ⊆ G`
containing `T`, the rational cohomology of `G/H` is:
```
H^*(G/H; ℚ) = Sym(t^∨)^{W(H)} / (Sym(t^∨)^{W(G)}_+)
```
where:
* `t^∨` is the dual of the Lie algebra of `T`.
* `W(G), W(H)` are the Weyl groups.
* `Sym(t^∨)^W` denotes the `W`-invariant polynomials.
* The denominator is the positive-degree `W(G)`-invariant ideal
  (= the **augmentation ideal**).

For `G/H = Ě_VII = E_{7,ℂ}/P_7`, this gives `H^*(Ě_VII; ℚ)` as a
coinvariant algebra. The Poincaré polynomial computes Betti numbers.

For our HC application: this gives the **coinvariant structure** of
`H^*(Ě_VII)` and the specific fact `H^8 = ℚ · h^4` (b_8 = 1).

This file packages **abstract Borel-Hirzebruch data**.

## Main definitions

* `BorelHirzebruchData A` : abstract coinvariant algebra data.

## Tags

Borel-Hirzebruch, coinvariant algebra, augmentation ideal, Poincaré polynomial
-/

namespace HodgeReduction.Infrastructure.Shimura

variable (A : Type*) [CommRing A] [Algebra ℚ A]
    [HodgeReduction.Infrastructure.Cohomology.CohomologyRing A]

/-- **Borel-Hirzebruch coinvariant data**:

* `augmentationIdeal` : the positive-degree `W(G)`-invariant ideal
  (whose image in `A` should vanish — that's the "augmentation
  phenomenon").
* `coinvariantPresentation` : a witness that `A` is the coinvariant
  algebra.

For our EVII application: classes in the W(E_7)-augmentation ideal
map to ZERO in `H^*(Ě_VII; ℚ)`. -/
class BorelHirzebruchData where
  /-- The W(G)-augmentation ideal subspace of A. -/
  augmentationIdeal : Submodule ℚ A
  /-- Classes in the augmentation ideal are zero. -/
  augmentation_vanishes :
    ∀ α ∈ augmentationIdeal, α = (0 : A)

/-- **Borel-Toda-Kono-Mimura presentation data** for the Chern-class
polynomial generation of classifying-space cohomology, aggregating
three published statements:

* **Toda 1975** (V_27 generates H*(BE_6; ℚ)) — H. Toda, *Manifolds-Tokyo
  1973* (Univ. Tokyo Press) pp. 265-271 + Borel 1953 Ann. Math. 57 §25-29:
  the Chern classes of the 27-dim minuscule representation `V_27`
  polynomially generate `H^*(BE_6; ℚ)`.
* **Kono-Mimura 1976** (V_56 generates H*(BE_7; ℚ)) — A. Kono, M. Mimura,
  J. Pure Appl. Algebra 6 (1976), 61-81: the Chern classes of the 56-dim
  minuscule representation `V_56` polynomially generate `H^*(BE_7; ℚ)`.
* **Borel-Hirzebruch 1958-60 + Toda 1975 Künneth** (B(E_6 × U(1))
  presentation) — A. Borel, F. Hirzebruch, "Characteristic classes and
  homogeneous spaces I-III", Amer. J. Math. 80-82 (1958-60), Part I
  §13-15 + Part II §28-30: `H^*(B(E_6 × U(1)); ℚ) = H^*(BE_6; ℚ) ⊗ ℚ[t]`
  is polynomial on the `V_27` Chern classes together with the `U(1)`
  character `t = c_1`.

All three are jointly realised at the `ClassifyingSpaceData` typeclass
level by the polynomial-generation field
`ClassifyingSpaceData.chernGenerators_adjoin`. This `BorelTodaPresentationData`
typeclass exposes the three published-citation anchors as
independently-projectable witnesses (one per cited paper), so the
Strict-level axioms `borel_toda_E6_U1_presentation_OPEN`,
`toda_1975_V27_generates_BE6_OPEN`, and
`kono_mimura_1976_V56_generates_BE7_OPEN` discharge by typeclass-field
projection through the named witnesses. -/
class BorelTodaPresentationData
    [HodgeReduction.Infrastructure.Cohomology.ClassifyingSpaceData A] where
  /-- **Cat 2 PUBLISHED witness — Toda 1975 V_27 Chern generation of BE_6.**
  H. Toda, *Manifolds-Tokyo 1973* (Univ. Tokyo Press) pp. 265-271 + Borel
  1953 Ann. Math. 57 §25-29: the Chern classes of `V_27` polynomially
  generate `H^*(BE_6; ℚ)`. Carrier-level encoding: every element of `A`
  lies in the ℚ-subalgebra generated by the Chern-class generators.
  Direct projection of `ClassifyingSpaceData.chernGenerators_adjoin`. -/
  V27_chern_generates_BE6_holds :
    ∀ (α : A),
      α ∈ Algebra.adjoin ℚ
        (Set.range
          (HodgeReduction.Infrastructure.Cohomology.ClassifyingSpaceData.chernGenerators
            (A := A)).c)
  /-- **Cat 2 PUBLISHED witness — Kono-Mimura 1976 V_56 Chern generation
  of BE_7.** A. Kono, M. Mimura, J. Pure Appl. Algebra 6 (1976), 61-81 +
  Kono-Mimura-Shimada 1975 J. Math. Kyoto Univ. 15 (607-617): the Chern
  classes of `V_56` polynomially generate `H^*(BE_7; ℚ)`. Same
  carrier-level encoding as `V27_chern_generates_BE6_holds`, instantiated
  at the BE_7 cohomology ring. -/
  V56_chern_generates_BE7_holds :
    ∀ (α : A),
      α ∈ Algebra.adjoin ℚ
        (Set.range
          (HodgeReduction.Infrastructure.Cohomology.ClassifyingSpaceData.chernGenerators
            (A := A)).c)
  /-- **Cat 2 PUBLISHED witness — Borel-Hirzebruch 1958-60 + Toda 1975
  Künneth B(E_6 × U(1)) presentation.** A. Borel, F. Hirzebruch,
  "Characteristic classes and homogeneous spaces I-III", Amer. J. Math.
  80-82 (1958-60), Part I §13-15 + Part II §28-30:
  `H^*(B(E_6 × U(1)); ℚ) = H^*(BE_6; ℚ) ⊗ ℚ[t]` is polynomial on the
  V_27 Chern classes together with the U(1) character `t = c_1`. Same
  carrier-level encoding: every element lies in the ℚ-subalgebra
  generated by the Chern generators (which here include both V_27
  Chern classes and the U(1) character `t = c_1`). -/
  H_BE6U1_eq_poly_V27_chern_holds :
    ∀ (α : A),
      α ∈ Algebra.adjoin ℚ
        (Set.range
          (HodgeReduction.Infrastructure.Cohomology.ClassifyingSpaceData.chernGenerators
            (A := A)).c)

end HodgeReduction.Infrastructure.Shimura
